import type { Genre, VibeContent } from '../../types/index.js';

export const collegeGenre: Genre = {
  id: 'college',
  name: 'College World',
  description: 'Campus, exams, professors, hostel, parties, student life.',
  icon: '🎓',
  levels: {
    1: [
      { id: 'col_1_1', leftLabel: 'Boring Lecture', rightLabel: 'Amazing Lecture', difficulty: 1 },
      { id: 'col_1_2', leftLabel: 'Easy Exam', rightLabel: 'Impossible Exam', difficulty: 1 },
      { id: 'col_1_3', leftLabel: 'Early Class', rightLabel: 'Perfect Class', difficulty: 1 },
      { id: 'col_1_4', leftLabel: 'Bad Cafeteria Food', rightLabel: 'Great Cafeteria Food', difficulty: 1 },
      { id: 'col_1_5', leftLabel: 'Strict Professor', rightLabel: 'Chill Professor', difficulty: 1 },
      { id: 'col_1_6', leftLabel: 'Empty Library', rightLabel: 'Packed Library', difficulty: 1 },
      { id: 'col_1_7', leftLabel: 'Short Assignment', rightLabel: 'Endless Assignment', difficulty: 1 },
      { id: 'col_1_8', leftLabel: 'Awkward Icebreaker', rightLabel: 'Fun Icebreaker', difficulty: 1 },
      { id: 'col_1_9', leftLabel: 'Terrible Roommate', rightLabel: 'Best Roommate', difficulty: 1 },
      { id: 'col_1_10', leftLabel: 'Quiet Dorm', rightLabel: 'Loud Dorm', difficulty: 1 },
      { id: 'col_1_11', leftLabel: 'Skipped Class', rightLabel: 'Attended Class', difficulty: 1 },
      { id: 'col_1_12', leftLabel: 'Failed Test', rightLabel: 'Aced Test', difficulty: 1 },
      { id: 'col_1_13', leftLabel: 'Cramming', rightLabel: 'Studying Ahead', difficulty: 1 },
      { id: 'col_1_14', leftLabel: 'Cheap Beer', rightLabel: 'Expensive Cocktail', difficulty: 1 },
      { id: 'col_1_15', leftLabel: 'Walking in the Rain', rightLabel: 'Taking the Bus', difficulty: 1 },
      { id: 'col_1_16', leftLabel: 'Morning Person', rightLabel: 'Night Owl', difficulty: 1 },
      { id: 'col_1_17', leftLabel: 'Freshman', rightLabel: 'Senior', difficulty: 1 },
      { id: 'col_1_18', leftLabel: 'Greek Life', rightLabel: 'Independent', difficulty: 1 },
      { id: 'col_1_19', leftLabel: 'A', rightLabel: 'F', difficulty: 1 },
      { id: 'col_1_20', leftLabel: 'STEM Major', rightLabel: 'Humanities Major', difficulty: 1 },
    ],
    2: [
      { id: 'col_2_1', leftLabel: 'Professor who uses PowerPoint', rightLabel: 'Professor who just talks', difficulty: 2 },
      { id: 'col_2_2', leftLabel: 'The library during midterms', rightLabel: 'The library during finals', difficulty: 2 },
      { id: 'col_2_3', leftLabel: 'A 5-page paper', rightLabel: 'A 10-minute presentation', difficulty: 2 },
      { id: 'col_2_4', leftLabel: 'Dining hall breakfast', rightLabel: 'Dining hall dinner', difficulty: 2 },
      { id: 'col_2_5', leftLabel: 'Group project leader', rightLabel: 'Group project slacker', difficulty: 2 },
      { id: 'col_2_6', leftLabel: '8 AM class in winter', rightLabel: 'Friday afternoon class', difficulty: 2 },
      { id: 'col_2_7', leftLabel: 'A syllabus week party', rightLabel: 'A post-finals party', difficulty: 2 },
      { id: 'col_2_8', leftLabel: 'Living on campus', rightLabel: 'Commuting from home', difficulty: 2 },
      { id: 'col_2_9', leftLabel: 'Buying new textbooks', rightLabel: 'Pirating PDFs', difficulty: 2 },
      { id: 'col_2_10', leftLabel: 'The smell of a frat house', rightLabel: 'The smell of a bio lab', difficulty: 2 },
      { id: 'col_2_11', leftLabel: 'Doing the reading', rightLabel: 'Skimming the reading', difficulty: 2 },
      { id: 'col_2_12', leftLabel: 'A TA that grades harshly', rightLabel: 'A professor that grades harshly', difficulty: 2 },
      { id: 'col_2_13', leftLabel: 'Using Chegg', rightLabel: 'Going to office hours', difficulty: 2 },
      { id: 'col_2_14', leftLabel: 'A minor in business', rightLabel: 'A minor in philosophy', difficulty: 2 },
      { id: 'col_2_15', leftLabel: 'A messy dorm room', rightLabel: 'A spotless dorm room', difficulty: 2 },
      { id: 'col_2_16', leftLabel: 'Taking notes on a laptop', rightLabel: 'Taking notes by hand', difficulty: 2 },
      { id: 'col_2_17', leftLabel: 'Eating ramen', rightLabel: 'Eating out', difficulty: 2 },
      { id: 'col_2_18', leftLabel: 'A major you love', rightLabel: 'A major that pays well', difficulty: 2 },
      { id: 'col_2_19', leftLabel: 'The campus gym', rightLabel: 'The campus library', difficulty: 2 },
      { id: 'col_2_20', leftLabel: 'A long weekend', rightLabel: 'Spring break', difficulty: 2 },
    ],
    3: [
      { id: 'col_3_1', leftLabel: 'The feeling of finishing finals', rightLabel: 'The feeling of starting syllabus week', difficulty: 3 },
      { id: 'col_3_2', leftLabel: 'A professor who thinks their class is the only one you take', rightLabel: 'A professor who forgets they teach the class', difficulty: 3 },
      { id: 'col_3_3', leftLabel: 'The stress of choosing a major', rightLabel: 'The stress of applying for jobs', difficulty: 3 },
      { id: 'col_3_4', leftLabel: 'A roommate who never leaves', rightLabel: 'A roommate you never see', difficulty: 3 },
      { id: 'col_3_5', leftLabel: 'The illusion of free time', rightLabel: 'The reality of procrastination', difficulty: 3 },
      { id: 'col_3_6', leftLabel: 'A lecture that changes your life', rightLabel: 'A lecture you immediately forget', difficulty: 3 },
      { id: 'col_3_7', leftLabel: 'The imposter syndrome in a seminar', rightLabel: 'The Dunning-Kruger effect in a 101 class', difficulty: 3 },
      { id: 'col_3_8', leftLabel: 'A friend you only see in class', rightLabel: 'A friend you only see at parties', difficulty: 3 },
      { id: 'col_3_9', leftLabel: 'The guilt of skipping class', rightLabel: 'The regret of attending a useless class', difficulty: 3 },
      { id: 'col_3_10', leftLabel: 'A curve that saves your grade', rightLabel: 'A curve that ruins your grade', difficulty: 3 },
      { id: 'col_3_11', leftLabel: 'The politics of student government', rightLabel: 'The politics of a group chat', difficulty: 3 },
      { id: 'col_3_12', leftLabel: 'A degree as a piece of paper', rightLabel: 'A degree as a transformative experience', difficulty: 3 },
      { id: 'col_3_13', leftLabel: 'The fear of graduation', rightLabel: 'The desperation to graduate', difficulty: 3 },
      { id: 'col_3_14', leftLabel: 'A networking event', rightLabel: 'A job fair', difficulty: 3 },
      { id: 'col_3_15', leftLabel: 'The cafeteria salad bar', rightLabel: 'The cafeteria mystery meat', difficulty: 3 },
      { id: 'col_3_16', leftLabel: 'A deep philosophical discussion at 3 AM', rightLabel: 'A nonsensical argument at 3 AM', difficulty: 3 },
      { id: 'col_3_17', leftLabel: 'The burden of student loans', rightLabel: 'The privilege of a full ride', difficulty: 3 },
      { id: 'col_3_18', leftLabel: 'A campus tradition that is fun', rightLabel: 'A campus tradition that is a hazing ritual', difficulty: 3 },
      { id: 'col_3_19', leftLabel: 'The freshman 15', rightLabel: 'The senior slump', difficulty: 3 },
      { id: 'col_3_20', leftLabel: 'A study abroad trip that changes you', rightLabel: 'A study abroad trip that was just a vacation', difficulty: 3 },
    ],
    4: [
      { id: 'col_4_1', leftLabel: 'The realization that nobody knows what they are doing', rightLabel: 'The realization that adults are just older children', difficulty: 4 },
      { id: 'col_4_2', leftLabel: 'The commodification of higher education', rightLabel: 'The pursuit of knowledge for its own sake', difficulty: 4 },
      { id: 'col_4_3', leftLabel: 'A syllabus as a binding contract', rightLabel: 'A syllabus as a rough suggestion', difficulty: 4 },
      { id: 'col_4_4', leftLabel: 'The existential dread of a blank Word document', rightLabel: 'The panic of a 11:59 PM deadline', difficulty: 4 },
      { id: 'col_4_5', leftLabel: 'The difference between being smart and being good at school', rightLabel: 'The difference between being educated and being intelligent', difficulty: 4 },
      { id: 'col_4_6', leftLabel: 'The artificial bubble of a college campus', rightLabel: 'The harsh reality of the real world', difficulty: 4 },
      { id: 'col_4_7', leftLabel: 'A letter of recommendation from a Nobel laureate', rightLabel: 'A letter of recommendation from an employer', difficulty: 4 },
      { id: 'col_4_8', leftLabel: 'The romanticization of the starving student', rightLabel: 'The actual poverty of being a student', difficulty: 4 },
      { id: 'col_4_9', leftLabel: 'A thesis that nobody will ever read', rightLabel: 'A tweet that goes viral', difficulty: 4 },
      { id: 'col_4_10', leftLabel: 'The sunk cost fallacy of a double major', rightLabel: 'The terrifying freedom of dropping out', difficulty: 4 },
      { id: 'col_4_11', leftLabel: 'The aesthetics of academia (Dark Academia)', rightLabel: 'The reality of academia (exhaustion)', difficulty: 4 },
      { id: 'col_4_12', leftLabel: 'A professor who is a brilliant researcher but a terrible teacher', rightLabel: 'A professor who is a great teacher but hasn\'t published in years', difficulty: 4 },
      { id: 'col_4_13', leftLabel: 'The pressure to have the "best four years of your life"', rightLabel: 'The reality that it\'s just four years of your life', difficulty: 4 },
      { id: 'col_4_14', leftLabel: 'The illusion of meritocracy in admissions', rightLabel: 'The reality of legacy preferences', difficulty: 4 },
      { id: 'col_4_15', leftLabel: 'A relationship that survives graduation', rightLabel: 'A relationship that ends at graduation', difficulty: 4 },
      { id: 'col_4_16', leftLabel: 'The difference between learning and memorizing', rightLabel: 'The difference between passing and excelling', difficulty: 4 },
      { id: 'col_4_17', leftLabel: 'The campus as a safe space', rightLabel: 'The campus as an ideological battleground', difficulty: 4 },
      { id: 'col_4_18', leftLabel: 'The paralyzing fear of picking the wrong career path', rightLabel: 'The liberating realization that a career path is not fixed', difficulty: 4 },
      { id: 'col_4_19', leftLabel: 'The most useful thing you learned in college was soft skills', rightLabel: 'The most useful thing you learned in college was how to network', difficulty: 4 },
      { id: 'col_4_20', leftLabel: 'A degree as a status symbol', rightLabel: 'A degree as a minimum requirement', difficulty: 4 },
    ],
    5: [
      { id: 'col_5_1', leftLabel: 'The ivory tower', rightLabel: 'The trenches', difficulty: 5 },
      { id: 'col_5_2', leftLabel: 'Is college a scam?', rightLabel: 'Is college the great equalizer?', difficulty: 5 },
      { id: 'col_5_3', leftLabel: 'The tragedy of specializing too early', rightLabel: 'The danger of being a jack of all trades', difficulty: 5 },
      { id: 'col_5_4', leftLabel: 'The search for truth', rightLabel: 'The search for funding', difficulty: 5 },
      { id: 'col_5_5', leftLabel: 'The paradox of paying for an education you can get at a public library', rightLabel: 'The value of the piece of paper', difficulty: 5 },
      { id: 'col_5_6', leftLabel: 'The end of youth', rightLabel: 'The beginning of adulthood', difficulty: 5 },
      { id: 'col_5_7', leftLabel: 'The concept of "potential"', rightLabel: 'The burden of "expectations"', difficulty: 5 },
      { id: 'col_5_8', leftLabel: 'A generation defined by debt', rightLabel: 'A generation defined by access to information', difficulty: 5 },
      { id: 'col_5_9', leftLabel: 'The illusion of prestige', rightLabel: 'The reality of alumni networks', difficulty: 5 },
      { id: 'col_5_10', leftLabel: 'The most profound lecture you ever slept through', rightLabel: 'The most trivial assignment you agonized over', difficulty: 5 },
      { id: 'col_5_11', leftLabel: 'The democratization of knowledge', rightLabel: 'The gatekeeping of credentials', difficulty: 5 },
      { id: 'col_5_12', leftLabel: 'A transformative intellectual awakening', rightLabel: 'A very expensive networking club', difficulty: 5 },
      { id: 'col_5_13', leftLabel: 'The fear of leaving the bubble', rightLabel: 'The desperation to burst the bubble', difficulty: 5 },
      { id: 'col_5_14', leftLabel: 'The obsolescence of the university model', rightLabel: 'The enduring necessity of a physical campus', difficulty: 5 },
      { id: 'col_5_15', leftLabel: 'The most important lesson wasn\'t on the syllabus', rightLabel: 'The most important lesson was that the syllabus was a lie', difficulty: 5 },
      { id: 'col_5_16', leftLabel: 'The arbitrary nature of grading', rightLabel: 'The arbitrary nature of success', difficulty: 5 },
      { id: 'col_5_17', leftLabel: 'The tragedy of the adjunct professor', rightLabel: 'The bloat of university administration', difficulty: 5 },
      { id: 'col_5_18', leftLabel: 'The university as a corporation', rightLabel: 'The university as a sanctuary of thought', difficulty: 5 },
      { id: 'col_5_19', leftLabel: 'The fleeting nature of college friendships', rightLabel: 'The enduring bonds forged in shared misery', difficulty: 5 },
      { id: 'col_5_20', leftLabel: 'A stepping stone', rightLabel: 'The peak', difficulty: 5 },
    ],
  },
};
