import type { Genre, VibeContent } from '../../types/index.js';

export const everydayGenre: Genre = {
  id: 'everyday',
  name: 'Everyday Life',
  description:
    'Relatable Indian life, awkward moments, family drama, money problems, social chaos, dating disasters and everyday situations.',
  icon: '🌎',
  levels: {
    // ============================================================
    // LEVEL 1 — EVERYDAY CHAOS
    // ============================================================
    1: [
      { id: 'evy_1_1', leftLabel: 'Good Morning', rightLabel: 'Already Tired', difficulty: 1 },
      { id: 'evy_1_2', leftLabel: 'One Alarm', rightLabel: 'Seven Alarms', difficulty: 1 },
      { id: 'evy_1_3', leftLabel: 'Freshly Showered', rightLabel: 'Need Another Shower', difficulty: 1 },
      { id: 'evy_1_4', leftLabel: 'Clean Room', rightLabel: 'Clothes Everywhere', difficulty: 1 },
      { id: 'evy_1_5', leftLabel: 'Making Breakfast', rightLabel: 'Ordering Breakfast', difficulty: 1 },
      { id: 'evy_1_6', leftLabel: 'Healthy Breakfast', rightLabel: 'Maggi for Breakfast', difficulty: 1 },
      { id: 'evy_1_7', leftLabel: 'Five Minute Nap', rightLabel: 'Three Hour Nap', difficulty: 1 },
      { id: 'evy_1_8', leftLabel: 'One Reel', rightLabel: 'Two Hours Scrolling', difficulty: 1 },
      { id: 'evy_1_9', leftLabel: 'Quick Shower', rightLabel: 'Bathroom Concert', difficulty: 1 },
      { id: 'evy_1_10', leftLabel: 'Saving Money', rightLabel: 'Ordering Food Again', difficulty: 1 },
      { id: 'evy_1_11', leftLabel: '₹100 Purchase', rightLabel: '₹2,000 Somehow', difficulty: 1 },
      { id: 'evy_1_12', leftLabel: 'Checking Bank Balance', rightLabel: 'Instant Regret', difficulty: 1 },
      { id: 'evy_1_13', leftLabel: 'Short Queue', rightLabel: 'Never-Ending Queue', difficulty: 1 },
      { id: 'evy_1_14', leftLabel: 'Five Minute Traffic', rightLabel: 'Bumper-To-Bumper Traffic', difficulty: 1 },
      { id: 'evy_1_15', leftLabel: 'Perfect Weather', rightLabel: 'Delhi-Level Heat', difficulty: 1 },
      { id: 'evy_1_16', leftLabel: 'Light Rain', rightLabel: 'Unexpected Downpour', difficulty: 1 },
      { id: 'evy_1_17', leftLabel: 'Umbrella Ready', rightLabel: 'Umbrella Missing', difficulty: 1 },
      { id: 'evy_1_18', leftLabel: 'Finding Parking', rightLabel: 'Parking Mission Impossible', difficulty: 1 },
      { id: 'evy_1_19', leftLabel: 'Easy UPI Payment', rightLabel: 'UPI Suddenly Not Working', difficulty: 1 },
      { id: 'evy_1_20', leftLabel: 'Full Phone Battery', rightLabel: '3% Battery', difficulty: 1 },
      { id: 'evy_1_21', leftLabel: 'Fast Wi-Fi', rightLabel: 'Loading Forever', difficulty: 1 },
      { id: 'evy_1_22', leftLabel: 'One Notification', rightLabel: 'Notification Explosion', difficulty: 1 },
      { id: 'evy_1_23', leftLabel: 'Reply Immediately', rightLabel: 'Reply Tomorrow', difficulty: 1 },
      {
        id: 'evy_1_24', leftLabel: "I'll Reply Later", rightLabel: 'Completely Forgot', difficulty: 1
      },
      { id: 'evy_1_25', leftLabel: 'Weekend Plans', rightLabel: 'Weekend Sleep', difficulty: 1 },
      { id: 'evy_1_26', leftLabel: 'Going to the Gym', rightLabel: 'Thinking About Gym', difficulty: 1 },
      { id: 'evy_1_27', leftLabel: 'Healthy Snack', rightLabel: 'Chips at Midnight', difficulty: 1 },
      { id: 'evy_1_28', leftLabel: 'One Cup of Chai', rightLabel: 'Third Cup of Chai', difficulty: 1 },
      { id: 'evy_1_29', leftLabel: 'Simple Lunch', rightLabel: 'Food Coma', difficulty: 1 },
      { id: 'evy_1_30', leftLabel: 'Small Grocery Trip', rightLabel: 'Five Shopping Bags', difficulty: 1 },
      { id: 'evy_1_31', leftLabel: 'One Online Order', rightLabel: 'Five Packages', difficulty: 1 },
      { id: 'evy_1_32', leftLabel: 'Window Shopping', rightLabel: 'Accidental Shopping', difficulty: 1 },
      { id: 'evy_1_33', leftLabel: 'Just Browsing', rightLabel: 'Added to Cart', difficulty: 1 },
      { id: 'evy_1_34', leftLabel: 'Added to Cart', rightLabel: 'Actually Bought It', difficulty: 1 },
      { id: 'evy_1_35', leftLabel: 'Quick Nap', rightLabel: 'Waking Up Confused', difficulty: 1 },
      { id: 'evy_1_36', leftLabel: 'Early Bedtime', rightLabel: '2 AM Suddenly', difficulty: 1 },
      { id: 'evy_1_37', leftLabel: 'One Episode', rightLabel: 'Entire Season', difficulty: 1 },
      { id: 'evy_1_38', leftLabel: 'Watching a Movie', rightLabel: 'Checking Phone Every Five Minutes', difficulty: 1 },
      { id: 'evy_1_39', leftLabel: 'Silent Phone', rightLabel: 'Group Chat Chaos', difficulty: 1 },
      { id: 'evy_1_40', leftLabel: 'Peaceful Morning', rightLabel: 'Family Calling', difficulty: 1 },
      { id: 'evy_1_41', leftLabel: 'One Parent Call', rightLabel: 'Seven Missed Calls', difficulty: 1 },
      { id: 'evy_1_42', leftLabel: 'Simple Question', rightLabel: 'Full Family Interrogation', difficulty: 1 },
      { id: 'evy_1_43', leftLabel: 'Normal Dinner', rightLabel: 'Marriage Questions', difficulty: 1 },
      { id: 'evy_1_44', leftLabel: 'Quiet Relatives', rightLabel: 'Wedding Season Relatives', difficulty: 1 },
      { id: 'evy_1_45', leftLabel: 'Guest Coming', rightLabel: 'Emergency Cleaning', difficulty: 1 },
      { id: 'evy_1_46', leftLabel: 'Clean Kitchen', rightLabel: 'Cooking Disaster', difficulty: 1 },
      { id: 'evy_1_47', leftLabel: 'Simple Recipe', rightLabel: 'MasterChef Accident', difficulty: 1 },
      { id: 'evy_1_48', leftLabel: 'Making Tea', rightLabel: 'Making Tea for Everyone', difficulty: 1 },
      { id: 'evy_1_49', leftLabel: 'One Biscuit', rightLabel: 'Empty Biscuit Packet', difficulty: 1 },
      { id: 'evy_1_50', leftLabel: 'Small Hunger', rightLabel: 'Emergency Food Hunt', difficulty: 1 },
      { id: 'evy_1_51', leftLabel: 'Fresh Clothes', rightLabel: 'Favourite Shirt Missing', difficulty: 1 },
      { id: 'evy_1_52', leftLabel: 'Laundry Done', rightLabel: 'Laundry Chair Full', difficulty: 1 },
      { id: 'evy_1_53', leftLabel: 'Folded Clothes', rightLabel: 'Clothes Mountain', difficulty: 1 },
      { id: 'evy_1_54', leftLabel: 'Organized Bag', rightLabel: 'Bag Black Hole', difficulty: 1 },
      { id: 'evy_1_55', leftLabel: 'Found the Keys', rightLabel: 'Keys Missing Again', difficulty: 1 },
      { id: 'evy_1_56', leftLabel: 'Phone in Hand', rightLabel: 'Looking for Phone', difficulty: 1 },
      { id: 'evy_1_57', leftLabel: 'Know the Password', rightLabel: 'Forgot Password', difficulty: 1 },
      { id: 'evy_1_58', leftLabel: 'Simple Login', rightLabel: 'OTP Adventure', difficulty: 1 },
      { id: 'evy_1_59', leftLabel: 'Quiet Lift Ride', rightLabel: 'Awkward Lift Ride', difficulty: 1 },
      { id: 'evy_1_60', leftLabel: 'Empty Elevator', rightLabel: 'Packed Elevator', difficulty: 1 },
      { id: 'evy_1_61', leftLabel: 'Green Signal', rightLabel: 'Why Is Nobody Moving?', difficulty: 1 },
      { id: 'evy_1_62', leftLabel: 'Easy Auto Ride', rightLabel: 'Driver Negotiation', difficulty: 1 },
      { id: 'evy_1_63', leftLabel: 'Short Cab Ride', rightLabel: 'Traffic Marathon', difficulty: 1 },
      { id: 'evy_1_64', leftLabel: 'On Time', rightLabel: 'Running Late', difficulty: 1 },
      { id: 'evy_1_65', leftLabel: 'Leaving Early', rightLabel: 'Still Somehow Late', difficulty: 1 },
      { id: 'evy_1_66', leftLabel: 'Perfect Outfit', rightLabel: 'Nothing to Wear', difficulty: 1 },
      { id: 'evy_1_67', leftLabel: 'Ready in Ten Minutes', rightLabel: 'Still Getting Ready', difficulty: 1 },
      { id: 'evy_1_68', leftLabel: 'Good Hair Day', rightLabel: 'Hat Day', difficulty: 1 },
      { id: 'evy_1_69', leftLabel: 'Perfect Selfie', rightLabel: '200 Failed Selfies', difficulty: 1 },
      { id: 'evy_1_70', leftLabel: 'One Photo', rightLabel: 'Photoshoot', difficulty: 1 },
      { id: 'evy_1_71', leftLabel: 'Casual Outfit', rightLabel: 'Accidentally Overdressed', difficulty: 1 },
      { id: 'evy_1_72', leftLabel: 'Simple Hair', rightLabel: 'Hair Has Its Own Plans', difficulty: 1 },
      { id: 'evy_1_73', leftLabel: 'Quick Makeup', rightLabel: 'Full Transformation', difficulty: 1 },
      { id: 'evy_1_74', leftLabel: 'Just Five Minutes', rightLabel: 'Lost Entire Afternoon', difficulty: 1 },
      { id: 'evy_1_75', leftLabel: 'Small Break', rightLabel: 'Productivity Gone', difficulty: 1 },
      { id: 'evy_1_76', leftLabel: 'One Task', rightLabel: 'Twenty Random Tasks', difficulty: 1 },
      { id: 'evy_1_77', leftLabel: 'Making a To-Do List', rightLabel: 'Avoiding the To-Do List', difficulty: 1 },
      { id: 'evy_1_78', leftLabel: 'Motivated Monday', rightLabel: 'Surviving Monday', difficulty: 1 },
      { id: 'evy_1_79', leftLabel: 'Fresh Week', rightLabel: 'Already Waiting for Friday', difficulty: 1 },
      { id: 'evy_1_80', leftLabel: 'Relaxed Sunday', rightLabel: 'Sunday Anxiety', difficulty: 1 },
      { id: 'evy_1_81', leftLabel: 'Clean Desk', rightLabel: 'Snack Battlefield', difficulty: 1 },
      { id: 'evy_1_82', leftLabel: 'Productive Hour', rightLabel: 'Distracted Hour', difficulty: 1 },
      { id: 'evy_1_83', leftLabel: 'Focused', rightLabel: 'Checking Instagram', difficulty: 1 },
      { id: 'evy_1_84', leftLabel: 'Reading a Book', rightLabel: 'Watching Reels', difficulty: 1 },
      { id: 'evy_1_85', leftLabel: 'Learning Something', rightLabel: 'Googling Random Things', difficulty: 1 },
      { id: 'evy_1_86', leftLabel: 'Saving a Recipe', rightLabel: 'Ordering the Recipe', difficulty: 1 },
      { id: 'evy_1_87', leftLabel: 'Cooking at Home', rightLabel: 'Food Delivery', difficulty: 1 },
      { id: 'evy_1_88', leftLabel: 'One Coffee', rightLabel: 'Coffee Addiction', difficulty: 1 },
      { id: 'evy_1_89', leftLabel: 'Normal Chai', rightLabel: 'Emotional Support Chai', difficulty: 1 },
      { id: 'evy_1_90', leftLabel: 'Feeling Productive', rightLabel: 'Rewarding Yourself for Nothing', difficulty: 1 },
      { id: 'evy_1_91', leftLabel: 'Small Problem', rightLabel: 'Overthinking Everything', difficulty: 1 },
      { id: 'evy_1_92', leftLabel: 'One Thought', rightLabel: 'Full Imaginary Conversation', difficulty: 1 },
      { id: 'evy_1_93', leftLabel: 'Calm Mind', rightLabel: 'Brain at 2 AM', difficulty: 1 },
      { id: 'evy_1_94', leftLabel: 'Normal Day', rightLabel: 'Random Plot Twist', difficulty: 1 },
      { id: 'evy_1_95', leftLabel: 'Simple Plan', rightLabel: 'Everything Goes Wrong', difficulty: 1 },
      { id: 'evy_1_96', leftLabel: 'Going Out', rightLabel: 'Staying Home', difficulty: 1 },
      { id: 'evy_1_97', leftLabel: 'Social Battery Full', rightLabel: 'Do Not Talk to Me', difficulty: 1 },
      { id: 'evy_1_98', leftLabel: 'Meeting Friends', rightLabel: 'Canceling Plans', difficulty: 1 },
      { id: 'evy_1_99', leftLabel: 'Fun Evening', rightLabel: 'Pajamas at 8 PM', difficulty: 1 },
      { id: 'evy_1_100', leftLabel: 'Normal Day', rightLabel: 'Absolute Chaos', difficulty: 1 },
    ],

    // ============================================================
    // LEVEL 2 — EMBARRASSING & FUNNY
    // ============================================================
    2: [
      { id: 'evy_2_1', leftLabel: 'Tiny Mistake', rightLabel: 'Everyone Saw It', difficulty: 2 },
      { id: 'evy_2_2', leftLabel: 'Wrong Chat', rightLabel: 'Very Wrong Chat', difficulty: 2 },
      { id: 'evy_2_3', leftLabel: 'Typing...', rightLabel: 'Deleted Message Panic', difficulty: 2 },
      { id: 'evy_2_4', leftLabel: 'Seen', rightLabel: 'Seen Two Days Ago', difficulty: 2 },
      { id: 'evy_2_5', leftLabel: 'Forgot to Reply', rightLabel: 'Pretending You Forgot', difficulty: 2 },
      { id: 'evy_2_6', leftLabel: 'Accidental Like', rightLabel: 'Liked a 2019 Photo', difficulty: 2 },
      { id: 'evy_2_7', leftLabel: 'Stalking Profile', rightLabel: 'Accidental Follow', difficulty: 2 },
      { id: 'evy_2_8', leftLabel: 'Instagram Browsing', rightLabel: 'Instagram Investigation', difficulty: 2 },
      { id: 'evy_2_9', leftLabel: 'One Story View', rightLabel: 'Watching Every Story', difficulty: 2 },
      { id: 'evy_2_10', leftLabel: 'Casual Story', rightLabel: 'Clearly Posted for Someone', difficulty: 2 },
      { id: 'evy_2_11', leftLabel: 'Normal Selfie', rightLabel: 'Checking Who Viewed It', difficulty: 2 },
      { id: 'evy_2_12', leftLabel: 'Cute Photo', rightLabel: 'Deleted Immediately', difficulty: 2 },
      { id: 'evy_2_13', leftLabel: 'Simple Text', rightLabel: 'Rewriting It Ten Times', difficulty: 2 },
      { id: 'evy_2_14', leftLabel: 'Hey', rightLabel: 'Typed a Whole Paragraph', difficulty: 2 },
      { id: 'evy_2_15', leftLabel: 'Quick Reply', rightLabel: 'Overthinking the Emoji', difficulty: 2 },
      { id: 'evy_2_16', leftLabel: 'Laughing Normally', rightLabel: 'Fake Laughing at a Bad Joke', difficulty: 2 },
      { id: 'evy_2_17', leftLabel: 'Small Awkwardness', rightLabel: 'Complete Social Shutdown', difficulty: 2 },
      { id: 'evy_2_18', leftLabel: 'Forgot a Name', rightLabel: 'Pretending to Remember', difficulty: 2 },
      {
        id: 'evy_2_19', leftLabel: 'Recognized Someone', rightLabel: "They Don't Recognize You", difficulty: 2
      },
      {
        id: 'evy_2_20', leftLabel: 'Waving Back', rightLabel: "They Weren't Waving at You", difficulty: 2
      },
      { id: 'evy_2_21', leftLabel: 'Eye Contact', rightLabel: 'Instantly Looking Away', difficulty: 2 },
      { id: 'evy_2_22', leftLabel: 'Awkward Smile', rightLabel: 'Awkward Double Smile', difficulty: 2 },
      { id: 'evy_2_23', leftLabel: 'Saying Hello', rightLabel: 'Saying Hello Twice', difficulty: 2 },
      { id: 'evy_2_24', leftLabel: 'Calling Someone', rightLabel: 'Calling the Wrong Person', difficulty: 2 },
      { id: 'evy_2_25', leftLabel: 'Pocket Dial', rightLabel: 'Pocket Video Call', difficulty: 2 },
      { id: 'evy_2_26', leftLabel: 'Muted Phone', rightLabel: 'Phone Rings at the Worst Time', difficulty: 2 },
      { id: 'evy_2_27', leftLabel: 'Quiet Room', rightLabel: 'Stomach Growling Loudly', difficulty: 2 },
      { id: 'evy_2_28', leftLabel: 'Silent Room', rightLabel: 'Chair Makes a Noise', difficulty: 2 },
      { id: 'evy_2_29', leftLabel: 'Walking Normally', rightLabel: 'Almost Tripping', difficulty: 2 },
      {
        id: 'evy_2_30', leftLabel: 'Graceful Exit', rightLabel: "Door Won't Open", difficulty: 2
      },
      { id: 'evy_2_31', leftLabel: 'Confident Entrance', rightLabel: 'Walked into Wrong Room', difficulty: 2 },
      { id: 'evy_2_32', leftLabel: 'Knowing Where You Are', rightLabel: 'Completely Lost', difficulty: 2 },
      { id: 'evy_2_33', leftLabel: 'Small Spill', rightLabel: 'Entire Drink Everywhere', difficulty: 2 },
      { id: 'evy_2_34', leftLabel: 'Clean Outfit', rightLabel: 'Food Stain Immediately', difficulty: 2 },
      { id: 'evy_2_35', leftLabel: 'Perfect Hair', rightLabel: 'Wind Ruined Everything', difficulty: 2 },
      { id: 'evy_2_36', leftLabel: 'Good Outfit', rightLabel: 'Someone Wearing the Same Outfit', difficulty: 2 },
      { id: 'evy_2_37', leftLabel: 'Subtle Entrance', rightLabel: 'Everyone Notices You', difficulty: 2 },
      { id: 'evy_2_38', leftLabel: 'Quiet Sneeze', rightLabel: 'Earthquake Sneeze', difficulty: 2 },
      { id: 'evy_2_39', leftLabel: 'Normal Cough', rightLabel: 'Everyone Looks at You', difficulty: 2 },
      { id: 'evy_2_40', leftLabel: 'Small Yawn', rightLabel: 'Accidental Loud Yawn', difficulty: 2 },
      { id: 'evy_2_41', leftLabel: 'Family Visit', rightLabel: 'Family Background Check', difficulty: 2 },
      { id: 'evy_2_42', leftLabel: 'Normal Relative', rightLabel: 'Career Advisor Relative', difficulty: 2 },
      { id: 'evy_2_43', leftLabel: 'Simple Question', rightLabel: 'When Are You Getting Married?', difficulty: 2 },
      { id: 'evy_2_44', leftLabel: 'Family Dinner', rightLabel: 'Marriage Interrogation', difficulty: 2 },
      { id: 'evy_2_45', leftLabel: 'Visiting Relatives', rightLabel: 'Answering Personal Questions', difficulty: 2 },
      { id: 'evy_2_46', leftLabel: 'Private Life', rightLabel: 'Family Group Announcement', difficulty: 2 },
      { id: 'evy_2_47', leftLabel: 'Personal News', rightLabel: 'Neighbourhood News', difficulty: 2 },
      { id: 'evy_2_48', leftLabel: 'One Auntie', rightLabel: 'Entire Gossip Network', difficulty: 2 },
      { id: 'evy_2_49', leftLabel: 'Family WhatsApp', rightLabel: '500 Good Morning Messages', difficulty: 2 },
      { id: 'evy_2_50', leftLabel: 'One Family Photo', rightLabel: 'Family Photoshoot', difficulty: 2 },
      { id: 'evy_2_51', leftLabel: 'Casual Chai', rightLabel: 'Chai Became a Two-Hour Meeting', difficulty: 2 },
      { id: 'evy_2_52', leftLabel: 'Quick Snack', rightLabel: 'Full Street Food Tour', difficulty: 2 },
      { id: 'evy_2_53', leftLabel: 'One Samosa', rightLabel: 'Samosa + Chai + Dessert', difficulty: 2 },
      { id: 'evy_2_54', leftLabel: 'Just a Bite', rightLabel: 'Ate Half Their Food', difficulty: 2 },
      { id: 'evy_2_55', leftLabel: 'Sharing Fries', rightLabel: 'Protecting Your Fries', difficulty: 2 },
      {
        id: 'evy_2_56', leftLabel: 'Not Hungry', rightLabel: "Eating Everyone's Food", difficulty: 2
      },
      { id: 'evy_2_57', leftLabel: 'Healthy Dinner', rightLabel: 'Midnight Food Delivery', difficulty: 2 },
      { id: 'evy_2_58', leftLabel: 'Small Craving', rightLabel: 'Food Emergency', difficulty: 2 },
      { id: 'evy_2_59', leftLabel: 'Checking Menu', rightLabel: 'Ordering Everything', difficulty: 2 },
      { id: 'evy_2_60', leftLabel: 'Saving Money', rightLabel: 'Food App Offers', difficulty: 2 },
      { id: 'evy_2_61', leftLabel: 'Simple Shopping', rightLabel: 'Impulse Shopping', difficulty: 2 },
      { id: 'evy_2_62', leftLabel: 'Need One Thing', rightLabel: 'Bought Seven Things', difficulty: 2 },
      {
        id: 'evy_2_63', leftLabel: 'Discount', rightLabel: "Bought Something You Don't Need", difficulty: 2
      },
      { id: 'evy_2_64', leftLabel: 'Sale Browsing', rightLabel: 'Credit Card Regret', difficulty: 2 },
      { id: 'evy_2_65', leftLabel: '₹500 Budget', rightLabel: '₹5,000 Checkout', difficulty: 2 },
      { id: 'evy_2_66', leftLabel: 'Saving for the Month', rightLabel: 'Salary Disappeared', difficulty: 2 },
      { id: 'evy_2_67', leftLabel: 'Checking Expense', rightLabel: 'Ignoring Expense', difficulty: 2 },
      { id: 'evy_2_68', leftLabel: 'Budget Plan', rightLabel: 'Budget Gone by Day Five', difficulty: 2 },
      { id: 'evy_2_69', leftLabel: 'Free Delivery', rightLabel: 'Added Items for Free Delivery', difficulty: 2 },
      { id: 'evy_2_70', leftLabel: 'Cashback', rightLabel: 'Spending More for Cashback', difficulty: 2 },
      { id: 'evy_2_71', leftLabel: 'Going Out Briefly', rightLabel: 'Returning Home at Midnight', difficulty: 2 },
      { id: 'evy_2_72', leftLabel: 'One Drink', rightLabel: 'Entire Night Out', difficulty: 2 },
      { id: 'evy_2_73', leftLabel: 'Quick Coffee', rightLabel: 'Deep Life Conversation', difficulty: 2 },
      { id: 'evy_2_74', leftLabel: 'Coffee Catch-Up', rightLabel: 'Three-Hour Catch-Up', difficulty: 2 },
      { id: 'evy_2_75', leftLabel: 'Casual Hangout', rightLabel: 'Unexpected Adventure', difficulty: 2 },
      { id: 'evy_2_76', leftLabel: 'Simple Plan', rightLabel: 'Group Chat Planning Disaster', difficulty: 2 },
      { id: 'evy_2_77', leftLabel: 'Everyone Coming', rightLabel: 'Everyone Cancels', difficulty: 2 },
      { id: 'evy_2_78', leftLabel: 'One Friend Late', rightLabel: 'Everyone Waiting', difficulty: 2 },
      { id: 'evy_2_79', leftLabel: 'On Time', rightLabel: 'Waiting 45 Minutes', difficulty: 2 },
      { id: 'evy_2_80', leftLabel: 'Short Drive', rightLabel: 'Lost With Google Maps', difficulty: 2 },
      { id: 'evy_2_81', leftLabel: 'Simple Date', rightLabel: 'Date Becomes Story Material', difficulty: 2 },
      { id: 'evy_2_82', leftLabel: 'Cute Conversation', rightLabel: 'Accidental Oversharing', difficulty: 2 },
      {
        id: 'evy_2_83', leftLabel: 'Casual Compliment', rightLabel: "Now You're Blushing", difficulty: 2
      },
      { id: 'evy_2_84', leftLabel: 'Friendly Hug', rightLabel: 'Awkward Goodbye Hug', difficulty: 2 },
      { id: 'evy_2_85', leftLabel: 'Normal Handshake', rightLabel: 'Awkward Handshake', difficulty: 2 },
      { id: 'evy_2_86', leftLabel: 'Friendly Smile', rightLabel: 'Was That Flirting?', difficulty: 2 },
      { id: 'evy_2_87', leftLabel: 'Normal Eye Contact', rightLabel: 'Why Are We Still Looking?', difficulty: 2 },
      { id: 'evy_2_88', leftLabel: 'Casual Compliment', rightLabel: 'Thinking About It All Day', difficulty: 2 },
      { id: 'evy_2_89', leftLabel: 'Nice Outfit', rightLabel: 'Clearly Dressed to Impress', difficulty: 2 },
      { id: 'evy_2_90', leftLabel: 'Normal Conversation', rightLabel: 'Butterflies Everywhere', difficulty: 2 },
      { id: 'evy_2_91', leftLabel: 'Normal Crush', rightLabel: 'Checking Their Last Seen', difficulty: 2 },
      { id: 'evy_2_92', leftLabel: 'One Text', rightLabel: 'Waiting for Their Reply', difficulty: 2 },
      { id: 'evy_2_93', leftLabel: 'Quick Reply', rightLabel: 'Overthinking Their Reply', difficulty: 2 },
      { id: 'evy_2_94', leftLabel: 'Goodnight', rightLabel: 'Still Chatting at 2 AM', difficulty: 2 },
      {
        id: 'evy_2_95', leftLabel: 'Just Friends', rightLabel: "Everyone Thinks You're Dating", difficulty: 2
      },
      { id: 'evy_2_96', leftLabel: 'Private Joke', rightLabel: 'Everyone Wants Context', difficulty: 2 },
      { id: 'evy_2_97', leftLabel: 'Secret Crush', rightLabel: 'Friends Already Know', difficulty: 2 },
      { id: 'evy_2_98', leftLabel: 'Subtle Flirting', rightLabel: 'Friends Calling You Out', difficulty: 2 },
      { id: 'evy_2_99', leftLabel: 'Cute Moment', rightLabel: 'Replay It in Your Head', difficulty: 2 },
      { id: 'evy_2_100', leftLabel: 'Normal Day', rightLabel: 'Embarrassing Story for Years', difficulty: 2 },
    ],

    // ============================================================
    // LEVEL 3 — SOCIAL LIFE, DATING & LIFE DRAMA
    // ============================================================
    3: [
      { id: 'evy_3_1', leftLabel: 'Friendly Vibe', rightLabel: 'Definitely Flirting', difficulty: 3 },
      { id: 'evy_3_2', leftLabel: 'Small Crush', rightLabel: 'Full-Blown Obsession', difficulty: 3 },
      { id: 'evy_3_3', leftLabel: 'Thinking About Them', rightLabel: 'Checking Their Profile', difficulty: 3 },
      { id: 'evy_3_4', leftLabel: 'One Story View', rightLabel: 'Waiting for Their Story', difficulty: 3 },
      { id: 'evy_3_5', leftLabel: 'Casual Like', rightLabel: 'Strategic Like', difficulty: 3 },
      { id: 'evy_3_6', leftLabel: 'Simple DM', rightLabel: 'Flirty DM', difficulty: 3 },
      { id: 'evy_3_7', leftLabel: 'Normal Text', rightLabel: 'Text You Keep Rewriting', difficulty: 3 },
      { id: 'evy_3_8', leftLabel: 'Quick Reply', rightLabel: 'Waiting for the Reply', difficulty: 3 },
      { id: 'evy_3_9', leftLabel: 'Seen', rightLabel: 'Seen and Overthinking', difficulty: 3 },
      { id: 'evy_3_10', leftLabel: 'Goodnight', rightLabel: 'Goodnight ❤️', difficulty: 3 },
      { id: 'evy_3_11', leftLabel: 'Friendship', rightLabel: 'Situationship', difficulty: 3 },
      { id: 'evy_3_12', leftLabel: 'Situationship', rightLabel: 'Almost Relationship', difficulty: 3 },
      { id: 'evy_3_13', leftLabel: 'Casual Date', rightLabel: 'Definitely a Date', difficulty: 3 },
      { id: 'evy_3_14', leftLabel: 'Coffee', rightLabel: 'Coffee With Chemistry', difficulty: 3 },
      { id: 'evy_3_15', leftLabel: 'Friendly Hug', rightLabel: 'Hug You Remember', difficulty: 3 },
      { id: 'evy_3_16', leftLabel: 'Long Conversation', rightLabel: 'Forgot the Time', difficulty: 3 },
      { id: 'evy_3_17', leftLabel: 'Eye Contact', rightLabel: "Can't Look Away", difficulty: 3 },
      { id: 'evy_3_18', leftLabel: 'Cute Smile', rightLabel: 'Dangerous Smile', difficulty: 3 },
      { id: 'evy_3_19', leftLabel: 'Friendly Compliment', rightLabel: 'Compliment With Intent', difficulty: 3 },
      { id: 'evy_3_20', leftLabel: 'Nice Outfit', rightLabel: 'Trying to Impress Someone', difficulty: 3 },
      { id: 'evy_3_21', leftLabel: 'First Date Nerves', rightLabel: 'First Date Butterflies', difficulty: 3 },
      { id: 'evy_3_22', leftLabel: 'Cute Date', rightLabel: 'Unexpected Chemistry', difficulty: 3 },
      { id: 'evy_3_23', leftLabel: 'Good Conversation', rightLabel: 'Instant Connection', difficulty: 3 },
      { id: 'evy_3_24', leftLabel: 'First Kiss Nerves', rightLabel: 'First Kiss Confidence', difficulty: 3 },
      { id: 'evy_3_25', leftLabel: 'Cheek Kiss', rightLabel: 'Kiss You Were Waiting For', difficulty: 3 },
      {
        id: 'evy_3_26', leftLabel: 'Quick Hug', rightLabel: "Don't Want to Let Go", difficulty: 3
      },
      { id: 'evy_3_27', leftLabel: 'Holding Hands', rightLabel: "Never Want to Let Go", difficulty: 3 },
      { id: 'evy_3_28', leftLabel: 'Sitting Together', rightLabel: 'Sitting Very Close', difficulty: 3 },
      { id: 'evy_3_29', leftLabel: 'Personal Space', rightLabel: 'No Personal Space', difficulty: 3 },
      {
        id: 'evy_3_30', leftLabel: 'Cute Cuddle', rightLabel: "Can't Stop Cuddling", difficulty: 3
      },
      { id: 'evy_3_31', leftLabel: 'Movie Night', rightLabel: 'Forgot the Movie', difficulty: 3 },
      { id: 'evy_3_32', leftLabel: 'Netflix Night', rightLabel: 'Talking the Entire Night', difficulty: 3 },
      { id: 'evy_3_33', leftLabel: 'Sleepover', rightLabel: 'Sleepover With Chemistry', difficulty: 3 },
      { id: 'evy_3_34', leftLabel: 'Goodnight Hug', rightLabel: 'Goodnight Kiss', difficulty: 3 },
      { id: 'evy_3_35', leftLabel: 'One More Minute', rightLabel: 'One More Hour Together', difficulty: 3 },
      { id: 'evy_3_36', leftLabel: 'Goodbye', rightLabel: 'Not Ready to Say Goodbye', difficulty: 3 },
      { id: 'evy_3_37', leftLabel: 'Cute Moment', rightLabel: 'Romantic Moment', difficulty: 3 },
      { id: 'evy_3_38', leftLabel: 'Romantic Moment', rightLabel: 'Very Steamy Moment', difficulty: 3 },
      { id: 'evy_3_39', leftLabel: 'Flirty Smile', rightLabel: 'Flirty Stare', difficulty: 3 },
      { id: 'evy_3_40', leftLabel: 'Small Spark', rightLabel: 'Serious Chemistry', difficulty: 3 },
      { id: 'evy_3_41', leftLabel: 'Family Advice', rightLabel: 'Family Interference', difficulty: 3 },
      { id: 'evy_3_42', leftLabel: 'Casual Family Dinner', rightLabel: 'Family Courtroom', difficulty: 3 },
      { id: 'evy_3_43', leftLabel: 'When Will You Marry?', rightLabel: 'We Found Someone for You', difficulty: 3 },
      { id: 'evy_3_44', leftLabel: 'One Relative', rightLabel: 'Entire Family Investigating', difficulty: 3 },
      { id: 'evy_3_45', leftLabel: 'Private Relationship', rightLabel: 'Family Group Announcement', difficulty: 3 },
      { id: 'evy_3_46', leftLabel: 'Dating Secret', rightLabel: 'Parents Found Out', difficulty: 3 },
      { id: 'evy_3_47', leftLabel: 'Small Family Argument', rightLabel: 'Three-Day Cold War', difficulty: 3 },
      { id: 'evy_3_48', leftLabel: 'Normal Discussion', rightLabel: 'Full Family Debate', difficulty: 3 },
      { id: 'evy_3_49', leftLabel: 'One Wedding', rightLabel: 'Wedding Season Marathon', difficulty: 3 },
      { id: 'evy_3_50', leftLabel: 'Attending Wedding', rightLabel: 'Answering Personal Questions', difficulty: 3 },
      { id: 'evy_3_51', leftLabel: 'Reasonable Spending', rightLabel: 'Why Did I Buy That?', difficulty: 3 },
      { id: 'evy_3_52', leftLabel: 'Saving Salary', rightLabel: 'Salary Vanished', difficulty: 3 },
      { id: 'evy_3_53', leftLabel: 'Small EMI', rightLabel: 'EMI Collection', difficulty: 3 },
      { id: 'evy_3_54', leftLabel: 'One Subscription', rightLabel: 'Subscription Graveyard', difficulty: 3 },
      { id: 'evy_3_55', leftLabel: 'Free Trial', rightLabel: 'Forgot to Cancel', difficulty: 3 },
      { id: 'evy_3_56', leftLabel: 'Budget Month', rightLabel: 'Food Delivery Month', difficulty: 3 },
      { id: 'evy_3_57', leftLabel: 'Saving for Vacation', rightLabel: 'Shopping for Vacation', difficulty: 3 },
      { id: 'evy_3_58', leftLabel: 'Online Sale', rightLabel: 'Financial Mistake', difficulty: 3 },
      { id: 'evy_3_59', leftLabel: 'One Coffee', rightLabel: 'Daily Café Habit', difficulty: 3 },
      { id: 'evy_3_60', leftLabel: 'Chai Break', rightLabel: 'Chai Therapy Session', difficulty: 3 },
      { id: 'evy_3_61', leftLabel: 'Healthy Week', rightLabel: 'Weekend Food Festival', difficulty: 3 },
      { id: 'evy_3_62', leftLabel: 'Gym Membership', rightLabel: 'Gym Donation', difficulty: 3 },
      { id: 'evy_3_63', leftLabel: 'Morning Walk', rightLabel: 'Morning Snooze', difficulty: 3 },
      { id: 'evy_3_64', leftLabel: 'Meal Prep', rightLabel: 'Ordering Something Else', difficulty: 3 },
      { id: 'evy_3_65', leftLabel: 'Sleep Schedule', rightLabel: 'Sleep Schedule? Never Heard of Her', difficulty: 3 },
      { id: 'evy_3_66', leftLabel: 'Productive Evening', rightLabel: 'Phone Distraction', difficulty: 3 },
      { id: 'evy_3_67', leftLabel: 'One Reel', rightLabel: 'Existential Crisis at 2 AM', difficulty: 3 },
      { id: 'evy_3_68', leftLabel: 'Normal Overthinking', rightLabel: 'Creating Entire Scenarios', difficulty: 3 },
      { id: 'evy_3_69', leftLabel: 'Small Problem', rightLabel: 'Imaginary Argument', difficulty: 3 },
      { id: 'evy_3_70', leftLabel: 'One Awkward Moment', rightLabel: 'Thinking About It for Five Years', difficulty: 3 },
      { id: 'evy_3_71', leftLabel: 'Friend Group', rightLabel: 'Friend Group Politics', difficulty: 3 },
      { id: 'evy_3_72', leftLabel: 'Small Gossip', rightLabel: 'Breaking News', difficulty: 3 },
      { id: 'evy_3_73', leftLabel: 'Private Story', rightLabel: 'Everyone Wants to Know', difficulty: 3 },
      { id: 'evy_3_74', leftLabel: 'Secret', rightLabel: 'Worst Person to Tell', difficulty: 3 },
      { id: 'evy_3_75', leftLabel: 'Best Friend', rightLabel: 'Personal FBI', difficulty: 3 },
      { id: 'evy_3_76', leftLabel: 'Friend Advice', rightLabel: 'Friend Making It Worse', difficulty: 3 },
      { id: 'evy_3_77', leftLabel: 'Small Fight', rightLabel: 'Group Chat Investigation', difficulty: 3 },
      { id: 'evy_3_78', leftLabel: 'One Screenshot', rightLabel: 'Entire Chat Leaked', difficulty: 3 },
      { id: 'evy_3_79', leftLabel: 'Private Joke', rightLabel: 'Public Embarrassment', difficulty: 3 },
      { id: 'evy_3_80', leftLabel: 'Normal Friend', rightLabel: 'Friend Who Knows Everything', difficulty: 3 },
      { id: 'evy_3_81', leftLabel: 'Casual Party', rightLabel: 'Main Character Moment', difficulty: 3 },
      { id: 'evy_3_82', leftLabel: 'One Drink', rightLabel: 'Dance Floor Confidence', difficulty: 3 },
      { id: 'evy_3_83', leftLabel: 'Quiet Party', rightLabel: 'House Party Chaos', difficulty: 3 },
      { id: 'evy_3_84', leftLabel: 'Going Home Early', rightLabel: 'Sunrise Return', difficulty: 3 },
      { id: 'evy_3_85', leftLabel: 'Casual Outfit', rightLabel: 'Dressed for Attention', difficulty: 3 },
      { id: 'evy_3_86', leftLabel: 'Small Flirt', rightLabel: 'Mutual Attraction', difficulty: 3 },
      { id: 'evy_3_87', leftLabel: 'Cute Chemistry', rightLabel: 'Everyone Notices', difficulty: 3 },
      { id: 'evy_3_88', leftLabel: 'Private Smile', rightLabel: 'Obvious Crush', difficulty: 3 },
      { id: 'evy_3_89', leftLabel: 'Normal Compliment', rightLabel: 'That Compliment Changed the Mood', difficulty: 3 },
      { id: 'evy_3_90', leftLabel: 'Flirting', rightLabel: 'Actually Catching Feelings', difficulty: 3 },
      { id: 'evy_3_91', leftLabel: 'One Kiss', rightLabel: 'Thinking About It All Week', difficulty: 3 },
      {
        id: 'evy_3_92', leftLabel: 'Kiss Goodnight', rightLabel: "Don't Want to Say Goodnight", difficulty: 3
      },
      { id: 'evy_3_93', leftLabel: 'Romantic Tension', rightLabel: 'Impossible to Ignore', difficulty: 3 },
      { id: 'evy_3_94', leftLabel: 'Cute Cuddle', rightLabel: 'Cuddle Becomes the Plan', difficulty: 3 },
      { id: 'evy_3_95', leftLabel: 'Movie Date', rightLabel: 'Movie Completely Forgotten', difficulty: 3 },
      { id: 'evy_3_96', leftLabel: 'Long Hug', rightLabel: 'Hug That Says Everything', difficulty: 3 },
      { id: 'evy_3_97', leftLabel: 'Late Night Chat', rightLabel: 'Morning Still Talking', difficulty: 3 },
      { id: 'evy_3_98', leftLabel: 'Good Chemistry', rightLabel: 'Dangerous Chemistry', difficulty: 3 },
      { id: 'evy_3_99', leftLabel: 'Attraction', rightLabel: 'Serious Desire', difficulty: 3 },
      { id: 'evy_3_100', leftLabel: 'Normal Week', rightLabel: 'Emotional Rollercoaster', difficulty: 3 },
    ],

    // ============================================================
    // LEVEL 4 — AWKWARD, CHAOTIC & SPICY
    // ============================================================
    4: [
      { id: 'evy_4_1', leftLabel: 'Small Crush', rightLabel: 'Cannot Act Normal Around Them', difficulty: 4 },
      { id: 'evy_4_2', leftLabel: 'Checking Their Profile', rightLabel: 'Investigating Their Entire Life', difficulty: 4 },
      { id: 'evy_4_3', leftLabel: 'Casual Text', rightLabel: 'Waiting by the Phone', difficulty: 4 },
      { id: 'evy_4_4', leftLabel: 'Late Reply', rightLabel: 'Imagining 17 Reasons', difficulty: 4 },
      { id: 'evy_4_5', leftLabel: 'One Emoji', rightLabel: 'Analyzing the Emoji', difficulty: 4 },
      { id: 'evy_4_6', leftLabel: 'Cute Message', rightLabel: 'Reading It Again Before Sleeping', difficulty: 4 },
      { id: 'evy_4_7', leftLabel: 'Goodnight Text', rightLabel: 'Goodnight Text With Heart', difficulty: 4 },
      { id: 'evy_4_8', leftLabel: 'Normal Flirting', rightLabel: 'Clearly Trying to Seduce', difficulty: 4 },
      { id: 'evy_4_9', leftLabel: 'Eye Contact', rightLabel: 'Eye Contact That Changes Everything', difficulty: 4 },
      { id: 'evy_4_10', leftLabel: 'Cute Smile', rightLabel: 'That Smile Is Dangerous', difficulty: 4 },
      { id: 'evy_4_11', leftLabel: 'Casual Touch', rightLabel: 'Suddenly Very Aware of Them', difficulty: 4 },
      { id: 'evy_4_12', leftLabel: 'Accidental Touch', rightLabel: 'Definitely Not Thinking About It', difficulty: 4 },
      { id: 'evy_4_13', leftLabel: 'Sitting Close', rightLabel: 'Way Too Close', difficulty: 4 },
      { id: 'evy_4_14', leftLabel: 'Personal Space', rightLabel: 'What Personal Space?', difficulty: 4 },
      { id: 'evy_4_15', leftLabel: 'Friendly Hug', rightLabel: 'Hug Lasting a Little Too Long', difficulty: 4 },
      { id: 'evy_4_16', leftLabel: 'Goodbye Hug', rightLabel: 'Neither Person Wants to Leave', difficulty: 4 },
      { id: 'evy_4_17', leftLabel: 'Cheek Kiss', rightLabel: 'Unexpected Kiss', difficulty: 4 },
      { id: 'evy_4_18', leftLabel: 'First Kiss', rightLabel: 'Kiss You Keep Thinking About', difficulty: 4 },
      { id: 'evy_4_19', leftLabel: 'Quick Kiss', rightLabel: 'Kiss That Changes the Mood', difficulty: 4 },
      { id: 'evy_4_20', leftLabel: 'Goodnight Kiss', rightLabel: 'One More Kiss', difficulty: 4 },
      {
        id: 'evy_4_21', leftLabel: 'One Kiss', rightLabel: "Can't Stop Smiling", difficulty: 4
      },
      { id: 'evy_4_22', leftLabel: 'Cute Kiss', rightLabel: 'Very Passionate Kiss', difficulty: 4 },
      { id: 'evy_4_23', leftLabel: 'Romantic Moment', rightLabel: 'Things Are Getting Steamy', difficulty: 4 },
      { id: 'evy_4_24', leftLabel: 'Flirty Energy', rightLabel: 'Serious Sexual Tension', difficulty: 4 },
      { id: 'evy_4_25', leftLabel: 'Romantic Tension', rightLabel: 'Impossible to Ignore', difficulty: 4 },
      { id: 'evy_4_26', leftLabel: 'Cute Cuddle', rightLabel: 'Very Intimate Cuddle', difficulty: 4 },
      { id: 'evy_4_27', leftLabel: 'Cuddling', rightLabel: 'Neither Wants to Move', difficulty: 4 },
      { id: 'evy_4_28', leftLabel: 'Movie Night', rightLabel: 'Movie Completely Forgotten', difficulty: 4 },
      { id: 'evy_4_29', leftLabel: 'Netflix Date', rightLabel: 'Netflix Is Just Background Noise', difficulty: 4 },
      { id: 'evy_4_30', leftLabel: 'Sleepover', rightLabel: 'Sleepover With Serious Chemistry', difficulty: 4 },
      { id: 'evy_4_31', leftLabel: 'Goodnight', rightLabel: 'Why Are We Still Awake?', difficulty: 4 },
      { id: 'evy_4_32', leftLabel: 'Midnight Chat', rightLabel: 'Sunrise Conversation', difficulty: 4 },
      { id: 'evy_4_33', leftLabel: 'Late Night Call', rightLabel: 'Very Personal Conversation', difficulty: 4 },
      { id: 'evy_4_34', leftLabel: 'Casual Date', rightLabel: 'Date With Obvious Chemistry', difficulty: 4 },
      { id: 'evy_4_35', leftLabel: 'Coffee Date', rightLabel: 'Coffee Date That Becomes Dinner', difficulty: 4 },
      { id: 'evy_4_36', leftLabel: 'Dinner Date', rightLabel: 'Why Is It Suddenly Midnight?', difficulty: 4 },
      { id: 'evy_4_37', leftLabel: 'Goodbye at 10 PM', rightLabel: 'Still Together at 2 AM', difficulty: 4 },
      { id: 'evy_4_38', leftLabel: 'One More Drink', rightLabel: 'One More Place', difficulty: 4 },
      { id: 'evy_4_39', leftLabel: 'Going Home', rightLabel: 'Not Ready to Go Home', difficulty: 4 },
      {
        id: 'evy_4_40', leftLabel: 'Perfect Date', rightLabel: "Date You Don't Want to End", difficulty: 4
      },
      { id: 'evy_4_41', leftLabel: 'Secret Crush', rightLabel: 'Friends Have Already Figured It Out', difficulty: 4 },
      { id: 'evy_4_42', leftLabel: 'Private Flirting', rightLabel: 'Everyone Can See It', difficulty: 4 },
      { id: 'evy_4_43', leftLabel: 'Just Friends', rightLabel: 'Absolutely Nobody Believes You', difficulty: 4 },
      {
        id: 'evy_4_44', leftLabel: 'Friendship', rightLabel: "Everyone Says You're Dating", difficulty: 4
      },
      { id: 'evy_4_45', leftLabel: 'Situationship', rightLabel: 'Relationship Without the Label', difficulty: 4 },
      { id: 'evy_4_46', leftLabel: 'Almost Dating', rightLabel: 'Already Emotionally Invested', difficulty: 4 },
      { id: 'evy_4_47', leftLabel: 'Casual Feelings', rightLabel: 'Serious Feelings', difficulty: 4 },
      { id: 'evy_4_48', leftLabel: 'Small Jealousy', rightLabel: 'Trying Not to Look Jealous', difficulty: 4 },
      { id: 'evy_4_49', leftLabel: 'Someone Else Flirting', rightLabel: 'Suddenly Very Interested', difficulty: 4 },
      { id: 'evy_4_50', leftLabel: 'Playing It Cool', rightLabel: 'Obviously Not Playing It Cool', difficulty: 4 },
      { id: 'evy_4_51', leftLabel: 'Family Visit', rightLabel: 'Marriage Proposal Investigation', difficulty: 4 },
      { id: 'evy_4_52', leftLabel: 'Relative Asking', rightLabel: 'Relative Already Has a Match', difficulty: 4 },
      { id: 'evy_4_53', leftLabel: 'Simple Wedding', rightLabel: 'Entire Family Drama', difficulty: 4 },
      { id: 'evy_4_54', leftLabel: 'Wedding Guest', rightLabel: 'Wedding Relationship Detective', difficulty: 4 },
      { id: 'evy_4_55', leftLabel: 'Family Dinner', rightLabel: 'Career + Marriage + Salary Interview', difficulty: 4 },
      { id: 'evy_4_56', leftLabel: 'Private Life', rightLabel: 'Family Knows Everything', difficulty: 4 },
      { id: 'evy_4_57', leftLabel: 'One Auntie', rightLabel: 'Full Neighborhood Intelligence', difficulty: 4 },
      { id: 'evy_4_58', leftLabel: 'Small Gossip', rightLabel: 'Breaking News Before You Know It', difficulty: 4 },
      { id: 'evy_4_59', leftLabel: 'One Secret', rightLabel: 'Family Group Disaster', difficulty: 4 },
      { id: 'evy_4_60', leftLabel: 'Normal WhatsApp', rightLabel: 'Screenshots Everywhere', difficulty: 4 },
      { id: 'evy_4_61', leftLabel: 'Small Spending', rightLabel: 'Bank Statement Horror', difficulty: 4 },
      { id: 'evy_4_62', leftLabel: 'One Purchase', rightLabel: 'Financial Character Development', difficulty: 4 },
      { id: 'evy_4_63', leftLabel: 'Online Sale', rightLabel: 'Shopping Spiral', difficulty: 4 },
      { id: 'evy_4_64', leftLabel: 'Just Browsing', rightLabel: 'Package Arriving Tomorrow', difficulty: 4 },
      { id: 'evy_4_65', leftLabel: 'Saving Money', rightLabel: 'Rewarding Yourself With Shopping', difficulty: 4 },
      { id: 'evy_4_66', leftLabel: 'Budgeting', rightLabel: 'Ignoring the Bank App', difficulty: 4 },
      { id: 'evy_4_67', leftLabel: 'Salary Day', rightLabel: 'Bills Day', difficulty: 4 },
      { id: 'evy_4_68', leftLabel: 'Rich on the 1st', rightLabel: 'Broke on the 20th', difficulty: 4 },
      { id: 'evy_4_69', leftLabel: 'Small Food Order', rightLabel: 'Food Delivery Financial Crisis', difficulty: 4 },
      { id: 'evy_4_70', leftLabel: 'One Dessert', rightLabel: 'Entire Dessert Menu', difficulty: 4 },
      { id: 'evy_4_71', leftLabel: 'Quick Party', rightLabel: 'Morning Regret', difficulty: 4 },
      { id: 'evy_4_72', leftLabel: 'Quiet Night Out', rightLabel: 'Legendary Night Out', difficulty: 4 },
      { id: 'evy_4_73', leftLabel: 'One Friend', rightLabel: 'Entire Friend Group Appears', difficulty: 4 },
      { id: 'evy_4_74', leftLabel: 'Casual Plan', rightLabel: 'Unplanned Adventure', difficulty: 4 },
      { id: 'evy_4_75', leftLabel: 'Going Home Early', rightLabel: 'Sunrise Return', difficulty: 4 },
      { id: 'evy_4_76', leftLabel: 'One Photo', rightLabel: 'Next Morning Photo Evidence', difficulty: 4 },
      { id: 'evy_4_77', leftLabel: 'Private Moment', rightLabel: 'Friend Recorded Everything', difficulty: 4 },
      { id: 'evy_4_78', leftLabel: 'Funny Story', rightLabel: 'Story You Can Never Tell Family', difficulty: 4 },
      { id: 'evy_4_79', leftLabel: 'Mild Embarrassment', rightLabel: 'New Personality After That', difficulty: 4 },
      { id: 'evy_4_80', leftLabel: 'Awkward Moment', rightLabel: 'Permanent Core Memory', difficulty: 4 },
      { id: 'evy_4_81', leftLabel: 'Normal Day', rightLabel: 'Unexpected Plot Twist', difficulty: 4 },
      { id: 'evy_4_82', leftLabel: 'Simple Plan', rightLabel: 'Everything Goes Wrong', difficulty: 4 },
      { id: 'evy_4_83', leftLabel: 'Small Problem', rightLabel: 'Full Existential Crisis', difficulty: 4 },
      { id: 'evy_4_84', leftLabel: 'Tiny Argument', rightLabel: 'Silent Treatment', difficulty: 4 },
      { id: 'evy_4_85', leftLabel: 'Small Fight', rightLabel: 'Group Chat Tribunal', difficulty: 4 },
      { id: 'evy_4_86', leftLabel: 'One Screenshot', rightLabel: 'Relationship Evidence Folder', difficulty: 4 },
      { id: 'evy_4_87', leftLabel: 'One Voice Note', rightLabel: 'Accidental Public Playback', difficulty: 4 },
      { id: 'evy_4_88', leftLabel: 'Normal Call', rightLabel: 'Call at the Worst Possible Time', difficulty: 4 },
      { id: 'evy_4_89', leftLabel: 'Private Conversation', rightLabel: 'Someone Overheard Everything', difficulty: 4 },
      { id: 'evy_4_90', leftLabel: 'Quiet Evening', rightLabel: 'Unexpected Drama', difficulty: 4 },
      { id: 'evy_4_91', leftLabel: 'Romance', rightLabel: 'Romance With Serious Tension', difficulty: 4 },
      { id: 'evy_4_92', leftLabel: 'Cuddle', rightLabel: 'Cuddle That Feels Too Good to End', difficulty: 4 },
      {
        id: 'evy_4_93', leftLabel: 'One Kiss', rightLabel: "Can't Stop Thinking About Another", difficulty: 4
      },
      { id: 'evy_4_94', leftLabel: 'Flirting', rightLabel: 'Mutual Desire', difficulty: 4 },
      { id: 'evy_4_95', leftLabel: 'Romantic Mood', rightLabel: 'Dangerously Romantic Mood', difficulty: 4 },
      { id: 'evy_4_96', leftLabel: 'Cute Night', rightLabel: 'Things Get Very Steamy', difficulty: 4 },
      { id: 'evy_4_97', leftLabel: 'Date Night', rightLabel: 'Night Neither Person Forgets', difficulty: 4 },
      { id: 'evy_4_98', leftLabel: 'Good Chemistry', rightLabel: 'Overwhelming Chemistry', difficulty: 4 },
      {
        id: 'evy_4_99', leftLabel: 'Romantic Tension', rightLabel: "Cannot Pretend It's Not There", difficulty: 4
      },
      {
        id: 'evy_4_100', leftLabel: 'Normal Evening', rightLabel: 'Story You Tell Your Best Friend Immediately',
        difficulty: 4
      },
    ],

    // ============================================================
    // LEVEL 5 — MAXIMUM CHAOS
    // ============================================================
    5: [
      { id: 'evy_5_1', leftLabel: 'Small Crush', rightLabel: 'Completely Distracted by Them', difficulty: 5 },
      { id: 'evy_5_2', leftLabel: 'Checking Their Profile', rightLabel: 'Knowing Their Entire Timeline', difficulty: 5 },
      { id: 'evy_5_3', leftLabel: 'Casual Like', rightLabel: 'Strategic Like at 1 AM', difficulty: 5 },
      { id: 'evy_5_4', leftLabel: 'Normal Story', rightLabel: 'Clearly Posted for One Person', difficulty: 5 },
      { id: 'evy_5_5', leftLabel: 'Simple DM', rightLabel: 'DM You Were Terrified to Send', difficulty: 5 },
      { id: 'evy_5_6', leftLabel: 'Hey', rightLabel: 'Hey You 😉', difficulty: 5 },
      { id: 'evy_5_7', leftLabel: 'Friendly Text', rightLabel: 'Definitely Flirty Text', difficulty: 5 },
      { id: 'evy_5_8', leftLabel: 'One Reply', rightLabel: 'Waiting for Their Reply Like a Job', difficulty: 5 },
      { id: 'evy_5_9', leftLabel: 'Seen', rightLabel: 'Seen at the Exact Wrong Time', difficulty: 5 },
      { id: 'evy_5_10', leftLabel: 'Goodnight', rightLabel: 'Goodnight That Definitely Means More', difficulty: 5 },
      { id: 'evy_5_11', leftLabel: 'Cute Smile', rightLabel: 'Smile That Completely Disarms You', difficulty: 5 },
      { id: 'evy_5_12', leftLabel: 'Eye Contact', rightLabel: 'Eye Contact With Serious Chemistry', difficulty: 5 },
      { id: 'evy_5_13', leftLabel: 'Flirting', rightLabel: 'Neither Person Is Pretending Anymore', difficulty: 5 },
      { id: 'evy_5_14', leftLabel: 'Small Spark', rightLabel: 'Full Fire', difficulty: 5 },
      { id: 'evy_5_15', leftLabel: 'Cute Compliment', rightLabel: 'Compliment That Ruins Your Ability to Focus', difficulty: 5 },
      { id: 'evy_5_16', leftLabel: 'Casual Touch', rightLabel: 'Touch You Keep Thinking About', difficulty: 5 },
      { id: 'evy_5_17', leftLabel: 'Accidental Touch', rightLabel: 'Neither Person Moves Away', difficulty: 5 },
      { id: 'evy_5_18', leftLabel: 'Sitting Close', rightLabel: 'Basically Sharing the Same Seat', difficulty: 5 },
      { id: 'evy_5_19', leftLabel: 'Personal Space', rightLabel: 'Personal Space Has Left the Chat', difficulty: 5 },
      { id: 'evy_5_20', leftLabel: 'Friendly Hug', rightLabel: 'Hug That Says Way Too Much', difficulty: 5 },
      { id: 'evy_5_21', leftLabel: 'Goodbye Hug', rightLabel: 'Neither Wants to Let Go', difficulty: 5 },
      { id: 'evy_5_22', leftLabel: 'Cheek Kiss', rightLabel: 'Kiss That Changes the Entire Mood', difficulty: 5 },
      { id: 'evy_5_23', leftLabel: 'First Kiss', rightLabel: 'Kiss You Replay in Your Head', difficulty: 5 },
      { id: 'evy_5_24', leftLabel: 'Quick Kiss', rightLabel: 'One Kiss Becomes Several', difficulty: 5 },
      { id: 'evy_5_25', leftLabel: 'Goodnight Kiss', rightLabel: 'Absolutely Not Ready for Goodnight', difficulty: 5 },
      { id: 'evy_5_26', leftLabel: 'One More Kiss', rightLabel: 'Okay, One More After That', difficulty: 5 },
      { id: 'evy_5_27', leftLabel: 'Romantic Kiss', rightLabel: 'Very Passionate Kiss', difficulty: 5 },
      { id: 'evy_5_28', leftLabel: 'Cute Moment', rightLabel: 'Very Steamy Moment', difficulty: 5 },
      { id: 'evy_5_29', leftLabel: 'Romantic Mood', rightLabel: 'Dangerously Seductive Mood', difficulty: 5 },
      { id: 'evy_5_30', leftLabel: 'Flirty Energy', rightLabel: 'Impossible-to-Ignore Sexual Tension', difficulty: 5 },
      { id: 'evy_5_31', leftLabel: 'Cute Cuddle', rightLabel: 'Cuddle You Never Want to End', difficulty: 5 },
      { id: 'evy_5_32', leftLabel: 'Cuddling', rightLabel: 'Completely Lost in the Moment', difficulty: 5 },
      { id: 'evy_5_33', leftLabel: 'Movie Night', rightLabel: 'Movie Is Completely Forgotten', difficulty: 5 },
      { id: 'evy_5_34', leftLabel: 'Netflix Date', rightLabel: 'Netflix Is Now Decorative', difficulty: 5 },
      { id: 'evy_5_35', leftLabel: 'Sleepover', rightLabel: 'Sleepover With Dangerous Chemistry', difficulty: 5 },
      { id: 'evy_5_36', leftLabel: 'Late Night Talk', rightLabel: 'Nobody Is Going to Sleep', difficulty: 5 },
      {
        id: 'evy_5_37', leftLabel: 'Goodnight', rightLabel: "Suddenly It's 4 AM", difficulty: 5
      },
      { id: 'evy_5_38', leftLabel: 'One More Hour', rightLabel: 'Morning Has Arrived', difficulty: 5 },
      { id: 'evy_5_39', leftLabel: 'Date Night', rightLabel: 'Date That Turns Into an All-Nighter', difficulty: 5 },
      { id: 'evy_5_40', leftLabel: 'Goodbye', rightLabel: 'Neither Person Actually Leaves', difficulty: 5 },
      { id: 'evy_5_41', leftLabel: 'Friendship', rightLabel: 'Everyone Knows There Is Something More', difficulty: 5 },
      { id: 'evy_5_42', leftLabel: 'Situationship', rightLabel: 'Relationship Without Saying It', difficulty: 5 },
      { id: 'evy_5_43', leftLabel: 'Almost Dating', rightLabel: 'Emotionally Basically Married', difficulty: 5 },
      { id: 'evy_5_44', leftLabel: 'Casual Feelings', rightLabel: 'Very Serious Feelings', difficulty: 5 },
      {
        id: 'evy_5_45', leftLabel: 'Playing It Cool', rightLabel: "Everyone Knows You're Gone", difficulty: 5
      },
      { id: 'evy_5_46', leftLabel: 'Small Jealousy', rightLabel: 'Suddenly Very Possessive', difficulty: 5 },
      { id: 'evy_5_47', leftLabel: 'Someone Else Flirts', rightLabel: 'Instant Mood Change', difficulty: 5 },
      { id: 'evy_5_48', leftLabel: 'Secret Crush', rightLabel: 'Friends Running an Investigation', difficulty: 5 },
      { id: 'evy_5_49', leftLabel: 'Private Romance', rightLabel: 'Friends Already Know Everything', difficulty: 5 },
      { id: 'evy_5_50', leftLabel: 'Dating Secret', rightLabel: 'Family Almost Finds Out', difficulty: 5 },
      { id: 'evy_5_51', leftLabel: 'Normal Family Dinner', rightLabel: 'Marriage Proposal Ambush', difficulty: 5 },
      { id: 'evy_5_52', leftLabel: 'One Relative', rightLabel: 'Entire Family Investigating Your Love Life', difficulty: 5 },
      { id: 'evy_5_53', leftLabel: 'Simple Wedding', rightLabel: 'Wedding Becomes Family Reality Show', difficulty: 5 },
      {
        id: 'evy_5_54', leftLabel: 'Wedding Guest', rightLabel: "Asked When You're Getting Married", difficulty: 5
      },
      { id: 'evy_5_55', leftLabel: 'Private Life', rightLabel: 'Auntie Knows Before You Do', difficulty: 5 },
      { id: 'evy_5_56', leftLabel: 'One Secret', rightLabel: 'Family WhatsApp Knows', difficulty: 5 },
      { id: 'evy_5_57', leftLabel: 'Small Gossip', rightLabel: 'Neighborhood Breaking News', difficulty: 5 },
      { id: 'evy_5_58', leftLabel: 'One Screenshot', rightLabel: 'Entire Relationship Evidence Folder', difficulty: 5 },
      { id: 'evy_5_59', leftLabel: 'Private Chat', rightLabel: 'Screenshot in Friend Group', difficulty: 5 },
      { id: 'evy_5_60', leftLabel: 'One Voice Note', rightLabel: 'Played at Maximum Volume', difficulty: 5 },
      { id: 'evy_5_61', leftLabel: 'Saving Money', rightLabel: 'Salary Disappears Before Payday', difficulty: 5 },
      { id: 'evy_5_62', leftLabel: 'Budget Plan', rightLabel: 'Financial Disaster', difficulty: 5 },
      { id: 'evy_5_63', leftLabel: 'One Purchase', rightLabel: 'Three Packages Tomorrow', difficulty: 5 },
      { id: 'evy_5_64', leftLabel: 'Shopping Therapy', rightLabel: 'Shopping Has Become the Problem', difficulty: 5 },
      { id: 'evy_5_65', leftLabel: 'Small Sale', rightLabel: 'Entire Cart Purchased', difficulty: 5 },
      { id: 'evy_5_66', leftLabel: 'Free Delivery', rightLabel: 'Spent ₹1,000 to Save ₹50', difficulty: 5 },
      { id: 'evy_5_67', leftLabel: 'One Food Order', rightLabel: 'Food Delivery Is Your Personality', difficulty: 5 },
      { id: 'evy_5_68', leftLabel: 'Small Craving', rightLabel: 'Midnight Food Festival', difficulty: 5 },
      { id: 'evy_5_69', leftLabel: 'Healthy Monday', rightLabel: 'Weekend Food Apocalypse', difficulty: 5 },
      { id: 'evy_5_70', leftLabel: 'One Dessert', rightLabel: 'Ordering Dessert for the Table', difficulty: 5 },
      { id: 'evy_5_71', leftLabel: 'One Chai', rightLabel: 'Chai Is Now a Personality Trait', difficulty: 5 },
      { id: 'evy_5_72', leftLabel: 'Quick Chai', rightLabel: 'Three-Hour Gossip Session', difficulty: 5 },
      { id: 'evy_5_73', leftLabel: 'Casual Hangout', rightLabel: 'Entire Night Disappears', difficulty: 5 },
      { id: 'evy_5_74', leftLabel: 'One Friend', rightLabel: 'Entire Friend Group Appears', difficulty: 5 },
      { id: 'evy_5_75', leftLabel: 'Simple Plan', rightLabel: 'Unplanned Adventure', difficulty: 5 },
      { id: 'evy_5_76', leftLabel: 'Going Home Early', rightLabel: 'Sunrise Return', difficulty: 5 },
      { id: 'evy_5_77', leftLabel: 'One Photo', rightLabel: 'Next Morning Evidence', difficulty: 5 },
      { id: 'evy_5_78', leftLabel: 'Private Moment', rightLabel: 'Friend Group Knows by Breakfast', difficulty: 5 },
      { id: 'evy_5_79', leftLabel: 'Funny Story', rightLabel: 'Story You Can Never Tell Your Parents', difficulty: 5 },
      { id: 'evy_5_80', leftLabel: 'Mild Embarrassment', rightLabel: 'Permanent Character Development', difficulty: 5 },
      { id: 'evy_5_81', leftLabel: 'Small Mistake', rightLabel: 'Core Memory Created', difficulty: 5 },
      { id: 'evy_5_82', leftLabel: 'Awkward Moment', rightLabel: 'Still Thinking About It at 3 AM', difficulty: 5 },
      { id: 'evy_5_83', leftLabel: 'One Bad Decision', rightLabel: 'Story for the Next Ten Years', difficulty: 5 },
      { id: 'evy_5_84', leftLabel: 'Normal Evening', rightLabel: 'Unexpected Plot Twist', difficulty: 5 },
      { id: 'evy_5_85', leftLabel: 'Small Problem', rightLabel: 'Existential Crisis', difficulty: 5 },
      { id: 'evy_5_86', leftLabel: 'Minor Argument', rightLabel: 'Three-Day Silent Treatment', difficulty: 5 },
      { id: 'evy_5_87', leftLabel: 'One Fight', rightLabel: 'Group Chat Tribunal', difficulty: 5 },
      { id: 'evy_5_88', leftLabel: 'Normal Call', rightLabel: 'Worst Possible Timing', difficulty: 5 },
      { id: 'evy_5_89', leftLabel: 'Private Conversation', rightLabel: 'Someone Heard Everything', difficulty: 5 },
      { id: 'evy_5_90', leftLabel: 'Quiet Night', rightLabel: 'Unexpected Chaos', difficulty: 5 },
      { id: 'evy_5_91', leftLabel: 'Romance', rightLabel: 'Uncontrollable Chemistry', difficulty: 5 },
      { id: 'evy_5_92', leftLabel: 'Cuddle', rightLabel: 'Dangerously Intimate Cuddle', difficulty: 5 },
      {
        id: 'evy_5_93', leftLabel: 'One Kiss', rightLabel: "Can't Stop Wanting Another", difficulty: 5
      },
      { id: 'evy_5_94', leftLabel: 'Flirty Date', rightLabel: 'Sexual Tension You Can Feel', difficulty: 5 },
      { id: 'evy_5_95', leftLabel: 'Romantic Evening', rightLabel: 'Things Are Getting Very Steamy', difficulty: 5 },
      { id: 'evy_5_96', leftLabel: 'Cute Sleepover', rightLabel: 'Sleepover With Serious Temptation', difficulty: 5 },
      { id: 'evy_5_97', leftLabel: 'Goodnight Kiss', rightLabel: 'Definitely Not Saying Goodnight', difficulty: 5 },
      { id: 'evy_5_98', leftLabel: 'Romantic Tension', rightLabel: 'Overwhelming Desire', difficulty: 5 },
      { id: 'evy_5_99', leftLabel: 'One Perfect Date', rightLabel: 'Night You Never Forget', difficulty: 5 },
      { id: 'evy_5_100', leftLabel: 'Forgettable Day', rightLabel: 'Best Story of Your Life', difficulty: 5 },
    ],
  },
};
