import type { Genre, VibeContent } from '../../types/index.js';

export const everydayGenre: Genre = {
  id: 'everyday',
  name: 'Everyday Life',
  description: 'Broad everyday situations, chores, routines, and minor inconveniences.',
  icon: '🌎',
  levels: {
    1: [
      { id: 'evy_1_1', leftLabel: 'Good Morning', rightLabel: 'Bad Morning', difficulty: 1 },
      { id: 'evy_1_2', leftLabel: 'Short Line', rightLabel: 'Long Line', difficulty: 1 },
      { id: 'evy_1_3', leftLabel: 'Clean Room', rightLabel: 'Messy Room', difficulty: 1 },
      { id: 'evy_1_4', leftLabel: 'Hot Shower', rightLabel: 'Cold Shower', difficulty: 1 },
      { id: 'evy_1_5', leftLabel: 'Fast Internet', rightLabel: 'Slow Internet', difficulty: 1 },
      { id: 'evy_1_6', leftLabel: 'Good Hair Day', rightLabel: 'Bad Hair Day', difficulty: 1 },
      { id: 'evy_1_7', leftLabel: 'Sunny Day', rightLabel: 'Rainy Day', difficulty: 1 },
      { id: 'evy_1_8', leftLabel: 'Easy Chore', rightLabel: 'Hard Chore', difficulty: 1 },
      { id: 'evy_1_9', leftLabel: 'Good Sleep', rightLabel: 'Bad Sleep', difficulty: 1 },
      { id: 'evy_1_10', leftLabel: 'Tasty Meal', rightLabel: 'Disgusting Meal', difficulty: 1 },
      { id: 'evy_1_11', leftLabel: 'Friendly Neighbor', rightLabel: 'Annoying Neighbor', difficulty: 1 },
      { id: 'evy_1_12', leftLabel: 'Quick Errand', rightLabel: 'All-Day Errand', difficulty: 1 },
      { id: 'evy_1_13', leftLabel: 'Finding Money', rightLabel: 'Losing Money', difficulty: 1 },
      { id: 'evy_1_14', leftLabel: 'Waking up refreshed', rightLabel: 'Waking up tired', difficulty: 1 },
      { id: 'evy_1_15', leftLabel: 'Fresh Laundry', rightLabel: 'Dirty Laundry', difficulty: 1 },
      { id: 'evy_1_16', leftLabel: 'Green Lights', rightLabel: 'Red Lights', difficulty: 1 },
      { id: 'evy_1_17', leftLabel: 'Good Coffee', rightLabel: 'Bad Coffee', difficulty: 1 },
      { id: 'evy_1_18', leftLabel: 'Funny Joke', rightLabel: 'Bad Joke', difficulty: 1 },
      { id: 'evy_1_19', leftLabel: 'Warm Bed', rightLabel: 'Cold Floor', difficulty: 1 },
      { id: 'evy_1_20', leftLabel: 'Getting a Compliment', rightLabel: 'Getting Insulted', difficulty: 1 },
    ],
    2: [
      { id: 'evy_2_1', leftLabel: 'Slightly Annoying', rightLabel: 'Incredibly Frustrating', difficulty: 2 },
      { id: 'evy_2_2', leftLabel: 'Minor Inconvenience', rightLabel: 'Day Ruined', difficulty: 2 },
      { id: 'evy_2_3', leftLabel: 'Good Habit', rightLabel: 'Life-Changing Habit', difficulty: 2 },
      { id: 'evy_2_4', leftLabel: 'Bad Habit', rightLabel: 'Terrible Addiction', difficulty: 2 },
      { id: 'evy_2_5', leftLabel: 'Slightly Tired', rightLabel: 'Completely Exhausted', difficulty: 2 },
      { id: 'evy_2_6', leftLabel: 'Mild Headache', rightLabel: 'Migraine', difficulty: 2 },
      { id: 'evy_2_7', leftLabel: 'Slightly Late', rightLabel: 'Missed It Completely', difficulty: 2 },
      { id: 'evy_2_8', leftLabel: 'Small Puddle', rightLabel: 'Giant Mud Puddle', difficulty: 2 },
      { id: 'evy_2_9', leftLabel: 'Lost Pen', rightLabel: 'Lost Wallet', difficulty: 2 },
      { id: 'evy_2_10', leftLabel: 'Minor Spill', rightLabel: 'Major Stain', difficulty: 2 },
      { id: 'evy_2_11', leftLabel: 'Stubbing your toe', rightLabel: 'Stepping on a Lego', difficulty: 2 },
      { id: 'evy_2_12', leftLabel: 'A bad hair cut', rightLabel: 'A terrible dye job', difficulty: 2 },
      { id: 'evy_2_13', leftLabel: 'Forgetting a name', rightLabel: 'Forgetting a birthday', difficulty: 2 },
      { id: 'evy_2_14', leftLabel: 'A papercut', rightLabel: 'A burn', difficulty: 2 },
      { id: 'evy_2_15', leftLabel: 'An awkward silence', rightLabel: 'An offensive comment', difficulty: 2 },
      { id: 'evy_2_16', leftLabel: 'A parking ticket', rightLabel: 'Getting towed', difficulty: 2 },
      { id: 'evy_2_17', leftLabel: 'A cold', rightLabel: 'The flu', difficulty: 2 },
      { id: 'evy_2_18', leftLabel: 'A flat tire', rightLabel: 'An engine failure', difficulty: 2 },
      { id: 'evy_2_19', leftLabel: 'A burnt dinner', rightLabel: 'Food poisoning', difficulty: 2 },
      { id: 'evy_2_20', leftLabel: 'A cancelled plan (Relief)', rightLabel: 'A cancelled plan (Disappointment)', difficulty: 2 },
    ],
    3: [
      { id: 'evy_3_1', leftLabel: 'Trivial Choice', rightLabel: 'Important Decision', difficulty: 3 },
      { id: 'evy_3_2', leftLabel: 'White Lie', rightLabel: 'Massive Deception', difficulty: 3 },
      { id: 'evy_3_3', leftLabel: 'Slightly Awkward', rightLabel: 'Extremely Uncomfortable', difficulty: 3 },
      { id: 'evy_3_4', leftLabel: 'Harmless Prank', rightLabel: 'Cruel Joke', difficulty: 3 },
      { id: 'evy_3_5', leftLabel: 'Small Secret', rightLabel: 'Dark Secret', difficulty: 3 },
      { id: 'evy_3_6', leftLabel: 'Mild Disagreement', rightLabel: 'Huge Fight', difficulty: 3 },
      { id: 'evy_3_7', leftLabel: 'Petty Gossip', rightLabel: 'Malicious Rumor', difficulty: 3 },
      { id: 'evy_3_8', leftLabel: 'Innocent Mistake', rightLabel: 'Intentional Sabotage', difficulty: 3 },
      { id: 'evy_3_9', leftLabel: 'Slight Exaggeration', rightLabel: 'Total Fabrication', difficulty: 3 },
      { id: 'evy_3_10', leftLabel: 'Minor Grudge', rightLabel: 'Lifelong Vendetta', difficulty: 3 },
      { id: 'evy_3_11', leftLabel: 'A necessary evil', rightLabel: 'An unnecessary cruelty', difficulty: 3 },
      { id: 'evy_3_12', leftLabel: 'A harmless superstition', rightLabel: 'A dangerous delusion', difficulty: 3 },
      { id: 'evy_3_13', leftLabel: 'A polite fiction', rightLabel: 'A brutal truth', difficulty: 3 },
      { id: 'evy_3_14', leftLabel: 'A calculated risk', rightLabel: 'A reckless gamble', difficulty: 3 },
      { id: 'evy_3_15', leftLabel: 'A guilty pleasure', rightLabel: 'A shameful habit', difficulty: 3 },
      { id: 'evy_3_16', leftLabel: 'A subtle flex', rightLabel: 'An obnoxious brag', difficulty: 3 },
      { id: 'evy_3_17', leftLabel: 'A fair compromise', rightLabel: 'A complete surrender', difficulty: 3 },
      { id: 'evy_3_18', leftLabel: 'A healthy boundary', rightLabel: 'An emotional wall', difficulty: 3 },
      { id: 'evy_3_19', leftLabel: 'A genuine apology', rightLabel: 'A manipulative non-apology', difficulty: 3 },
      { id: 'evy_3_20', leftLabel: 'A constructive debate', rightLabel: 'A toxic argument', difficulty: 3 },
    ],
    4: [
      { id: 'evy_4_1', leftLabel: 'Mild Panic', rightLabel: 'Full Blown Panic Attack', difficulty: 4 },
      { id: 'evy_4_2', leftLabel: 'Slight Embarrassment', rightLabel: 'Mortifying Humiliation', difficulty: 4 },
      { id: 'evy_4_3', leftLabel: 'Fleeting Thought', rightLabel: 'Obsession', difficulty: 4 },
      { id: 'evy_4_4', leftLabel: 'Minor Regret', rightLabel: 'Biggest Regret', difficulty: 4 },
      { id: 'evy_4_5', leftLabel: 'Passing Fancy', rightLabel: 'True Love', difficulty: 4 },
      { id: 'evy_4_6', leftLabel: 'Slight Disappointment', rightLabel: 'Crushing Heartbreak', difficulty: 4 },
      { id: 'evy_4_7', leftLabel: 'Mild Joy', rightLabel: 'Pure Ecstasy', difficulty: 4 },
      { id: 'evy_4_8', leftLabel: 'Brief Sadness', rightLabel: 'Deep Depression', difficulty: 4 },
      { id: 'evy_4_9', leftLabel: 'Slight Fear', rightLabel: 'Paralyzing Terror', difficulty: 4 },
      { id: 'evy_4_10', leftLabel: 'Minor Surprise', rightLabel: 'Total Shock', difficulty: 4 },
      { id: 'evy_4_11', leftLabel: 'The illusion of control', rightLabel: 'The reality of chaos', difficulty: 4 },
      { id: 'evy_4_12', leftLabel: 'A memory you cherish', rightLabel: 'A memory you repress', difficulty: 4 },
      { id: 'evy_4_13', leftLabel: 'The desire to be seen', rightLabel: 'The desire to disappear', difficulty: 4 },
      { id: 'evy_4_14', leftLabel: 'A comforting lie', rightLabel: 'An uncomfortable truth', difficulty: 4 },
      { id: 'evy_4_15', leftLabel: 'The fear of missing out', rightLabel: 'The joy of missing out', difficulty: 4 },
      { id: 'evy_4_16', leftLabel: 'The pursuit of happiness', rightLabel: 'The acceptance of sorrow', difficulty: 4 },
      { id: 'evy_4_17', leftLabel: 'A rational fear', rightLabel: 'An irrational phobia', difficulty: 4 },
      { id: 'evy_4_18', leftLabel: 'The feeling of nostalgia', rightLabel: 'The feeling of regret', difficulty: 4 },
      { id: 'evy_4_19', leftLabel: 'A necessary sacrifice', rightLabel: 'A pointless tragedy', difficulty: 4 },
      { id: 'evy_4_20', leftLabel: 'The burden of empathy', rightLabel: 'The luxury of apathy', difficulty: 4 },
    ],
    5: [
      { id: 'evy_5_1', leftLabel: 'Forgettable Day', rightLabel: 'Best Day Ever', difficulty: 5 },
      { id: 'evy_5_2', leftLabel: 'Normal Interaction', rightLabel: 'Life Altering Meeting', difficulty: 5 },
      { id: 'evy_5_3', leftLabel: 'Trivial Realization', rightLabel: 'Profound Epiphany', difficulty: 5 },
      { id: 'evy_5_4', leftLabel: 'Small Coincidence', rightLabel: 'Miracle', difficulty: 5 },
      { id: 'evy_5_5', leftLabel: 'Minor Change', rightLabel: 'Paradigm Shift', difficulty: 5 },
      { id: 'evy_5_6', leftLabel: 'Fleeting Memory', rightLabel: 'Core Memory', difficulty: 5 },
      { id: 'evy_5_7', leftLabel: 'Passing Mood', rightLabel: 'Personality Trait', difficulty: 5 },
      { id: 'evy_5_8', leftLabel: 'Small Sacrifice', rightLabel: 'Ultimate Sacrifice', difficulty: 5 },
      { id: 'evy_5_9', leftLabel: 'Minor Obstacle', rightLabel: 'Insurmountable Barrier', difficulty: 5 },
      { id: 'evy_5_10', leftLabel: 'Slight Improvement', rightLabel: 'Total Transformation', difficulty: 5 },
      { id: 'evy_5_11', leftLabel: 'The meaning of life', rightLabel: 'The inevitability of death', difficulty: 5 },
      { id: 'evy_5_12', leftLabel: 'The illusion of time', rightLabel: 'The reality of aging', difficulty: 5 },
      { id: 'evy_5_13', leftLabel: 'The interconnectedness of all things', rightLabel: 'The fundamental isolation of consciousness', difficulty: 5 },
      { id: 'evy_5_14', leftLabel: 'The beauty of the mundane', rightLabel: 'The terror of the sublime', difficulty: 5 },
      { id: 'evy_5_15', leftLabel: 'The absurdity of existence', rightLabel: 'The inherent purpose of existence', difficulty: 5 },
      { id: 'evy_5_16', leftLabel: 'The concept of infinity', rightLabel: 'The concept of nothingness', difficulty: 5 },
      { id: 'evy_5_17', leftLabel: 'The fragility of human civilization', rightLabel: 'The resilience of nature', difficulty: 5 },
      { id: 'evy_5_18', leftLabel: 'The nature of consciousness', rightLabel: 'The mechanics of the universe', difficulty: 5 },
      { id: 'evy_5_19', leftLabel: 'The most profound thought you ever had', rightLabel: 'The most meaningless thought you ever had', difficulty: 5 },
      { id: 'evy_5_20', leftLabel: 'The feeling of being entirely alone', rightLabel: 'The feeling of being one with the universe', difficulty: 5 },
    ],
  },
};
