import type { Genre, VibeContent } from '../../types/index.js';

export const schoolGenre: Genre = {
  id: 'school',
  name: 'School Life',
  description: 'Nostalgic classroom politics, recess drama, and teenage angst.',
  icon: '🎒',
  levels: {
    1: [
      { id: 'sch_1_1', leftLabel: 'Good Teacher', rightLabel: 'Bad Teacher', difficulty: 1 },
      { id: 'sch_1_2', leftLabel: 'Cool Kid', rightLabel: 'Nerd', difficulty: 1 },
      { id: 'sch_1_3', leftLabel: 'Easy Subject', rightLabel: 'Hard Subject', difficulty: 1 },
      { id: 'sch_1_4', leftLabel: 'A+ Student', rightLabel: 'Failing Student', difficulty: 1 },
      { id: 'sch_1_5', leftLabel: 'Fun Field Trip', rightLabel: 'Boring Field Trip', difficulty: 1 },
      { id: 'sch_1_6', leftLabel: 'Best Subject', rightLabel: 'Worst Subject', difficulty: 1 },
      { id: 'sch_1_7', leftLabel: 'Front Row', rightLabel: 'Back Row', difficulty: 1 },
      { id: 'sch_1_8', leftLabel: 'Strict Principal', rightLabel: 'Chill Principal', difficulty: 1 },
      { id: 'sch_1_9', leftLabel: 'Good Cafeteria Food', rightLabel: 'Gross Cafeteria Food', difficulty: 1 },
      { id: 'sch_1_10', leftLabel: 'Popular', rightLabel: 'Unpopular', difficulty: 1 },
      { id: 'sch_1_11', leftLabel: 'Heavy Backpack', rightLabel: 'Light Backpack', difficulty: 1 },
      { id: 'sch_1_12', leftLabel: 'Strict Rules', rightLabel: 'No Rules', difficulty: 1 },
      { id: 'sch_1_13', leftLabel: 'Good Excuses', rightLabel: 'Bad Excuses', difficulty: 1 },
      { id: 'sch_1_14', leftLabel: 'Group Project Carry', rightLabel: 'Group Project Slacker', difficulty: 1 },
      { id: 'sch_1_15', leftLabel: 'Morning Person', rightLabel: 'Night Owl', difficulty: 1 },
      { id: 'sch_1_16', leftLabel: 'Teacher’s Pet', rightLabel: 'Class Clown', difficulty: 1 },
      { id: 'sch_1_17', leftLabel: 'Neat Handwriting', rightLabel: 'Messy Handwriting', difficulty: 1 },
      { id: 'sch_1_18', leftLabel: 'Early to Class', rightLabel: 'Always Late', difficulty: 1 },
      { id: 'sch_1_19', leftLabel: 'Quiet Class', rightLabel: 'Loud Class', difficulty: 1 },
      { id: 'sch_1_20', leftLabel: 'Passes Notes', rightLabel: 'Uses Phone', difficulty: 1 },
    ],
    2: [
      { id: 'sch_2_1', leftLabel: 'Actually Useful in Life', rightLabel: 'Never Used Again', difficulty: 2 },
      { id: 'sch_2_2', leftLabel: 'Chill Substitute', rightLabel: 'Strict Substitute', difficulty: 2 },
      { id: 'sch_2_3', leftLabel: 'Band Kid Energy', rightLabel: 'Theater Kid Energy', difficulty: 2 },
      { id: 'sch_2_4', leftLabel: 'Tattletale', rightLabel: 'Loyal Friend', difficulty: 2 },
      { id: 'sch_2_5', leftLabel: 'Locker Next to Crush', rightLabel: 'Locker Next to Bully', difficulty: 2 },
      { id: 'sch_2_6', leftLabel: 'Cramming at 2 AM', rightLabel: 'Studied a Week Ago', difficulty: 2 },
      { id: 'sch_2_7', leftLabel: 'Fake Sick Day', rightLabel: 'Real Sick Day', difficulty: 2 },
      { id: 'sch_2_8', leftLabel: 'Hall Pass Abuser', rightLabel: 'Never Leaves Class', difficulty: 2 },
      { id: 'sch_2_9', leftLabel: 'Forgot Homework', rightLabel: 'Dog Actually Ate It', difficulty: 2 },
      { id: 'sch_2_10', leftLabel: 'C- but Tried Hard', rightLabel: 'A+ but Slept in Class', difficulty: 2 },
      { id: 'sch_2_11', leftLabel: 'PE Tryhard', rightLabel: 'PE Skipper', difficulty: 2 },
      { id: 'sch_2_12', leftLabel: 'High School Musical', rightLabel: 'Euphoria', difficulty: 2 },
      { id: 'sch_2_13', leftLabel: 'Valedictorian', rightLabel: 'Most Likely to Succeed', difficulty: 2 },
      { id: 'sch_2_14', leftLabel: 'Dodgeball Target', rightLabel: 'Dodgeball Sniper', difficulty: 2 },
      { id: 'sch_2_15', leftLabel: 'Borrowing a Pencil', rightLabel: 'Never Returning the Pencil', difficulty: 2 },
      { id: 'sch_2_16', leftLabel: 'Fire Drill in Winter', rightLabel: 'Fire Drill during a Test', difficulty: 2 },
      { id: 'sch_2_17', leftLabel: 'Senior Prank', rightLabel: 'Senior Vandalism', difficulty: 2 },
      { id: 'sch_2_18', leftLabel: 'Cafeteria Legend', rightLabel: 'Eats in Bathroom', difficulty: 2 },
      { id: 'sch_2_19', leftLabel: 'Aced the Quiz', rightLabel: 'Failed the Open Book Test', difficulty: 2 },
      { id: 'sch_2_20', leftLabel: 'Suspension', rightLabel: 'Detention', difficulty: 2 },
    ],
    3: [
      { id: 'sch_3_1', leftLabel: 'Middle School Cringe', rightLabel: 'High School Drama', difficulty: 3 },
      { id: 'sch_3_2', leftLabel: 'Main Character Energy', rightLabel: 'NPC Energy', difficulty: 3 },
      { id: 'sch_3_3', leftLabel: 'The "Cool" English Teacher', rightLabel: 'The Sad Math Teacher', difficulty: 3 },
      { id: 'sch_3_4', leftLabel: 'Gossip Starter', rightLabel: 'Gossip Finisher', difficulty: 3 },
      { id: 'sch_3_5', leftLabel: 'Dress Code Violation', rightLabel: 'Fashion Disaster', difficulty: 3 },
      { id: 'sch_3_6', leftLabel: 'Prom King', rightLabel: 'Prom Reject', difficulty: 3 },
      { id: 'sch_3_7', leftLabel: 'Reading the SparkNotes', rightLabel: 'Watching the Movie', difficulty: 3 },
      { id: 'sch_3_8', leftLabel: 'Parent-Teacher Conference Fear', rightLabel: 'Report Card Day Fear', difficulty: 3 },
      { id: 'sch_3_9', leftLabel: 'Assigned Seating Trauma', rightLabel: 'Group Project Trauma', difficulty: 3 },
      { id: 'sch_3_10', leftLabel: 'The "We Get Out at 3:15" Stare', rightLabel: 'The "Don\'t Call On Me" Stare', difficulty: 3 },
      { id: 'sch_3_11', leftLabel: 'Locker Combination Anxiety', rightLabel: 'Forgetting Your Schedule', difficulty: 3 },
      { id: 'sch_3_12', leftLabel: 'First Day Outfit', rightLabel: 'Last Day Outfit', difficulty: 3 },
      { id: 'sch_3_13', leftLabel: 'Texting Under the Desk', rightLabel: 'Sleeping With Eyes Open', difficulty: 3 },
      { id: 'sch_3_14', leftLabel: 'Befriending the Lunch Lady', rightLabel: 'Befriending the Janitor', difficulty: 3 },
      { id: 'sch_3_15', leftLabel: 'School Spirit Tryhard', rightLabel: 'Too Cool for Pep Rally', difficulty: 3 },
      { id: 'sch_3_16', leftLabel: 'Scent of Ax Body Spray', rightLabel: 'Scent of Expo Markers', difficulty: 3 },
      { id: 'sch_3_17', leftLabel: 'Failing Math', rightLabel: 'Failing Gym', difficulty: 3 },
      { id: 'sch_3_18', leftLabel: 'The Quiet Kid', rightLabel: 'The Over-Sharer', difficulty: 3 },
      { id: 'sch_3_19', leftLabel: 'Using Wikipedia', rightLabel: 'Using ChatGPT', difficulty: 3 },
      { id: 'sch_3_20', leftLabel: 'Getting Sent to the Principal', rightLabel: 'Getting Called Out on the Intercom', difficulty: 3 },
    ],
    4: [
      { id: 'sch_4_1', leftLabel: 'Peaking in High School', rightLabel: 'Late Bloomer', difficulty: 4 },
      { id: 'sch_4_2', leftLabel: 'The "My Dad is a Lawyer" Kid', rightLabel: 'The "I Know a Guy" Kid', difficulty: 4 },
      { id: 'sch_4_3', leftLabel: 'Trauma Bonding over Finals', rightLabel: 'Cutting Ties after Graduation', difficulty: 4 },
      { id: 'sch_4_4', leftLabel: 'The smell of old textbooks', rightLabel: 'The sound of the bell', difficulty: 4 },
      { id: 'sch_4_5', leftLabel: 'Meaningless Busywork', rightLabel: 'Soul-Crushing Essay', difficulty: 4 },
      { id: 'sch_4_6', leftLabel: 'Yearbook Quote Regret', rightLabel: 'Prom Photo Regret', difficulty: 4 },
      { id: 'sch_4_7', leftLabel: 'Believing the "Permanent Record"', rightLabel: 'Realizing Nothing Matters', difficulty: 4 },
      { id: 'sch_4_8', leftLabel: 'Teacher who overshares', rightLabel: 'Teacher who acts like a robot', difficulty: 4 },
      { id: 'sch_4_9', leftLabel: 'Nostalgic', rightLabel: 'Traumatizing', difficulty: 4 },
      { id: 'sch_4_10', leftLabel: 'The illusion of choice in electives', rightLabel: 'The harsh reality of prerequisites', difficulty: 4 },
      { id: 'sch_4_11', leftLabel: 'Macbeth', rightLabel: 'Romeo and Juliet', difficulty: 4 },
      { id: 'sch_4_12', leftLabel: 'Running the Pacer Test', rightLabel: 'Climbing the Rope', difficulty: 4 },
      { id: 'sch_4_13', leftLabel: 'Trying to be Unique', rightLabel: 'Desperate to Fit In', difficulty: 4 },
      { id: 'sch_4_14', leftLabel: 'First Kiss', rightLabel: 'First Heartbreak', difficulty: 4 },
      { id: 'sch_4_15', leftLabel: 'Unrequited Crush', rightLabel: 'Secret Relationship', difficulty: 4 },
      { id: 'sch_4_16', leftLabel: 'Calculus', rightLabel: 'Trigonometry', difficulty: 4 },
      { id: 'sch_4_17', leftLabel: 'The Popularity Hierarchy', rightLabel: 'The Academic Hierarchy', difficulty: 4 },
      { id: 'sch_4_18', leftLabel: 'Rebelling against the uniform', rightLabel: 'Rebelling against the curriculum', difficulty: 4 },
      { id: 'sch_4_19', leftLabel: 'Waiting for Summer', rightLabel: 'Dreading September', difficulty: 4 },
      { id: 'sch_4_20', leftLabel: 'The Valedictorian Speech', rightLabel: 'The Senior Ditch Day', difficulty: 4 },
    ],
    5: [
      { id: 'sch_5_1', leftLabel: 'A necessary evil', rightLabel: 'An outdated factory model', difficulty: 5 },
      { id: 'sch_5_2', leftLabel: 'Learning How to Learn', rightLabel: 'Learning How to Obey', difficulty: 5 },
      { id: 'sch_5_3', leftLabel: 'The tragedy of wasted potential', rightLabel: 'The miracle of late discovery', difficulty: 5 },
      { id: 'sch_5_4', leftLabel: 'Standardized Testing', rightLabel: 'Existential Dread', difficulty: 5 },
      { id: 'sch_5_5', leftLabel: 'The crushing weight of expectations', rightLabel: 'The terrifying freedom of graduation', difficulty: 5 },
      { id: 'sch_5_6', leftLabel: 'Knowing the answer but staying quiet', rightLabel: 'Not knowing but speaking confidently', difficulty: 5 },
      { id: 'sch_5_7', leftLabel: 'Realizing teachers are just adults', rightLabel: 'Realizing adults don\'t know anything', difficulty: 5 },
      { id: 'sch_5_8', leftLabel: 'High school as a prison', rightLabel: 'High school as a sanctuary', difficulty: 5 },
      { id: 'sch_5_9', leftLabel: 'The concept of "Cool"', rightLabel: 'The concept of "Cringe"', difficulty: 5 },
      { id: 'sch_5_10', leftLabel: 'Memorization', rightLabel: 'Actual Understanding', difficulty: 5 },
      { id: 'sch_5_11', leftLabel: 'The cliques we form', rightLabel: 'The tribes we inherit', difficulty: 5 },
      { id: 'sch_5_12', leftLabel: 'Chasing grades', rightLabel: 'Chasing passion', difficulty: 5 },
      { id: 'sch_5_13', leftLabel: 'The fear of being perceived', rightLabel: 'The desperation to be seen', difficulty: 5 },
      { id: 'sch_5_14', leftLabel: 'A coming-of-age movie', rightLabel: 'A psychological thriller', difficulty: 5 },
      { id: 'sch_5_15', leftLabel: 'The person you were', rightLabel: 'The person you pretended to be', difficulty: 5 },
      { id: 'sch_5_16', leftLabel: 'Systemic failure', rightLabel: 'Individual triumph', difficulty: 5 },
      { id: 'sch_5_17', leftLabel: 'The slow death of creativity', rightLabel: 'The birth of resilience', difficulty: 5 },
      { id: 'sch_5_18', leftLabel: 'Nostalgia as a liar', rightLabel: 'Trauma as a teacher', difficulty: 5 },
      { id: 'sch_5_19', leftLabel: 'The paradox of popularity', rightLabel: 'The burden of brilliance', difficulty: 5 },
      { id: 'sch_5_20', leftLabel: 'Is this going to be on the test?', rightLabel: 'Is this going to matter in 10 years?', difficulty: 5 },
    ],
  },
};
