import type { Genre, VibeContent } from '../../types/index.js';

const vibe = (
  id: string,
  leftLabel: string,
  rightLabel: string,
  difficulty: number
): VibeContent => ({
  id,
  leftLabel,
  rightLabel,
  difficulty,
});

export const spicyGenre: Genre = {
  id: 'spicy',
  name: 'Hot & Spicy World',
  description:
    'Flirting, attraction, cuddles, kisses, romance, intimacy, temptation, chemistry and spicy relationship drama.',
  icon: '🌶️',

  levels: {
    // ============================================================
    // LEVEL 1 — CRUSH & CUDDLE
    // ============================================================
    1: [
      vibe('spc_1_1', 'No Attraction', 'Instant Attraction', 1),
      vibe('spc_1_2', 'Tiny Crush', 'Huge Crush', 1),
      vibe('spc_1_3', 'Friendly Smile', 'Flirty Smile', 1),
      vibe('spc_1_4', 'Cute', 'Hot', 1),
      vibe('spc_1_5', 'Sweet', 'Spicy', 1),
      vibe('spc_1_6', 'Friendly Hug', 'Romantic Hug', 1),
      vibe('spc_1_7', 'Quick Hug', 'Long Hug', 1),
      vibe('spc_1_8', 'Side Hug', 'Full Embrace', 1),
      vibe('spc_1_9', 'Awkward Hug', 'Perfect Hug', 1),
      vibe('spc_1_10', 'Comforting Cuddle', 'Romantic Cuddle', 1),
      vibe('spc_1_11', 'Sitting Nearby', 'Sitting Very Close', 1),
      vibe('spc_1_12', 'Holding Hands', 'Fingers Interlocked', 1),
      vibe('spc_1_13', 'Hand Touch', 'Hand Holding', 1),
      vibe('spc_1_14', 'Shoulder Touch', 'Waist Touch', 1),
      vibe('spc_1_15', 'Cute Eye Contact', 'Intense Eye Contact', 1),
      vibe('spc_1_16', 'Quick Glance', 'Long Look', 1),
      vibe('spc_1_17', 'Friendly Smile', 'Flirty Smile', 1),
      vibe('spc_1_18', 'Casual Compliment', 'Make-Me-Blush Compliment', 1),
      vibe('spc_1_19', 'Nice', 'Charming', 1),
      vibe('spc_1_20', 'Attractive', 'Irresistible', 1),
      vibe('spc_1_21', 'Cute Face', 'Stunning Face', 1),
      vibe('spc_1_22', 'Nice Eyes', 'Hypnotic Eyes', 1),
      vibe('spc_1_23', 'Cute Smile', 'Dangerous Smile', 1),
      vibe('spc_1_24', 'Nice Voice', 'Very Attractive Voice', 1),
      vibe('spc_1_25', 'Good Style', 'Date-Night Style', 1),
      vibe('spc_1_26', 'Casual Outfit', 'Wow Outfit', 1),
      vibe('spc_1_27', 'Cute Selfie', 'Very Attractive Selfie', 1),
      vibe('spc_1_28', 'Normal Photo', 'Photo You Save', 1),
      vibe('spc_1_29', 'Like Their Story', 'Reply to Their Story', 1),
      vibe('spc_1_30', 'Like Their Photo', 'Slide Into Their DMs', 1),
      vibe('spc_1_31', 'Wait for Their Text', 'Text Them First', 1),
      vibe('spc_1_32', 'Slow Reply', 'Instant Reply', 1),
      vibe('spc_1_33', 'Casual Text', 'Flirty Text', 1),
      vibe('spc_1_34', 'Good Morning', 'Good Night', 1),
      vibe('spc_1_35', 'Cute Emoji', 'Flirty Emoji', 1),
      vibe('spc_1_36', 'One Heart', 'Heart-Eyes Energy', 1),
      vibe('spc_1_37', '“Hey”', '“Hey You 👀”', 1),
      vibe('spc_1_38', 'Small Spark', 'Instant Chemistry', 1),
      vibe('spc_1_39', 'Little Butterflies', 'Full Butterfly Attack', 1),
      vibe('spc_1_40', 'Slightly Nervous', 'Completely Flustered', 1),
      vibe('spc_1_41', 'Small Blush', 'Face Completely Red', 1),
      vibe('spc_1_42', 'Cute Date', 'Perfect Date', 1),
      vibe('spc_1_43', 'Coffee Date', 'Candlelight Date', 1),
      vibe('spc_1_44', 'Lunch Date', 'Late-Night Date', 1),
      vibe('spc_1_45', 'Movie Date', 'Movie You Barely Watch', 1),
      vibe('spc_1_46', 'Picnic', 'Sunset Picnic', 1),
      vibe('spc_1_47', 'Walk Together', 'Midnight Walk', 1),
      vibe('spc_1_48', 'Casual Drive', 'Late-Night Drive', 1),
      vibe('spc_1_49', 'Goodbye', '“Stay a Little Longer”', 1),
      vibe('spc_1_50', 'Quick Goodbye Hug', 'Hug Neither Wants to End', 1),
      vibe('spc_1_51', 'Cheek Kiss', 'Forehead Kiss', 1),
      vibe('spc_1_52', 'Air Kiss', 'Real Kiss', 1),
      vibe('spc_1_53', 'Almost Kiss', 'First Kiss', 1),
      vibe('spc_1_54', 'Sweet Kiss', 'Passionate Kiss', 1),
      vibe('spc_1_55', 'Quick Kiss', 'Long Kiss', 1),
      vibe('spc_1_56', 'Cute Kiss', 'Kiss That Gives Butterflies', 1),
      vibe('spc_1_57', 'Romantic', 'Very Romantic', 1),
      vibe('spc_1_58', 'Sweet Romance', 'Spicy Romance', 1),
      vibe('spc_1_59', 'Soft Energy', 'Magnetic Energy', 1),
      vibe('spc_1_60', 'Shy', 'Confident', 1),
      vibe('spc_1_61', 'Quiet Charm', 'Magnetic Charm', 1),
      vibe('spc_1_62', 'Funny', 'Dangerously Funny', 1),
      vibe('spc_1_63', 'Smart', 'Sexy Smart', 1),
      vibe('spc_1_64', 'Kind', 'Irresistibly Kind', 1),
      vibe('spc_1_65', 'Friendly', 'Flirty', 1),
      vibe('spc_1_66', 'Flirting', 'Heavy Flirting', 1),
      vibe('spc_1_67', 'Subtle Hint', 'Obvious Hint', 1),
      vibe('spc_1_68', 'Playing It Cool', 'Making a Move', 1),
      vibe('spc_1_69', 'Could Date', 'Would Date', 1),
      vibe('spc_1_70', 'Would Flirt', 'Would Kiss', 1),
      vibe('spc_1_71', 'Would Hug', 'Would Cuddle', 1),
      vibe('spc_1_72', 'Cuddle Buddy', 'Romantic Partner', 1),
      vibe('spc_1_73', 'Comfortable Silence', 'Electric Silence', 1),
      vibe('spc_1_74', 'Normal Conversation', 'Flirty Conversation', 1),
      vibe('spc_1_75', 'Cute Banter', 'Flirty Banter', 1),
      vibe('spc_1_76', 'Playful Teasing', 'Blush-Worthy Teasing', 1),
      vibe('spc_1_77', 'Nice Compliment', 'Dangerous Compliment', 1),
      vibe('spc_1_78', 'Cute Nickname', 'Flirty Nickname', 1),
      vibe('spc_1_79', 'Sweet Message', 'Message You Reread', 1),
      vibe('spc_1_80', 'Casual Call', 'Hours-Long Call', 1),
      vibe('spc_1_81', 'Goodnight Text', '“Wish You Were Here”', 1),
      vibe('spc_1_82', 'Secret Crush', 'Obvious Crush', 1),
      vibe('spc_1_83', 'Tiny Spark', 'Can’t Ignore the Chemistry', 1),
      vibe('spc_1_84', 'Mild Attraction', 'Strong Attraction', 1),
      vibe('spc_1_85', 'Cute Moment', 'Romantic Moment', 1),
      vibe('spc_1_86', 'Romantic Moment', 'Spicy Moment', 1),
      vibe('spc_1_87', 'Safe Crush', 'Dangerous Crush', 1),
      vibe('spc_1_88', 'Normal Date', 'Unforgettable Date', 1),
      vibe('spc_1_89', 'Sweet Vibes', 'Flirty Vibes', 1),
      vibe('spc_1_90', 'Calm', 'Butterflies Everywhere', 1),
      vibe('spc_1_91', 'Cute', 'Irresistible', 1),
      vibe('spc_1_92', 'Interesting', 'Intriguing', 1),
      vibe('spc_1_93', 'Attraction', 'Chemistry', 1),
      vibe('spc_1_94', 'Romance', 'Passion', 1),
      vibe('spc_1_95', 'Sweet', 'Tempting', 1),
      vibe('spc_1_96', 'Innocent', 'Flirty', 1),
      vibe('spc_1_97', 'Friendly Touch', 'Romantic Touch', 1),
      vibe('spc_1_98', 'Friendly Hug', 'Cuddle Session', 1),
      vibe('spc_1_99', 'Small Crush', 'Can’t Stop Thinking About Them', 1),
      vibe('spc_1_100', 'Good Vibes', 'Dangerously Good Vibes', 1),
    ],

    // ============================================================
    // LEVEL 2 — KISS & ROMANCE
    // ============================================================
    2: [
      vibe('spc_2_1', 'Tiny Crush', 'Can’t Stop Thinking About Them', 2),
      vibe('spc_2_2', 'Friendly Hug', 'Romantic Cuddle', 2),
      vibe('spc_2_3', 'Quick Cuddle', 'Hours-Long Cuddle', 2),
      vibe('spc_2_4', 'Sitting Nearby', 'Sitting Practically on Top of Each Other', 2),
      vibe('spc_2_5', 'Holding Hands', 'Fingers Interlocked', 2),
      vibe('spc_2_6', 'Hand Touch', 'Hand You Don’t Want to Let Go', 2),
      vibe('spc_2_7', 'Shoulder Touch', 'Waist Around', 2),
      vibe('spc_2_8', 'Cute Eye Contact', 'Eye Contact That Changes the Mood', 2),
      vibe('spc_2_9', 'Quick Glance', 'Slow Look', 2),
      vibe('spc_2_10', 'Flirty Smile', '“Come Here” Smile', 2),
      vibe('spc_2_11', 'Cute Teasing', 'Teasing That Makes You Blush', 2),
      vibe('spc_2_12', 'Friendly Banter', 'Flirty Banter', 2),
      vibe('spc_2_13', 'Casual Compliment', 'Compliment You Think About Later', 2),
      vibe('spc_2_14', '“You Look Nice”', '“You Look Really Good Tonight”', 2),
      vibe('spc_2_15', 'Cute Outfit', 'Date-Night Outfit', 2),
      vibe('spc_2_16', 'Normal Selfie', 'Selfie You Save', 2),
      vibe('spc_2_17', 'Like Their Story', 'Reply to Their Story', 2),
      vibe('spc_2_18', 'Follow', 'Turn Notifications On', 2),
      vibe('spc_2_19', 'Casual Text', 'Flirty Text', 2),
      vibe('spc_2_20', 'Double Text', 'Shameless Double Text', 2),
      vibe('spc_2_21', 'Good Morning', '“Wish You Were Here”', 2),
      vibe('spc_2_22', 'Goodnight', '“Don’t Make Me Miss You”', 2),
      vibe('spc_2_23', 'Cute Emoji', 'Very Flirty Emoji', 2),
      vibe('spc_2_24', 'One Heart', 'Way Too Many Hearts', 2),
      vibe('spc_2_25', 'Voice Note', 'Voice Note You Replay', 2),
      vibe('spc_2_26', 'Quick Call', 'Call Until Midnight', 2),
      vibe('spc_2_27', 'One Date', 'Three Dates in One Week', 2),
      vibe('spc_2_28', 'Coffee Date', 'Candlelight Dinner', 2),
      vibe('spc_2_29', 'Lunch Date', 'Late-Night Dinner', 2),
      vibe('spc_2_30', 'Movie Date', 'Movie Nobody Watches', 2),
      vibe('spc_2_31', 'Walk', 'Midnight Walk', 2),
      vibe('spc_2_32', 'Drive', 'Late-Night Drive', 2),
      vibe('spc_2_33', 'Picnic', 'Sunset Picnic', 2),
      vibe('spc_2_34', 'Cute Date', 'Date With Serious Chemistry', 2),
      vibe('spc_2_35', 'Goodbye Hug', 'Hug That Lasts Too Long', 2),
      vibe('spc_2_36', 'Cheek Kiss', 'Almost Kiss', 2),
      vibe('spc_2_37', 'Almost Kiss', 'First Kiss', 2),
      vibe('spc_2_38', 'First Kiss', 'Unexpected Kiss', 2),
      vibe('spc_2_39', 'Sweet Kiss', 'Passionate Kiss', 2),
      vibe('spc_2_40', 'Quick Kiss', 'Long Kiss', 2),
      vibe('spc_2_41', 'Cute Kiss', 'Kiss You Think About Tomorrow', 2),
      vibe('spc_2_42', 'Forehead Kiss', 'Kiss With Serious Chemistry', 2),
      vibe('spc_2_43', 'Butterflies', 'Completely Flustered', 2),
      vibe('spc_2_44', 'Small Blush', 'Can’t Hide the Blush', 2),
      vibe('spc_2_45', 'Nervous', 'Nervous in a Good Way', 2),
      vibe('spc_2_46', 'Small Spark', 'Electric Chemistry', 2),
      vibe('spc_2_47', 'Friendly Chemistry', 'Romantic Chemistry', 2),
      vibe('spc_2_48', 'Romantic Chemistry', 'Serious Tension', 2),
      vibe('spc_2_49', 'Subtle Flirting', 'Obvious Flirting', 2),
      vibe('spc_2_50', 'Playing It Cool', 'Making the First Move', 2),
      vibe('spc_2_51', 'Shy', 'Confident Flirt', 2),
      vibe('spc_2_52', 'Cute', 'Distractingly Attractive', 2),
      vibe('spc_2_53', 'Good Looking', 'Unfairly Good Looking', 2),
      vibe('spc_2_54', 'Charming', 'Ridiculously Charming', 2),
      vibe('spc_2_55', 'Nice Eyes', 'Eyes You Cannot Ignore', 2),
      vibe('spc_2_56', 'Cute Smile', 'Smile That Ruins Your Focus', 2),
      vibe('spc_2_57', 'Nice Voice', 'Voice That Changes the Mood', 2),
      vibe('spc_2_58', 'Good Style', 'Style That Turns Heads', 2),
      vibe('spc_2_59', 'Casual Outfit', 'Definitely Dressing to Impress', 2),
      vibe('spc_2_60', 'Cute Selfie', 'Thirst-Trap Energy', 2),
      vibe('spc_2_61', 'Friend Energy', 'Date Energy', 2),
      vibe('spc_2_62', 'Best Friend', 'Potential Soulmate', 2),
      vibe('spc_2_63', 'Secret Crush', 'Everyone Knows', 2),
      vibe('spc_2_64', 'Old Crush', 'Crush That Never Left', 2),
      vibe('spc_2_65', 'Celebrity Crush', 'Would Actually Date Them', 2),
      vibe('spc_2_66', 'Fictional Crush', 'Unfairly High Standards', 2),
      vibe('spc_2_67', 'Could Date', 'Would Date', 2),
      vibe('spc_2_68', 'Would Flirt', 'Would Kiss', 2),
      vibe('spc_2_69', 'Would Kiss', 'Would Cuddle All Night', 2),
      vibe('spc_2_70', 'Cuddle Buddy', 'Romantic Partner', 2),
      vibe('spc_2_71', 'Comfortable Silence', 'Electric Silence', 2),
      vibe('spc_2_72', 'Cute Moment', 'Moment You Replay Later', 2),
      vibe('spc_2_73', 'Normal Conversation', 'Conversation With Tension', 2),
      vibe('spc_2_74', 'Cute Tease', 'Dangerous Tease', 2),
      vibe('spc_2_75', 'Sweet Talk', 'Smooth Talk', 2),
      vibe('spc_2_76', 'Cute Nickname', 'Flirty Nickname', 2),
      vibe('spc_2_77', 'Sweet Message', 'Message You Screenshot', 2),
      vibe('spc_2_78', 'Goodnight Text', 'Text That Keeps You Awake', 2),
      vibe('spc_2_79', 'Casual Call', 'Call You Secretly Look Forward To', 2),
      vibe('spc_2_80', 'Cute Date', 'Date That Becomes a Core Memory', 2),
      vibe('spc_2_81', 'Small Jealousy', '“Who Was That?” Energy', 2),
      vibe('spc_2_82', 'Tiny Red Flag', 'Red Flag You Still Find Attractive', 2),
      vibe('spc_2_83', 'Green Flag', 'Marriage Material', 2),
      vibe('spc_2_84', 'Romantic', 'Hopelessly Romantic', 2),
      vibe('spc_2_85', 'Sweet', 'Sweet With Attitude', 2),
      vibe('spc_2_86', 'Innocent', 'Suspiciously Flirty', 2),
      vibe('spc_2_87', 'Safe', 'Tempting', 2),
      vibe('spc_2_88', 'Mild Attraction', 'Strong Attraction', 2),
      vibe('spc_2_89', 'Attraction', 'Temptation', 2),
      vibe('spc_2_90', 'Cute Chemistry', 'Can’t Deny the Chemistry', 2),
      vibe('spc_2_91', 'Soft Romance', 'Spicy Romance', 2),
      vibe('spc_2_92', 'Sweet Kiss', 'Kiss That Changes the Mood', 2),
      vibe('spc_2_93', 'Hug', 'Cuddle Session', 2),
      vibe('spc_2_94', 'Cuddle', 'Can’t Let Go', 2),
      vibe('spc_2_95', 'Flirty', 'Very Flirty', 2),
      vibe('spc_2_96', 'Hot', 'Dangerously Hot', 2),
      vibe('spc_2_97', 'Romantic', 'Intensely Romantic', 2),
      vibe('spc_2_98', 'Tempting', 'Very Tempting', 2),
      vibe('spc_2_99', 'Chemistry', 'Electric Chemistry', 2),
      vibe('spc_2_100', 'Spicy', 'Extra Spicy', 2),
    ],

    // ============================================================
    // LEVEL 3 — INTIMATE & SPICY
    // ============================================================
    3: [
      vibe('spc_3_1', 'Friendly Hug', 'Hug With Intentions', 3),
      vibe('spc_3_2', 'Quick Hug', 'Hug You Don’t Want to End', 3),
      vibe('spc_3_3', 'Casual Cuddle', 'Cuddle You Fall Asleep In', 3),
      vibe('spc_3_4', 'Short Cuddle', 'Hours-Long Cuddle', 3),
      vibe('spc_3_5', 'Sitting Close', 'Practically Tangled Together', 3),
      vibe('spc_3_6', 'Holding Hands', 'Fingers Locked Together', 3),
      vibe('spc_3_7', 'Hand Touch', 'Touch You Remember Later', 3),
      vibe('spc_3_8', 'Shoulder Touch', 'Waist Around', 3),
      vibe('spc_3_9', 'Friendly Touch', 'Definitely Flirty Touch', 3),
      vibe('spc_3_10', 'Eye Contact', 'Eye Contact That Feels Dangerous', 3),
      vibe('spc_3_11', 'Quick Look', 'Slow Look', 3),
      vibe('spc_3_12', 'Flirty Smile', 'Smile With Intentions', 3),
      vibe('spc_3_13', 'Cute Teasing', 'Teasing That Completely Flusters You', 3),
      vibe('spc_3_14', 'Playful Banter', 'Banter With Serious Tension', 3),
      vibe('spc_3_15', 'Cute Compliment', 'Compliment That Changes the Mood', 3),
      vibe('spc_3_16', '“You Look Good”', '“You Look REALLY Good”', 3),
      vibe('spc_3_17', 'Cute Outfit', 'Outfit That Demands Attention', 3),
      vibe('spc_3_18', 'Normal Selfie', 'Photo You Definitely Saved', 3),
      vibe('spc_3_19', 'Cute Photo', 'Photo That Starts a Situation', 3),
      vibe('spc_3_20', 'Casual DM', 'DM With Obvious Intentions', 3),
      vibe('spc_3_21', 'Like Their Story', 'Reply With “Looking Good 👀”', 3),
      vibe('spc_3_22', 'Casual Text', 'Text You Read Twice', 3),
      vibe('spc_3_23', 'Goodnight', '“Wish You Were Here”', 3),
      vibe('spc_3_24', 'Good Morning', '“You Were My First Thought”', 3),
      vibe('spc_3_25', 'Double Text', 'Shameless Triple Text', 3),
      vibe('spc_3_26', 'Flirty Emoji', 'Emoji That Changes Everything', 3),
      vibe('spc_3_27', 'Voice Note', 'Voice Note You Replay', 3),
      vibe('spc_3_28', 'Quick Call', 'Call Until 3AM', 3),
      vibe('spc_3_29', 'One Date', 'Date With Serious Chemistry', 3),
      vibe('spc_3_30', 'Coffee Date', 'Late-Night Date', 3),
      vibe('spc_3_31', 'Dinner', 'Dinner Nobody Wants to End', 3),
      vibe('spc_3_32', 'Movie Date', 'Movie Nobody Is Watching', 3),
      vibe('spc_3_33', 'Walk', 'Walk With Obvious Tension', 3),
      vibe('spc_3_34', 'Drive', 'Midnight Drive With Chemistry', 3),
      vibe('spc_3_35', 'Goodbye', '“Wait, Stay”', 3),
      vibe('spc_3_36', 'Goodbye Hug', 'Hug That Lasts Too Long', 3),
      vibe('spc_3_37', 'Cheek Kiss', 'Almost Kiss', 3),
      vibe('spc_3_38', 'Almost Kiss', 'Kiss That Actually Happens', 3),
      vibe('spc_3_39', 'First Kiss', 'Kiss You Think About for Days', 3),
      vibe('spc_3_40', 'Sweet Kiss', 'Intense Kiss', 3),
      vibe('spc_3_41', 'Quick Kiss', 'Long Kiss', 3),
      vibe('spc_3_42', 'Romantic Kiss', 'Passionate Kiss', 3),
      vibe('spc_3_43', 'Kiss', 'Kiss That Leaves You Smiling', 3),
      vibe('spc_3_44', 'Forehead Kiss', 'Kiss With Serious Chemistry', 3),
      vibe('spc_3_45', 'Butterflies', 'Completely Distracted', 3),
      vibe('spc_3_46', 'Blushing', 'Can’t Hide the Blush', 3),
      vibe('spc_3_47', 'Nervous', 'Dangerously Comfortable', 3),
      vibe('spc_3_48', 'Small Spark', 'Electric Chemistry', 3),
      vibe('spc_3_49', 'Romantic Chemistry', 'Serious Sexual Tension', 3),
      vibe('spc_3_50', 'Flirty Chemistry', 'Can’t Pretend It’s Friendly', 3),
      vibe('spc_3_51', 'Secret Crush', 'Crush Everyone Can See', 3),
      vibe('spc_3_52', 'Small Crush', 'Major Distraction', 3),
      vibe('spc_3_53', 'Old Crush', 'Crush That Never Left', 3),
      vibe('spc_3_54', 'Forbidden Crush', 'Crush You Should Avoid', 3),
      vibe('spc_3_55', 'Friend', 'Friend You Suddenly See Differently', 3),
      vibe('spc_3_56', 'Best Friend', 'Potential Soulmate', 3),
      vibe('spc_3_57', 'Coworker', 'Coworker With Chemistry', 3),
      vibe('spc_3_58', 'Neighbor', 'Neighbor You Secretly Notice', 3),
      vibe('spc_3_59', 'Celebrity Crush', 'Would Actually Date Them', 3),
      vibe('spc_3_60', 'Fictional Crush', 'Unfairly High Standards', 3),
      vibe('spc_3_61', 'Would Flirt', 'Would Make a Move', 3),
      vibe('spc_3_62', 'Would Kiss', 'Would Cuddle All Night', 3),
      vibe('spc_3_63', 'Would Date', 'Would Fall Hard', 3),
      vibe('spc_3_64', 'Could Resist', 'Would Probably Fold', 3),
      vibe('spc_3_65', 'Tempting', 'Very Hard to Resist', 3),
      vibe('spc_3_66', 'Attraction', 'Serious Temptation', 3),
      vibe('spc_3_67', 'Cute', 'Distractingly Hot', 3),
      vibe('spc_3_68', 'Good Looking', 'Unfairly Attractive', 3),
      vibe('spc_3_69', 'Charming', 'Dangerously Charming', 3),
      vibe('spc_3_70', 'Confident', 'Weaponized Confidence', 3),
      vibe('spc_3_71', 'Mysterious', 'Impossible to Ignore', 3),
      vibe('spc_3_72', 'Nice Voice', 'Voice That Changes the Mood', 3),
      vibe('spc_3_73', 'Nice Eyes', 'Eyes You Can’t Look Away From', 3),
      vibe('spc_3_74', 'Cute Smile', 'Smile That Ruins Your Focus', 3),
      vibe('spc_3_75', 'Good Scent', 'Scent You Remember', 3),
      vibe('spc_3_76', 'Casual Outfit', 'Outfit With Dangerous Energy', 3),
      vibe('spc_3_77', 'Sweet', 'Sweet With a Wild Side', 3),
      vibe('spc_3_78', 'Innocent', 'Suspiciously Innocent', 3),
      vibe('spc_3_79', 'Safe Choice', 'Risky Choice', 3),
      vibe('spc_3_80', 'Good Idea', 'Terrible but Tempting Idea', 3),
      vibe('spc_3_81', 'Should Walk Away', 'Definitely Staying', 3),
      vibe('spc_3_82', 'No Feelings', 'Feelings Nobody Admits', 3),
      vibe('spc_3_83', 'Casual', 'Definitely Not Casual', 3),
      vibe('spc_3_84', 'Talking Stage', 'Situationship', 3),
      vibe('spc_3_85', 'Situationship', 'Accidental Relationship', 3),
      vibe('spc_3_86', 'Rebound', 'Real Feelings', 3),
      vibe('spc_3_87', 'Private Chemistry', 'Everyone Notices', 3),
      vibe('spc_3_88', 'Quiet Attraction', 'Room-Filling Chemistry', 3),
      vibe('spc_3_89', 'Romantic', 'Passionate', 3),
      vibe('spc_3_90', 'Flirty', 'Unfairly Flirty', 3),
      vibe('spc_3_91', 'Sweet Romance', 'Steamy Romance', 3),
      vibe('spc_3_92', 'Cuddle', 'Can’t Let Go', 3),
      vibe('spc_3_93', 'Kiss', 'Kiss You Remember', 3),
      vibe('spc_3_94', 'Attraction', 'Tension', 3),
      vibe('spc_3_95', 'Chemistry', 'Electric Chemistry', 3),
      vibe('spc_3_96', 'Romance', 'Passion', 3),
      vibe('spc_3_97', 'Temptation', 'Dangerous Temptation', 3),
      vibe('spc_3_98', 'Flirty Vibes', 'Very Spicy Vibes', 3),
      vibe('spc_3_99', 'Hot', 'Dangerously Hot', 3),
      vibe('spc_3_100', 'Spicy', 'Absolutely Scandalous', 3),
    ],

    // ============================================================
    // LEVEL 4 — STEAMY
    // ============================================================
    4: [
      vibe('spc_4_1', 'Cute Hug', 'Hug With Serious Chemistry', 4),
      vibe('spc_4_2', 'Quick Cuddle', 'Cuddle You Never Want to End', 4),
      vibe('spc_4_3', 'Casual Cuddle', 'Cuddle That Changes the Mood', 4),
      vibe('spc_4_4', 'Sitting Close', 'Way Too Close to Be Innocent', 4),
      vibe('spc_4_5', 'Holding Hands', 'Fingers Locked Together', 4),
      vibe('spc_4_6', 'Friendly Touch', 'Touch With Obvious Intentions', 4),
      vibe('spc_4_7', 'Shoulder Touch', 'Waist Around', 4),
      vibe('spc_4_8', 'Quick Look', 'Slow Look', 4),
      vibe('spc_4_9', 'Eye Contact', 'Eye Contact You Have to Break', 4),
      vibe('spc_4_10', 'Flirty Smile', 'Smile With Dangerous Intentions', 4),
      vibe('spc_4_11', 'Cute Tease', 'Tease That Makes You Blush', 4),
      vibe('spc_4_12', 'Playful Banter', 'Banter That Feels Like a Challenge', 4),
      vibe('spc_4_13', 'Compliment', 'Compliment That Changes the Mood', 4),
      vibe('spc_4_14', '“You Look Good”', '“You Know Exactly What You’re Doing”', 4),
      vibe('spc_4_15', 'Cute Outfit', 'Outfit That Causes Problems', 4),
      vibe('spc_4_16', 'Normal Selfie', 'Selfie You Definitely Saved', 4),
      vibe('spc_4_17', 'Cute Photo', 'Photo That Starts a Situation', 4),
      vibe('spc_4_18', 'Story Like', 'Story Reply With Intentions', 4),
      vibe('spc_4_19', 'Casual DM', 'DM That Makes Things Interesting', 4),
      vibe('spc_4_20', '“Hey”', '“Hey You 👀”', 4),
      vibe('spc_4_21', 'Goodnight', '“Wish You Were Here”', 4),
      vibe('spc_4_22', 'Good Morning', '“You Were My First Thought”', 4),
      vibe('spc_4_23', 'Voice Note', 'Voice Note You Replay', 4),
      vibe('spc_4_24', 'Call', 'Call Until Morning', 4),
      vibe('spc_4_25', 'One Date', 'Date With Dangerous Chemistry', 4),
      vibe('spc_4_26', 'Dinner', 'Dinner Nobody Wants to End', 4),
      vibe('spc_4_27', 'Coffee', 'Coffee That Turns Into Midnight', 4),
      vibe('spc_4_28', 'Movie Date', 'Movie Nobody Is Watching', 4),
      vibe('spc_4_29', 'Walk', 'Walk With Serious Tension', 4),
      vibe('spc_4_30', 'Drive', 'Midnight Drive With Chemistry', 4),
      vibe('spc_4_31', 'Goodbye', '“Stay a Little Longer”', 4),
      vibe('spc_4_32', 'Goodbye Hug', 'Hug Neither Person Wants to End', 4),
      vibe('spc_4_33', 'Cheek Kiss', 'Almost Kiss', 4),
      vibe('spc_4_34', 'Almost Kiss', 'Actual Kiss', 4),
      vibe('spc_4_35', 'First Kiss', 'Kiss That Changes Everything', 4),
      vibe('spc_4_36', 'Sweet Kiss', 'Passionate Kiss', 4),
      vibe('spc_4_37', 'Quick Kiss', 'Long Kiss', 4),
      vibe('spc_4_38', 'Romantic Kiss', 'Intense Kiss', 4),
      vibe('spc_4_39', 'Kiss', 'Kiss That Leaves You Breathless', 4),
      vibe('spc_4_40', 'Forehead Kiss', 'Kiss With Serious Tension', 4),
      vibe('spc_4_41', 'Butterflies', 'Completely Flustered', 4),
      vibe('spc_4_42', 'Blushing', 'Trying Desperately Not to Blush', 4),
      vibe('spc_4_43', 'Nervous', 'Nervous in the Best Way', 4),
      vibe('spc_4_44', 'Cute Chemistry', 'Electric Chemistry', 4),
      vibe('spc_4_45', 'Romantic Tension', 'Steamy Tension', 4),
      vibe('spc_4_46', 'Flirty Tension', 'Sexual Tension', 4),
      vibe('spc_4_47', 'Small Spark', 'Dangerous Spark', 4),
      vibe('spc_4_48', 'Attraction', 'Serious Temptation', 4),
      vibe('spc_4_49', 'Could Resist', 'Would Probably Fold', 4),
      vibe('spc_4_50', 'Tempting', 'Almost Impossible to Resist', 4),
      vibe('spc_4_51', 'Secret Crush', 'Secret That Is Hard to Hide', 4),
      vibe('spc_4_52', 'Forbidden Crush', 'Crush You Should Not Have', 4),
      vibe('spc_4_53', 'Friend', 'Friend With Dangerous Chemistry', 4),
      vibe('spc_4_54', 'Best Friend', 'Potential Soulmate', 4),
      vibe('spc_4_55', 'Coworker', 'Coworker You Shouldn’t Flirt With', 4),
      vibe('spc_4_56', 'Ex', 'Ex You Still Have Chemistry With', 4),
      vibe('spc_4_57', 'Old Crush', 'Old Crush Who Still Has Power', 4),
      vibe('spc_4_58', 'Rebound', 'Rebound That Gets Complicated', 4),
      vibe('spc_4_59', 'Talking Stage', 'Situationship From Hell', 4),
      vibe('spc_4_60', 'Situationship', 'Accidentally in Love', 4),
      vibe('spc_4_61', 'Casual', 'Definitely Not Casual', 4),
      vibe('spc_4_62', 'No Feelings', 'Feelings Nobody Admits', 4),
      vibe('spc_4_63', 'Jealous', 'Can’t Hide the Jealousy', 4),
      vibe('spc_4_64', '“Who Is That?”', '“Why Are They Looking at You?”', 4),
      vibe('spc_4_65', 'Tiny Red Flag', 'Red Flag You’d Still Risk It For', 4),
      vibe('spc_4_66', 'Red Flag', 'Hot Enough to Make You Hesitate', 4),
      vibe('spc_4_67', 'Green Flag', 'Green Flag With Dangerous Chemistry', 4),
      vibe('spc_4_68', 'Healthy Romance', 'Intense Romance', 4),
      vibe('spc_4_69', 'Sweet', 'Sweet With a Wild Side', 4),
      vibe('spc_4_70', 'Innocent', 'Suspiciously Innocent', 4),
      vibe('spc_4_71', 'Safe Choice', 'Choice You Know Is Trouble', 4),
      vibe('spc_4_72', 'Good Idea', 'Terrible but Tempting Idea', 4),
      vibe('spc_4_73', 'Should Walk Away', 'Absolutely Staying', 4),
      vibe('spc_4_74', 'Keep It Secret', 'Tell Your Best Friend Immediately', 4),
      vibe('spc_4_75', 'Private Chemistry', 'Everyone Notices', 4),
      vibe('spc_4_76', 'Quiet Attraction', 'Room-Filling Chemistry', 4),
      vibe('spc_4_77', 'Cute Moment', 'Moment You Replay at 2AM', 4),
      vibe('spc_4_78', 'Romantic', 'Dangerously Romantic', 4),
      vibe('spc_4_79', 'Flirty', 'Unfairly Flirty', 4),
      vibe('spc_4_80', 'Sweet', 'Very Suggestive', 4),
      vibe('spc_4_81', 'Cuddle', 'Can’t Let Go', 4),
      vibe('spc_4_82', 'Kiss', 'Kiss You Keep Thinking About', 4),
      vibe('spc_4_83', 'Romance', 'Passion', 4),
      vibe('spc_4_84', 'Attraction', 'Desire', 4),
      vibe('spc_4_85', 'Chemistry', 'Unavoidable Chemistry', 4),
      vibe('spc_4_86', 'Flirting', 'Full-Time Flirting', 4),
      vibe('spc_4_87', 'Hot', 'Dangerously Hot', 4),
      vibe('spc_4_88', 'Sexy', 'Distractingly Sexy', 4),
      vibe('spc_4_89', 'Tempting', 'Irresistible', 4),
      vibe('spc_4_90', 'Romantic Mood', 'Steamy Mood', 4),
      vibe('spc_4_91', 'Soft Romance', 'Intense Romance', 4),
      vibe('spc_4_92', 'Date Night', 'Very Late Date Night', 4),
      vibe('spc_4_93', 'Cuddle', 'Serious Chemistry', 4),
      vibe('spc_4_94', 'Kiss', 'Can’t Stop Kissing', 4),
      vibe('spc_4_95', 'Flirty', 'Shamelessly Flirty', 4),
      vibe('spc_4_96', 'Attraction', 'Dangerous Attraction', 4),
      vibe('spc_4_97', 'Chemistry', 'Nuclear Chemistry', 4),
      vibe('spc_4_98', 'Temptation', 'Dangerous Temptation', 4),
      vibe('spc_4_99', 'Spicy', 'Very Spicy', 4),
      vibe('spc_4_100', 'Dangerous Vibes', '“This Is Going to End Badly”', 4),
    ],

    // ============================================================
    // LEVEL 5 — FINAL VIBE
    // Maximum romance, desire, chemistry and temptation
    // ============================================================
    5: [
      vibe('spc_5_1', 'Cute Crush', 'Person Who Could Ruin Your Standards', 5),
      vibe('spc_5_2', 'Attraction', 'Dangerous Attraction', 5),
      vibe('spc_5_3', 'Chemistry', 'Chemistry Everyone Can Feel', 5),
      vibe('spc_5_4', 'Flirting', 'Absolutely Shameless Flirting', 5),
      vibe('spc_5_5', 'Cute', 'Distractingly Hot', 5),
      vibe('spc_5_6', 'Good Looking', 'Unfairly Attractive', 5),
      vibe('spc_5_7', 'Charming', 'Completely Irresistible', 5),
      vibe('spc_5_8', 'Confident', 'Dangerously Charismatic', 5),
      vibe('spc_5_9', 'Mysterious', 'Impossible Not to Think About', 5),
      vibe('spc_5_10', 'Interesting', 'Can’t Stop Thinking About Them', 5),
      vibe('spc_5_11', 'Cute Smile', 'Smile That Destroys Your Composure', 5),
      vibe('spc_5_12', 'Nice Eyes', 'Eyes You Cannot Look Away From', 5),
      vibe('spc_5_13', 'Nice Voice', 'Voice That Changes the Entire Mood', 5),
      vibe('spc_5_14', 'Good Outfit', 'Outfit That Should Require a Warning', 5),
      vibe('spc_5_15', 'Casual Look', 'Absolutely Unfair Look', 5),
      vibe('spc_5_16', 'Cute Selfie', 'Photo That Starts a Situation', 5),
      vibe('spc_5_17', 'Normal Picture', 'Picture You Definitely Saved', 5),
      vibe('spc_5_18', 'Like Their Story', 'Reply That Changes Everything', 5),
      vibe('spc_5_19', 'Casual DM', 'DM With Very Obvious Intentions', 5),
      vibe('spc_5_20', '“Hey”', '“Hey You 👀”', 5),
      vibe('spc_5_21', 'Good Conversation', 'Conversation You Never Want to End', 5),
      vibe('spc_5_22', 'Late Reply', 'Reply You Were Waiting All Night For', 5),
      vibe('spc_5_23', 'Double Text', 'Absolutely Shameless Triple Text', 5),
      vibe('spc_5_24', 'Flirty Emoji', 'Emoji That Changes Everything', 5),
      vibe('spc_5_25', 'Cute Message', 'Message You Read Five Times', 5),
      vibe('spc_5_26', 'Goodnight', '“Wish You Were Here”', 5),
      vibe('spc_5_27', 'Good Morning', '“You Were My First Thought”', 5),
      vibe('spc_5_28', 'Voice Note', 'Voice Note You Replay', 5),
      vibe('spc_5_29', 'Quick Call', 'Call Until Morning', 5),
      vibe('spc_5_30', 'Late-Night Chat', 'Conversation Nobody Wants to End', 5),
      vibe('spc_5_31', 'Friendly Hug', 'Hug With Serious Intentions', 5),
      vibe('spc_5_32', 'Quick Cuddle', 'Cuddle You Never Want to End', 5),
      vibe('spc_5_33', 'Casual Cuddle', 'Cuddle That Changes Everything', 5),
      vibe('spc_5_34', 'Sitting Close', 'Way Too Close to Be Innocent', 5),
      vibe('spc_5_35', 'Holding Hands', 'Fingers Completely Interlocked', 5),
      vibe('spc_5_36', 'Friendly Touch', 'Touch With Obvious Intentions', 5),
      vibe('spc_5_37', 'Shoulder Touch', 'Waist Around', 5),
      vibe('spc_5_38', 'Quick Look', 'Look That Says Everything', 5),
      vibe('spc_5_39', 'Eye Contact', 'Eye Contact You Have to Break', 5),
      vibe('spc_5_40', 'Flirty Smile', 'Smile With Dangerous Intentions', 5),
      vibe('spc_5_41', 'Playful Tease', 'Tease That Completely Flusters You', 5),
      vibe('spc_5_42', 'Cute Banter', 'Banter That Feels Like a Challenge', 5),
      vibe('spc_5_43', 'Compliment', 'Compliment That Lives in Your Head for Days', 5),
      vibe('spc_5_44', '“You Look Good”', '“You Know Exactly What You’re Doing”', 5),
      vibe('spc_5_45', 'Cute Outfit', 'Outfit That Causes Problems', 5),
      vibe('spc_5_46', 'Normal Selfie', 'Selfie That Starts a Situation', 5),
      vibe('spc_5_47', 'Casual Date', 'Date With Unavoidable Chemistry', 5),
      vibe('spc_5_48', 'Dinner', 'Dinner Nobody Wants to End', 5),
      vibe('spc_5_49', 'Coffee', 'Coffee That Turns Into Midnight', 5),
      vibe('spc_5_50', 'Movie Date', 'Movie Nobody Is Watching', 5),
      vibe('spc_5_51', 'Walk', 'Walk With Dangerous Tension', 5),
      vibe('spc_5_52', 'Drive', 'Midnight Drive With Chemistry', 5),
      vibe('spc_5_53', 'Goodbye', '“Stay a Little Longer”', 5),
      vibe('spc_5_54', 'Goodbye Hug', 'Hug That Lasts a Little Too Long', 5),
      vibe('spc_5_55', 'Cheek Kiss', 'Almost Kiss', 5),
      vibe('spc_5_56', 'Almost Kiss', 'Kiss Nobody Saw Coming', 5),
      vibe('spc_5_57', 'First Kiss', 'Kiss That Changes Everything', 5),
      vibe('spc_5_58', 'Sweet Kiss', 'Passionate Kiss', 5),
      vibe('spc_5_59', 'Quick Kiss', 'Long Kiss', 5),
      vibe('spc_5_60', 'Romantic Kiss', 'Intense Kiss', 5),
      vibe('spc_5_61', 'Kiss', 'Kiss You Think About at 2AM', 5),
      vibe('spc_5_62', 'Butterflies', 'Can’t Remember What You Were Saying', 5),
      vibe('spc_5_63', 'Blushing', 'Absolutely Exposed by Your Face', 5),
      vibe('spc_5_64', 'Nervous', 'Dangerously Comfortable', 5),
      vibe('spc_5_65', 'Cute Chemistry', 'Electric Chemistry', 5),
      vibe('spc_5_66', 'Romantic Tension', 'Serious Sexual Tension', 5),
      vibe('spc_5_67', 'Flirty Tension', 'Can’t Pretend It’s Friendly', 5),
      vibe('spc_5_68', 'Small Spark', 'Unavoidable Spark', 5),
      vibe('spc_5_69', 'Attraction', 'Serious Temptation', 5),
      vibe('spc_5_70', 'Tempting', 'Almost Impossible to Resist', 5),
      vibe('spc_5_71', 'Could Resist', 'Would Probably Fold', 5),
      vibe('spc_5_72', 'Safe Choice', 'Choice You Know Is Trouble', 5),
      vibe('spc_5_73', 'Good Idea', 'Terrible but Tempting Idea', 5),
      vibe('spc_5_74', 'Should Walk Away', 'Absolutely Staying', 5),
      vibe('spc_5_75', 'Secret Crush', 'Secret That Is Impossible to Hide', 5),
      vibe('spc_5_76', 'Forbidden Crush', 'Crush You Know Is Trouble', 5),
      vibe('spc_5_77', 'Friend', 'Friend With Dangerous Chemistry', 5),
      vibe('spc_5_78', 'Best Friend', 'Potential Soulmate', 5),
      vibe('spc_5_79', 'Coworker', 'Coworker With Unfair Chemistry', 5),
      vibe('spc_5_80', 'Ex', 'Ex You Shouldn’t Text', 5),
      vibe('spc_5_81', 'Old Crush', 'Old Crush Who Still Has Power', 5),
      vibe('spc_5_82', 'Rebound', 'Rebound That Becomes Real', 5),
      vibe('spc_5_83', 'Talking Stage', 'Situationship With No Exit', 5),
      vibe('spc_5_84', 'Situationship', 'Accidental Relationship', 5),
      vibe('spc_5_85', 'Casual', 'Definitely Not Casual', 5),
      vibe('spc_5_86', 'No Feelings', 'Feelings Nobody Wants to Admit', 5),
      vibe('spc_5_87', 'Jealous', 'Can’t Hide the Jealousy', 5),
      vibe('spc_5_88', 'Tiny Red Flag', 'Red Flag You’d Still Risk It For', 5),
      vibe('spc_5_89', 'Red Flag', 'Hot Enough to Make You Hesitate', 5),
      vibe('spc_5_90', 'Green Flag', 'Green Flag With Dangerous Chemistry', 5),
      vibe('spc_5_91', 'Romantic', 'Hopelessly Romantic', 5),
      vibe('spc_5_92', 'Sweet', 'Sweet With a Wild Side', 5),
      vibe('spc_5_93', 'Innocent', 'Suspiciously Innocent', 5),
      vibe('spc_5_94', 'Private Chemistry', 'Everyone Can Feel It', 5),
      vibe('spc_5_95', 'Quiet Attraction', 'Room-Filling Chemistry', 5),
      vibe('spc_5_96', 'Romance', 'Passion', 5),
      vibe('spc_5_97', 'Attraction', 'Desire', 5),
      vibe('spc_5_98', 'Hot', 'Dangerously Hot', 5),
      vibe('spc_5_99', 'Temptation', 'Almost Irresistible Temptation', 5),
      vibe('spc_5_100', 'Final Vibe', '“We Probably Shouldn’t…”', 5),
    ],
  },
};
