import type { Genre, VibeContent } from '../../types/index.js';

export const workGenre: Genre = {
  id: 'work',
  name: 'Work Life',
  description: 'Corporate jargon, office politics, and the daily grind.',
  icon: '💼',
  levels: {
    1: [
      { id: 'wrk_1_1', leftLabel: 'Good Boss', rightLabel: 'Bad Boss', difficulty: 1 },
      { id: 'wrk_1_2', leftLabel: 'Early Shift', rightLabel: 'Late Shift', difficulty: 1 },
      { id: 'wrk_1_3', leftLabel: 'High Salary', rightLabel: 'Low Salary', difficulty: 1 },
      { id: 'wrk_1_4', leftLabel: 'Work from Home', rightLabel: 'Commute to Office', difficulty: 1 },
      { id: 'wrk_1_5', leftLabel: 'Long Meeting', rightLabel: 'Short Meeting', difficulty: 1 },
      { id: 'wrk_1_6', leftLabel: 'Friendly Coworker', rightLabel: 'Annoying Coworker', difficulty: 1 },
      { id: 'wrk_1_7', leftLabel: 'Coffee Break', rightLabel: 'Lunch Break', difficulty: 1 },
      { id: 'wrk_1_8', leftLabel: 'Promotion', rightLabel: 'Demotion', difficulty: 1 },
      { id: 'wrk_1_9', leftLabel: 'Hard Worker', rightLabel: 'Lazy Worker', difficulty: 1 },
      { id: 'wrk_1_10', leftLabel: 'Paid Overtime', rightLabel: 'Unpaid Overtime', difficulty: 1 },
      { id: 'wrk_1_11', leftLabel: 'Office Gossip', rightLabel: 'Office Silence', difficulty: 1 },
      { id: 'wrk_1_12', leftLabel: 'Good Coffee', rightLabel: 'Bad Office Coffee', difficulty: 1 },
      { id: 'wrk_1_13', leftLabel: 'Busy Day', rightLabel: 'Slow Day', difficulty: 1 },
      { id: 'wrk_1_14', leftLabel: 'Answering Emails', rightLabel: 'Taking Calls', difficulty: 1 },
      { id: 'wrk_1_15', leftLabel: 'Getting Fired', rightLabel: 'Quitting', difficulty: 1 },
      { id: 'wrk_1_16', leftLabel: 'Strict Dress Code', rightLabel: 'Casual Friday', difficulty: 1 },
      { id: 'wrk_1_17', leftLabel: 'Micromanager', rightLabel: 'Absentee Boss', difficulty: 1 },
      { id: 'wrk_1_18', leftLabel: 'Company Party', rightLabel: 'Team Building Retreat', difficulty: 1 },
      { id: 'wrk_1_19', leftLabel: 'Monday Morning', rightLabel: 'Friday Afternoon', difficulty: 1 },
      { id: 'wrk_1_20', leftLabel: 'Taking Vacation', rightLabel: 'Working Through Holidays', difficulty: 1 },
    ],
    2: [
      { id: 'wrk_2_1', leftLabel: 'Per My Last Email', rightLabel: 'Let\'s Take This Offline', difficulty: 2 },
      { id: 'wrk_2_2', leftLabel: 'Reply All Accident', rightLabel: 'Sending to Wrong Person', difficulty: 2 },
      { id: 'wrk_2_3', leftLabel: 'The "Yes Man"', rightLabel: 'The "Devil\'s Advocate"', difficulty: 2 },
      { id: 'wrk_2_4', leftLabel: 'Meeting that could have been an email', rightLabel: 'Email chain that should be a meeting', difficulty: 2 },
      { id: 'wrk_2_5', leftLabel: 'Stolen Lunch', rightLabel: 'Stolen Idea', difficulty: 2 },
      { id: 'wrk_2_6', leftLabel: 'Networking', rightLabel: 'Nepotism', difficulty: 2 },
      { id: 'wrk_2_7', leftLabel: 'LinkedIn Influencer', rightLabel: 'Quiet Quitter', difficulty: 2 },
      { id: 'wrk_2_8', leftLabel: 'Toxic Positivity', rightLabel: 'Constant Complaining', difficulty: 2 },
      { id: 'wrk_2_9', leftLabel: 'Hustle Culture', rightLabel: 'Work-Life Balance', difficulty: 2 },
      { id: 'wrk_2_10', leftLabel: 'Unlimited PTO Trap', rightLabel: 'No PTO Left', difficulty: 2 },
      { id: 'wrk_2_11', leftLabel: 'Forgetting to Mute', rightLabel: 'Talking on Mute', difficulty: 2 },
      { id: 'wrk_2_12', leftLabel: 'Pizza Party Reward', rightLabel: 'Actual Bonus', difficulty: 2 },
      { id: 'wrk_2_13', leftLabel: 'Synergy', rightLabel: 'Bandwidth', difficulty: 2 },
      { id: 'wrk_2_14', leftLabel: 'Ping Pong Table', rightLabel: 'Good Health Insurance', difficulty: 2 },
      { id: 'wrk_2_15', leftLabel: 'The Intern', rightLabel: 'The CEO', difficulty: 2 },
      { id: 'wrk_2_16', leftLabel: 'Fake Laugh at Boss\'s Joke', rightLabel: 'Fake Enthusiasm for Project', difficulty: 2 },
      { id: 'wrk_2_17', leftLabel: 'Leaving at 4:59', rightLabel: 'Arriving at 9:01', difficulty: 2 },
      { id: 'wrk_2_18', leftLabel: 'Open Floor Plan', rightLabel: 'Cubicles', difficulty: 2 },
      { id: 'wrk_2_19', leftLabel: 'Broken Printer', rightLabel: 'Slow Wi-Fi', difficulty: 2 },
      { id: 'wrk_2_20', leftLabel: 'HR Department', rightLabel: 'IT Department', difficulty: 2 },
    ],
    3: [
      { id: 'wrk_3_1', leftLabel: 'Constructive Criticism', rightLabel: 'Thinly Veiled Insult', difficulty: 3 },
      { id: 'wrk_3_2', leftLabel: 'Imposter Syndrome', rightLabel: 'Dunning-Kruger Effect', difficulty: 3 },
      { id: 'wrk_3_3', leftLabel: 'Corporate Loyalty', rightLabel: 'Mercenary Mentality', difficulty: 3 },
      { id: 'wrk_3_4', leftLabel: 'The Illusion of Productivity', rightLabel: 'Actual Impact', difficulty: 3 },
      { id: 'wrk_3_5', leftLabel: 'A "Culture Fit"', rightLabel: 'A "Disruptor"', difficulty: 3 },
      { id: 'wrk_3_6', leftLabel: 'Climbing the Corporate Ladder', rightLabel: 'Jumping Off the Corporate Ladder', difficulty: 3 },
      { id: 'wrk_3_7', leftLabel: 'The burden of competence', rightLabel: 'The bliss of mediocrity', difficulty: 3 },
      { id: 'wrk_3_8', leftLabel: 'Burning Out', rightLabel: 'Fading Away', difficulty: 3 },
      { id: 'wrk_3_9', leftLabel: 'A job you love but pays badly', rightLabel: 'A job you hate but pays well', difficulty: 3 },
      { id: 'wrk_3_10', leftLabel: 'The Peter Principle', rightLabel: 'Glass Ceiling', difficulty: 3 },
      { id: 'wrk_3_11', leftLabel: 'Mandatory Fun', rightLabel: 'Optional Misery', difficulty: 3 },
      { id: 'wrk_3_12', leftLabel: 'Being CC\'d aggressively', rightLabel: 'Being BCC\'d secretly', difficulty: 3 },
      { id: 'wrk_3_13', leftLabel: 'The 3PM Slump', rightLabel: 'The Sunday Scaries', difficulty: 3 },
      { id: 'wrk_3_14', leftLabel: 'Pretending to look busy', rightLabel: 'Actually being overwhelmed', difficulty: 3 },
      { id: 'wrk_3_15', leftLabel: 'Agile Methodology', rightLabel: 'Waterfall Methodology', difficulty: 3 },
      { id: 'wrk_3_16', leftLabel: 'A promotion without a raise', rightLabel: 'A raise without a promotion', difficulty: 3 },
      { id: 'wrk_3_17', leftLabel: 'The Office Martyr', rightLabel: 'The Office Slacker', difficulty: 3 },
      { id: 'wrk_3_18', leftLabel: 'Golden Handcuffs', rightLabel: 'Freedom of Unemployment', difficulty: 3 },
      { id: 'wrk_3_19', leftLabel: 'The commute as meditation', rightLabel: 'The commute as torture', difficulty: 3 },
      { id: 'wrk_3_20', leftLabel: 'Leaving a legacy', rightLabel: 'Just paying the bills', difficulty: 3 },
    ],
    4: [
      { id: 'wrk_4_1', leftLabel: 'Capitalism as innovation', rightLabel: 'Capitalism as exploitation', difficulty: 4 },
      { id: 'wrk_4_2', leftLabel: 'The alienation of modern labor', rightLabel: 'The fulfillment of a craft', difficulty: 4 },
      { id: 'wrk_4_3', leftLabel: 'Your work is your identity', rightLabel: 'Your work is just what you do', difficulty: 4 },
      { id: 'wrk_4_4', leftLabel: 'The gig economy', rightLabel: 'The 9-to-5 grind', difficulty: 4 },
      { id: 'wrk_4_5', leftLabel: 'Automated by AI', rightLabel: 'Outsourced', difficulty: 4 },
      { id: 'wrk_4_6', leftLabel: 'The illusion of meritocracy', rightLabel: 'The reality of office politics', difficulty: 4 },
      { id: 'wrk_4_7', leftLabel: 'A toxic workplace disguised as a family', rightLabel: 'A cold workplace functioning like a machine', difficulty: 4 },
      { id: 'wrk_4_8', leftLabel: 'The paradox of efficiency', rightLabel: 'The bureaucracy of scale', difficulty: 4 },
      { id: 'wrk_4_9', leftLabel: 'Selling your soul', rightLabel: 'Keeping your integrity but going broke', difficulty: 4 },
      { id: 'wrk_4_10', leftLabel: 'The sunk cost fallacy of a career', rightLabel: 'The terrifying leap of a career change', difficulty: 4 },
      { id: 'wrk_4_11', leftLabel: 'Middle management purgatory', rightLabel: 'Entry-level hell', difficulty: 4 },
      { id: 'wrk_4_12', leftLabel: 'A visionary leader', rightLabel: 'A charismatic sociopath', difficulty: 4 },
      { id: 'wrk_4_13', leftLabel: 'The commodification of passion', rightLabel: 'The weaponization of incompetence', difficulty: 4 },
      { id: 'wrk_4_14', leftLabel: 'Retirement as a goal', rightLabel: 'Retirement as a myth', difficulty: 4 },
      { id: 'wrk_4_15', leftLabel: 'The fear of obsolescence', rightLabel: 'The desire for irrelevance', difficulty: 4 },
      { id: 'wrk_4_16', leftLabel: 'A brilliant strategy poorly executed', rightLabel: 'A terrible strategy flawlessly executed', difficulty: 4 },
      { id: 'wrk_4_17', leftLabel: 'The tragedy of the commons in the breakroom', rightLabel: 'The prisoner\'s dilemma in performance reviews', difficulty: 4 },
      { id: 'wrk_4_18', leftLabel: 'Micromanagement out of anxiety', rightLabel: 'Neglect out of apathy', difficulty: 4 },
      { id: 'wrk_4_19', leftLabel: 'The aesthetics of productivity', rightLabel: 'The reality of output', difficulty: 4 },
      { id: 'wrk_4_20', leftLabel: 'Living to work', rightLabel: 'Working to live', difficulty: 4 },
    ],
    5: [
      { id: 'wrk_5_1', leftLabel: 'The inevitable heat death of the universe', rightLabel: 'Quarterly earnings reports', difficulty: 5 },
      { id: 'wrk_5_2', leftLabel: 'Sisyphus pushing the boulder', rightLabel: 'Answering emails until you die', difficulty: 5 },
      { id: 'wrk_5_3', leftLabel: 'The concept of "value creation"', rightLabel: 'The extraction of surplus labor', difficulty: 5 },
      { id: 'wrk_5_4', leftLabel: 'The inherent absurdity of the rat race', rightLabel: 'The comforting structure of routine', difficulty: 5 },
      { id: 'wrk_5_5', leftLabel: 'A cog in the machine', rightLabel: 'The ghost in the machine', difficulty: 5 },
      { id: 'wrk_5_6', leftLabel: 'The infinite growth paradigm', rightLabel: 'Ecological collapse', difficulty: 5 },
      { id: 'wrk_5_7', leftLabel: 'The panopticon of remote monitoring software', rightLabel: 'The isolation of the home office', difficulty: 5 },
      { id: 'wrk_5_8', leftLabel: 'The artificial scarcity of promotions', rightLabel: 'The artificial abundance of useless meetings', difficulty: 5 },
      { id: 'wrk_5_9', leftLabel: 'Defining success internally', rightLabel: 'Defining success by LinkedIn metrics', difficulty: 5 },
      { id: 'wrk_5_10', leftLabel: 'The fleeting nature of professional achievements', rightLabel: 'The enduring weight of professional mistakes', difficulty: 5 },
      { id: 'wrk_5_11', leftLabel: 'A job as a necessary suffering', rightLabel: 'A job as a distraction from mortality', difficulty: 5 },
      { id: 'wrk_5_12', leftLabel: 'The linguistic gymnastics of corporate apologies', rightLabel: 'The brutal honesty of a resignation letter', difficulty: 5 },
      { id: 'wrk_5_13', leftLabel: 'The paradox of "human resources"', rightLabel: 'Treating humans as capital', difficulty: 5 },
      { id: 'wrk_5_14', leftLabel: 'The illusion of upward mobility', rightLabel: 'The reality of structural inequality', difficulty: 5 },
      { id: 'wrk_5_15', leftLabel: 'The democratization of labor', rightLabel: 'The monopolization of wealth', difficulty: 5 },
      { id: 'wrk_5_16', leftLabel: 'The sublime terror of an empty inbox', rightLabel: 'The crushing despair of 10,000 unread messages', difficulty: 5 },
      { id: 'wrk_5_17', leftLabel: 'The banality of evil in middle management', rightLabel: 'The heroism of silent competence', difficulty: 5 },
      { id: 'wrk_5_18', leftLabel: 'The search for meaning in a spreadsheet', rightLabel: 'The realization that the spreadsheet is meaningless', difficulty: 5 },
      { id: 'wrk_5_19', leftLabel: 'The end of work', rightLabel: 'The beginning of purpose', difficulty: 5 },
      { id: 'wrk_5_20', leftLabel: 'Being replaced by an algorithm', rightLabel: 'Realizing you were an algorithm all along', difficulty: 5 },
    ],
  },
};
