import type { Genre, VibeContent } from '../../types/index.js';

export const workGenre: Genre = {
  id: 'work',
  name: 'Corporate World',
  description:
    'Indian office life, corporate politics, chai breaks, gossip, crushes, flirting, managers, HR drama and workplace chaos.',
  icon: '💼',
  levels: {
    1: [
      { id: 'wrk_1_1', leftLabel: 'Friendly Colleague', rightLabel: 'Office Crush', difficulty: 1 },
      { id: 'wrk_1_2', leftLabel: 'Normal Eye Contact', rightLabel: 'Awkward Eye Contact', difficulty: 1 },
      { id: 'wrk_1_3', leftLabel: 'Professional Smile', rightLabel: 'Flirty Smile', difficulty: 1 },
      { id: 'wrk_1_4', leftLabel: 'Quick Chai Break', rightLabel: 'Second Chai Break', difficulty: 1 },
      { id: 'wrk_1_5', leftLabel: 'Office Lunch', rightLabel: 'Waiting for Your Crush at Lunch', difficulty: 1 },
      { id: 'wrk_1_6', leftLabel: 'Normal Compliment', rightLabel: 'Make-Me-Blush Compliment', difficulty: 1 },
      { id: 'wrk_1_7', leftLabel: 'Good Morning', rightLabel: 'Good Morning With a Smile', difficulty: 1 },
      { id: 'wrk_1_8', leftLabel: 'Formal DM', rightLabel: 'Suspiciously Friendly DM', difficulty: 1 },
      { id: 'wrk_1_9', leftLabel: 'Work Question', rightLabel: 'Excuse to Start a Conversation', difficulty: 1 },
      { id: 'wrk_1_10', leftLabel: 'Handshake', rightLabel: 'Friendly Hug', difficulty: 1 },
      { id: 'wrk_1_11', leftLabel: 'Friendly Hug', rightLabel: 'Hug That Lasts Too Long', difficulty: 1 },
      { id: 'wrk_1_12', leftLabel: 'Normal Meeting', rightLabel: 'Meeting With Your Crush', difficulty: 1 },
      { id: 'wrk_1_13', leftLabel: 'Meeting Room', rightLabel: 'Meeting Room With Just Two People', difficulty: 1 },
      { id: 'wrk_1_14', leftLabel: 'Office Corridor', rightLabel: 'Unexpected Eye Contact', difficulty: 1 },
      { id: 'wrk_1_15', leftLabel: 'Lift Ride', rightLabel: 'Lift Ride With Your Crush', difficulty: 1 },
      { id: 'wrk_1_16', leftLabel: 'Normal Chai', rightLabel: 'Chai With Your Favourite Colleague', difficulty: 1 },
      { id: 'wrk_1_17', leftLabel: 'Team Lunch', rightLabel: 'Sitting Beside Your Crush', difficulty: 1 },
      { id: 'wrk_1_18', leftLabel: 'Casual Conversation', rightLabel: 'Flirty Conversation', difficulty: 1 },
      { id: 'wrk_1_19', leftLabel: 'Professional Joke', rightLabel: 'Inside Joke', difficulty: 1 },
      { id: 'wrk_1_20', leftLabel: 'Normal WhatsApp', rightLabel: 'Personal WhatsApp', difficulty: 1 },
      { id: 'wrk_1_21', leftLabel: 'Office Group', rightLabel: 'Secret Office Group', difficulty: 1 },
      { id: 'wrk_1_22', leftLabel: 'LinkedIn Connection', rightLabel: 'Instagram Follow', difficulty: 1 },
      { id: 'wrk_1_23', leftLabel: 'Instagram Follow', rightLabel: 'Story Reply', difficulty: 1 },
      { id: 'wrk_1_24', leftLabel: 'Story Like', rightLabel: 'Story Reply', difficulty: 1 },
      { id: 'wrk_1_25', leftLabel: 'Goodnight', rightLabel: 'Reached Home?', difficulty: 1 },
      { id: 'wrk_1_26', leftLabel: 'Work Text', rightLabel: 'Text After Work', difficulty: 1 },
      { id: 'wrk_1_27', leftLabel: '9 AM Message', rightLabel: '11 PM Message', difficulty: 1 },
      { id: 'wrk_1_28', leftLabel: 'Casual Call', rightLabel: 'Call After Work', difficulty: 1 },
      { id: 'wrk_1_29', leftLabel: 'Coffee Break', rightLabel: 'Coffee Date', difficulty: 1 },
      { id: 'wrk_1_30', leftLabel: 'Team Meeting', rightLabel: 'One-on-One', difficulty: 1 },
      { id: 'wrk_1_31', leftLabel: 'Normal Feedback', rightLabel: 'Feedback You Overthink', difficulty: 1 },
      { id: 'wrk_1_32', leftLabel: 'Manager Favourite', rightLabel: 'Manager Problem Child', difficulty: 1 },
      { id: 'wrk_1_33', leftLabel: 'Hard Worker', rightLabel: 'Smart Worker', difficulty: 1 },
      { id: 'wrk_1_34', leftLabel: 'Office Bestie', rightLabel: 'Office Crush', difficulty: 1 },
      { id: 'wrk_1_35', leftLabel: 'New Employee', rightLabel: 'New Office Crush', difficulty: 1 },
      { id: 'wrk_1_36', leftLabel: 'New Project', rightLabel: 'New Stress', difficulty: 1 },
      { id: 'wrk_1_37', leftLabel: 'Normal Friday', rightLabel: 'Friday After 6 PM', difficulty: 1 },
      { id: 'wrk_1_38', leftLabel: 'Monday Morning', rightLabel: 'Friday Afternoon', difficulty: 1 },
      { id: 'wrk_1_39', leftLabel: 'Lunch Break', rightLabel: 'Chai Break', difficulty: 1 },
      { id: 'wrk_1_40', leftLabel: 'One Chai', rightLabel: 'Four Chais', difficulty: 1 },
      { id: 'wrk_1_41', leftLabel: 'Pantry', rightLabel: 'Gossip Headquarters', difficulty: 1 },
      { id: 'wrk_1_42', leftLabel: 'Cafeteria', rightLabel: 'Office Dating Zone', difficulty: 1 },
      { id: 'wrk_1_43', leftLabel: 'Office Party', rightLabel: 'After-Party', difficulty: 1 },
      { id: 'wrk_1_44', leftLabel: 'Team Building', rightLabel: 'Team Bonding 👀', difficulty: 1 },
      { id: 'wrk_1_45', leftLabel: 'Secret Santa', rightLabel: 'Secret Crush', difficulty: 1 },
      { id: 'wrk_1_46', leftLabel: 'Birthday Cake', rightLabel: 'Birthday Attention', difficulty: 1 },
      { id: 'wrk_1_47', leftLabel: 'Casual Outfit', rightLabel: 'Dressing to Impress', difficulty: 1 },
      { id: 'wrk_1_48', leftLabel: 'Normal Friday Outfit', rightLabel: 'Crush-Approved Outfit', difficulty: 1 },
      { id: 'wrk_1_49', leftLabel: 'Work From Home', rightLabel: 'Work From Bed', difficulty: 1 },
      { id: 'wrk_1_50', leftLabel: 'Camera On', rightLabel: 'Camera Off', difficulty: 1 },
      { id: 'wrk_1_51', leftLabel: 'Mute', rightLabel: 'Forgot to Mute', difficulty: 1 },
      { id: 'wrk_1_52', leftLabel: 'Screen Share', rightLabel: 'Wrong Tab', difficulty: 1 },
      { id: 'wrk_1_53', leftLabel: 'Email', rightLabel: 'WhatsApp', difficulty: 1 },
      { id: 'wrk_1_54', leftLabel: 'Teams Message', rightLabel: 'Personal DM', difficulty: 1 },
      { id: 'wrk_1_55', leftLabel: 'Formal Reply', rightLabel: 'Flirty Reply', difficulty: 1 },
      { id: 'wrk_1_56', leftLabel: 'Sure', rightLabel: 'Sure...', difficulty: 1 },
      { id: 'wrk_1_57', leftLabel: 'Okay', rightLabel: 'Okay 👍', difficulty: 1 },
      { id: 'wrk_1_58', leftLabel: 'Noted', rightLabel: 'Noted 👍', difficulty: 1 },
      { id: 'wrk_1_59', leftLabel: 'Per My Last Email', rightLabel: 'Just Following Up', difficulty: 1 },
      { id: 'wrk_1_60', leftLabel: 'Gentle Reminder', rightLabel: 'Not So Gentle Reminder', difficulty: 1 },
      { id: 'wrk_1_61', leftLabel: 'Meeting Could Be an Email', rightLabel: 'Email Could Be a Meeting', difficulty: 1 },
      { id: 'wrk_1_62', leftLabel: 'Short Meeting', rightLabel: 'Meeting That Never Ends', difficulty: 1 },
      { id: 'wrk_1_63', leftLabel: 'Early Login', rightLabel: 'Late Login', difficulty: 1 },
      { id: 'wrk_1_64', leftLabel: 'Leaving on Time', rightLabel: 'Waiting for Boss to Leave', difficulty: 1 },
      { id: 'wrk_1_65', leftLabel: '5 PM', rightLabel: '5:01 PM Emergency', difficulty: 1 },
      { id: 'wrk_1_66', leftLabel: 'Friday Task', rightLabel: 'Monday Problem', difficulty: 1 },
      { id: 'wrk_1_67', leftLabel: 'Office Gossip', rightLabel: 'Office Silence', difficulty: 1 },
      { id: 'wrk_1_68', leftLabel: 'Small Rumour', rightLabel: 'Everyone Knows', difficulty: 1 },
      { id: 'wrk_1_69', leftLabel: 'Private Chat', rightLabel: 'Screenshotted in Group', difficulty: 1 },
      { id: 'wrk_1_70', leftLabel: 'Manager Feedback', rightLabel: 'Appraisal Discussion', difficulty: 1 },
      { id: 'wrk_1_71', leftLabel: 'Appraisal', rightLabel: 'Waiting for Increment', difficulty: 1 },
      { id: 'wrk_1_72', leftLabel: 'Increment', rightLabel: 'Actually Good Increment', difficulty: 1 },
      { id: 'wrk_1_73', leftLabel: 'Bonus', rightLabel: 'Actual Bonus', difficulty: 1 },
      { id: 'wrk_1_74', leftLabel: 'Promotion', rightLabel: 'Someone Else Got Promoted', difficulty: 1 },
      { id: 'wrk_1_75', leftLabel: 'Workload', rightLabel: 'Impossible Workload', difficulty: 1 },
      { id: 'wrk_1_76', leftLabel: 'Busy Day', rightLabel: 'Fake Busy Day', difficulty: 1 },
      { id: 'wrk_1_77', leftLabel: 'Pretending to Work', rightLabel: 'Actually Working', difficulty: 1 },
      { id: 'wrk_1_78', leftLabel: 'Coffee', rightLabel: 'Coffee Keeping You Alive', difficulty: 1 },
      { id: 'wrk_1_79', leftLabel: 'Chai', rightLabel: 'Chai Keeping You Sane', difficulty: 1 },
      { id: 'wrk_1_80', leftLabel: 'Office AC', rightLabel: 'Office AC War', difficulty: 1 },
      { id: 'wrk_1_81', leftLabel: 'Lift', rightLabel: 'Stairs', difficulty: 1 },
      { id: 'wrk_1_82', leftLabel: 'Parking', rightLabel: 'Parking Lot Gossip', difficulty: 1 },
      { id: 'wrk_1_83', leftLabel: 'Cab Home', rightLabel: 'Cab Ride With Colleague', difficulty: 1 },
      { id: 'wrk_1_84', leftLabel: 'Late Office', rightLabel: 'Empty Office', difficulty: 1 },
      { id: 'wrk_1_85', leftLabel: 'Last Person Working', rightLabel: 'Everyone Already Left', difficulty: 1 },
      { id: 'wrk_1_86', leftLabel: 'Casual Goodbye', rightLabel: 'See You Tomorrow', difficulty: 1 },
      { id: 'wrk_1_87', leftLabel: 'Goodbye', rightLabel: 'Stay a Little Longer', difficulty: 1 },
      { id: 'wrk_1_88', leftLabel: 'Normal Hug', rightLabel: 'Crush Hug', difficulty: 1 },
      { id: 'wrk_1_89', leftLabel: 'Cheeky Smile', rightLabel: 'Flirty Smile', difficulty: 1 },
      { id: 'wrk_1_90', leftLabel: 'Nice Outfit', rightLabel: 'Wow Outfit', difficulty: 1 },
      { id: 'wrk_1_91', leftLabel: 'Cute', rightLabel: 'Attractive', difficulty: 1 },
      { id: 'wrk_1_92', leftLabel: 'Friendly', rightLabel: 'Flirty', difficulty: 1 },
      { id: 'wrk_1_93', leftLabel: 'Interesting', rightLabel: 'Intriguing', difficulty: 1 },
      { id: 'wrk_1_94', leftLabel: 'Small Spark', rightLabel: 'Real Chemistry', difficulty: 1 },
      { id: 'wrk_1_95', leftLabel: 'Work Friend', rightLabel: 'Potential Date', difficulty: 1 },
      { id: 'wrk_1_96', leftLabel: 'Office Friend', rightLabel: 'Office Bestie', difficulty: 1 },
      { id: 'wrk_1_97', leftLabel: 'Office Bestie', rightLabel: 'Office Crush', difficulty: 1 },
      { id: 'wrk_1_98', leftLabel: 'Office Crush', rightLabel: 'Everyone Knows', difficulty: 1 },
      { id: 'wrk_1_99', leftLabel: 'Normal Office Day', rightLabel: 'Interesting Office Day', difficulty: 1 },
      { id: 'wrk_1_100', leftLabel: 'Good Vibes', rightLabel: 'Dangerously Good Vibes', difficulty: 1 }
    ],

    2: [
      { id: 'wrk_2_1', leftLabel: 'Office Crush', rightLabel: 'Secret Office Crush', difficulty: 2 },
      { id: 'wrk_2_2', leftLabel: 'Secret Crush', rightLabel: 'Crush Everyone Knows', difficulty: 2 },
      { id: 'wrk_2_3', leftLabel: 'Friendly Hug', rightLabel: 'Definitely Not Friendly Hug', difficulty: 2 },
      { id: 'wrk_2_4', leftLabel: 'Quick Hug', rightLabel: 'Hug You Don’t Want to End', difficulty: 2 },
      { id: 'wrk_2_5', leftLabel: 'Friendly Touch', rightLabel: 'Definitely Flirty Touch', difficulty: 2 },
      { id: 'wrk_2_6', leftLabel: 'Normal Eye Contact', rightLabel: 'Eye Contact That Changes the Mood', difficulty: 2 },
      { id: 'wrk_2_7', leftLabel: 'Flirty Smile', rightLabel: 'Dangerous Smile', difficulty: 2 },
      { id: 'wrk_2_8', leftLabel: 'Professional Compliment', rightLabel: 'Compliment With Intentions', difficulty: 2 },
      { id: 'wrk_2_9', leftLabel: 'You Look Nice', rightLabel: 'You Look Really Good Today', difficulty: 2 },
      { id: 'wrk_2_10', leftLabel: 'Formal DM', rightLabel: 'Very Friendly DM', difficulty: 2 },
      { id: 'wrk_2_11', leftLabel: 'Work Question', rightLabel: 'Obvious Excuse to Text', difficulty: 2 },
      { id: 'wrk_2_12', leftLabel: 'Teams Message', rightLabel: 'Personal WhatsApp', difficulty: 2 },
      { id: 'wrk_2_13', leftLabel: 'Work WhatsApp', rightLabel: 'Late-Night WhatsApp', difficulty: 2 },
      { id: 'wrk_2_14', leftLabel: 'Goodnight', rightLabel: 'Reached Home?', difficulty: 2 },
      { id: 'wrk_2_15', leftLabel: 'Good Morning', rightLabel: 'You Were My First Thought', difficulty: 2 },
      { id: 'wrk_2_16', leftLabel: 'Casual Text', rightLabel: 'Text You Read Twice', difficulty: 2 },
      { id: 'wrk_2_17', leftLabel: 'Double Text', rightLabel: 'Shameless Double Text', difficulty: 2 },
      { id: 'wrk_2_18', leftLabel: 'Story Like', rightLabel: 'Story Reply', difficulty: 2 },
      { id: 'wrk_2_19', leftLabel: 'LinkedIn Follow', rightLabel: 'Instagram Follow', difficulty: 2 },
      { id: 'wrk_2_20', leftLabel: 'Instagram Follow', rightLabel: 'Instagram Story Reply', difficulty: 2 },
      { id: 'wrk_2_21', leftLabel: 'Chai Break', rightLabel: 'Secret Chai Date', difficulty: 2 },
      { id: 'wrk_2_22', leftLabel: 'Coffee Break', rightLabel: 'Coffee With Serious Chemistry', difficulty: 2 },
      { id: 'wrk_2_23', leftLabel: 'Lunch Together', rightLabel: 'Waiting for Them at Lunch', difficulty: 2 },
      { id: 'wrk_2_24', leftLabel: 'Team Lunch', rightLabel: 'Finding a Seat Beside Them', difficulty: 2 },
      { id: 'wrk_2_25', leftLabel: 'Office Party', rightLabel: 'Office Party After 10 PM', difficulty: 2 },
      { id: 'wrk_2_26', leftLabel: 'Team Event', rightLabel: 'After-Party', difficulty: 2 },
      { id: 'wrk_2_27', leftLabel: 'Business Trip', rightLabel: 'Suspiciously Fun Business Trip', difficulty: 2 },
      { id: 'wrk_2_28', leftLabel: 'Work Trip', rightLabel: 'Accidental Date', difficulty: 2 },
      { id: 'wrk_2_29', leftLabel: 'Cab Ride', rightLabel: 'Cab Ride With Your Crush', difficulty: 2 },
      { id: 'wrk_2_30', leftLabel: 'Lift Ride', rightLabel: 'Lift Ride You Both Remember', difficulty: 2 },
      { id: 'wrk_2_31', leftLabel: 'Meeting Room', rightLabel: 'Meeting Room With Just You Two', difficulty: 2 },
      { id: 'wrk_2_32', leftLabel: 'Calendar Invite', rightLabel: 'Why Is It Just Us?', difficulty: 2 },
      { id: 'wrk_2_33', leftLabel: 'One-on-One', rightLabel: 'One-on-One With Serious Chemistry', difficulty: 2 },
      { id: 'wrk_2_34', leftLabel: 'Office Corridor', rightLabel: 'Eye Contact Across the Office', difficulty: 2 },
      { id: 'wrk_2_35', leftLabel: 'Pantry', rightLabel: 'Gossip Headquarters', difficulty: 2 },
      { id: 'wrk_2_36', leftLabel: 'Cafeteria', rightLabel: 'Office Dating Zone', difficulty: 2 },
      { id: 'wrk_2_37', leftLabel: 'Parking Lot', rightLabel: 'Private Conversation', difficulty: 2 },
      { id: 'wrk_2_38', leftLabel: 'Late Office', rightLabel: 'Everyone Has Gone Home', difficulty: 2 },
      { id: 'wrk_2_39', leftLabel: 'Working Late', rightLabel: 'Suddenly Enjoying Overtime', difficulty: 2 },
      { id: 'wrk_2_40', leftLabel: 'Goodbye', rightLabel: 'Stay a Little Longer', difficulty: 2 },
      { id: 'wrk_2_41', leftLabel: 'Goodbye Hug', rightLabel: 'Hug That Lasts Too Long', difficulty: 2 },
      { id: 'wrk_2_42', leftLabel: 'Cheek Kiss', rightLabel: 'Almost Kiss', difficulty: 2 },
      { id: 'wrk_2_43', leftLabel: 'Almost Kiss', rightLabel: 'Actual Kiss', difficulty: 2 },
      { id: 'wrk_2_44', leftLabel: 'Cute', rightLabel: 'Distractingly Attractive', difficulty: 2 },
      { id: 'wrk_2_45', leftLabel: 'Professional', rightLabel: 'Suspiciously Flirty', difficulty: 2 },
      { id: 'wrk_2_46', leftLabel: 'Friendly', rightLabel: 'Clearly Interested', difficulty: 2 },
      { id: 'wrk_2_47', leftLabel: 'Small Crush', rightLabel: 'Major Distraction', difficulty: 2 },
      { id: 'wrk_2_48', leftLabel: 'Work Bestie', rightLabel: 'Office Crush', difficulty: 2 },
      { id: 'wrk_2_49', leftLabel: 'Office Crush', rightLabel: 'Actual Date', difficulty: 2 },
      { id: 'wrk_2_50', leftLabel: 'Actual Date', rightLabel: 'Office Secret', difficulty: 2 },
      { id: 'wrk_2_51', leftLabel: 'Office Secret', rightLabel: 'Office Gossip', difficulty: 2 },
      { id: 'wrk_2_52', leftLabel: 'Small Rumour', rightLabel: 'Entire Floor Knows', difficulty: 2 },
      { id: 'wrk_2_53', leftLabel: 'Private Chat', rightLabel: 'Screenshotted in Group', difficulty: 2 },
      { id: 'wrk_2_54', leftLabel: 'One Person Knows', rightLabel: 'Whole Team Knows', difficulty: 2 },
      { id: 'wrk_2_55', leftLabel: 'Manager Favourite', rightLabel: 'Manager’s Crush', difficulty: 2 },
      { id: 'wrk_2_56', leftLabel: 'Boss Joke', rightLabel: 'Fake Laugh', difficulty: 2 },
      { id: 'wrk_2_57', leftLabel: 'Boss Compliment', rightLabel: 'Suspicious Compliment', difficulty: 2 },
      { id: 'wrk_2_58', leftLabel: 'Manager Feedback', rightLabel: 'Personal Feedback', difficulty: 2 },
      { id: 'wrk_2_59', leftLabel: 'Performance Review', rightLabel: 'Salary Discussion', difficulty: 2 },
      { id: 'wrk_2_60', leftLabel: 'Appraisal', rightLabel: 'Appraisal Drama', difficulty: 2 },
      { id: 'wrk_2_61', leftLabel: 'Promotion', rightLabel: 'Promotion Politics', difficulty: 2 },
      { id: 'wrk_2_62', leftLabel: 'Good Increment', rightLabel: 'Disappointing Increment', difficulty: 2 },
      { id: 'wrk_2_63', leftLabel: 'Bonus', rightLabel: 'Bonus That Makes Everyone Jealous', difficulty: 2 },
      { id: 'wrk_2_64', leftLabel: 'Favourite Employee', rightLabel: 'Clearly Favoured Employee', difficulty: 2 },
      { id: 'wrk_2_65', leftLabel: 'Hard Worker', rightLabel: 'Office Martyr', difficulty: 2 },
      { id: 'wrk_2_66', leftLabel: 'Smart Worker', rightLabel: 'Workplace Survivor', difficulty: 2 },
      { id: 'wrk_2_67', leftLabel: 'Leaving on Time', rightLabel: 'Waiting for Boss', difficulty: 2 },
      { id: 'wrk_2_68', leftLabel: '5 PM', rightLabel: '5:01 PM Emergency', difficulty: 2 },
      { id: 'wrk_2_69', leftLabel: 'Friday Evening', rightLabel: 'Friday After 7 PM', difficulty: 2 },
      { id: 'wrk_2_70', leftLabel: 'Weekend', rightLabel: 'Weekend Work Message', difficulty: 2 },
      { id: 'wrk_2_71', leftLabel: 'Holiday', rightLabel: 'Holiday Work Call', difficulty: 2 },
      { id: 'wrk_2_72', leftLabel: 'WFH', rightLabel: 'WFH But Still Online', difficulty: 2 },
      { id: 'wrk_2_73', leftLabel: 'Camera Off', rightLabel: 'Definitely Not Working', difficulty: 2 },
      { id: 'wrk_2_74', leftLabel: 'Mute', rightLabel: 'Saying Something You Shouldn’t', difficulty: 2 },
      { id: 'wrk_2_75', leftLabel: 'Screen Share', rightLabel: 'Wrong WhatsApp Tab', difficulty: 2 },
      { id: 'wrk_2_76', leftLabel: 'Reply All', rightLabel: 'Career Risk', difficulty: 2 },
      { id: 'wrk_2_77', leftLabel: 'CC Manager', rightLabel: 'Passive Aggression', difficulty: 2 },
      { id: 'wrk_2_78', leftLabel: 'BCC', rightLabel: 'Office Politics', difficulty: 2 },
      { id: 'wrk_2_79', leftLabel: 'Per My Last Email', rightLabel: 'Just Following Up', difficulty: 2 },
      { id: 'wrk_2_80', leftLabel: 'Gentle Reminder', rightLabel: 'I’m Losing My Patience', difficulty: 2 },
      { id: 'wrk_2_81', leftLabel: 'Sure', rightLabel: 'Sure... 👀', difficulty: 2 },
      { id: 'wrk_2_82', leftLabel: 'Okay', rightLabel: 'Okay ❤️', difficulty: 2 },
      { id: 'wrk_2_83', leftLabel: 'Noted', rightLabel: 'Noted 👍', difficulty: 2 },
      { id: 'wrk_2_84', leftLabel: 'Professional Reply', rightLabel: 'Suspiciously Friendly Reply', difficulty: 2 },
      { id: 'wrk_2_85', leftLabel: 'Formal Goodbye', rightLabel: 'Personal Goodbye', difficulty: 2 },
      { id: 'wrk_2_86', leftLabel: 'Goodnight', rightLabel: 'Sleep Well ❤️', difficulty: 2 },
      { id: 'wrk_2_87', leftLabel: 'Casual Call', rightLabel: 'Call Until Midnight', difficulty: 2 },
      { id: 'wrk_2_88', leftLabel: 'Coffee', rightLabel: 'Coffee Date', difficulty: 2 },
      { id: 'wrk_2_89', leftLabel: 'Lunch', rightLabel: 'Lunch Date', difficulty: 2 },
      { id: 'wrk_2_90', leftLabel: 'Meeting', rightLabel: 'Excuse to Meet', difficulty: 2 },
      { id: 'wrk_2_91', leftLabel: 'Work Friend', rightLabel: 'Potential Relationship', difficulty: 2 },
      { id: 'wrk_2_92', leftLabel: 'Office Crush', rightLabel: 'Office Romance', difficulty: 2 },
      { id: 'wrk_2_93', leftLabel: 'Office Romance', rightLabel: 'Office Gossip', difficulty: 2 },
      { id: 'wrk_2_94', leftLabel: 'Office Gossip', rightLabel: 'HR Risk', difficulty: 2 },
      { id: 'wrk_2_95', leftLabel: 'Safe Flirting', rightLabel: 'Dangerous Flirting', difficulty: 2 },
      { id: 'wrk_2_96', leftLabel: 'Mild Chemistry', rightLabel: 'Electric Chemistry', difficulty: 2 },
      { id: 'wrk_2_97', leftLabel: 'Cute Vibes', rightLabel: 'Spicy Vibes', difficulty: 2 },
      { id: 'wrk_2_98', leftLabel: 'Friendly Chemistry', rightLabel: 'Romantic Chemistry', difficulty: 2 },
      { id: 'wrk_2_99', leftLabel: 'Normal Office Day', rightLabel: 'Drama-Filled Office Day', difficulty: 2 },
      { id: 'wrk_2_100', leftLabel: 'Professional', rightLabel: 'Definitely Personal', difficulty: 2 }
    ],

    3: [
      { id: 'wrk_3_1', leftLabel: 'Office Crush', rightLabel: 'Office Obsession', difficulty: 3 },
      { id: 'wrk_3_2', leftLabel: 'Secret Crush', rightLabel: 'Impossible-to-Hide Crush', difficulty: 3 },
      { id: 'wrk_3_3', leftLabel: 'Friendly Hug', rightLabel: 'Hug With Intentions', difficulty: 3 },
      { id: 'wrk_3_4', leftLabel: 'Cuddle-Like Hug', rightLabel: 'Definitely Not Professional', difficulty: 3 },
      { id: 'wrk_3_5', leftLabel: 'Friendly Touch', rightLabel: 'Touch With Obvious Intentions', difficulty: 3 },
      { id: 'wrk_3_6', leftLabel: 'Eye Contact', rightLabel: 'Eye Contact You Have to Break', difficulty: 3 },
      { id: 'wrk_3_7', leftLabel: 'Flirty Smile', rightLabel: 'Smile That Changes the Mood', difficulty: 3 },
      { id: 'wrk_3_8', leftLabel: 'Professional Compliment', rightLabel: 'Compliment That Feels Personal', difficulty: 3 },
      { id: 'wrk_3_9', leftLabel: 'You Look Good', rightLabel: 'You Know Exactly What You’re Doing', difficulty: 3 },
      { id: 'wrk_3_10', leftLabel: 'Work Question', rightLabel: 'Obvious Excuse to Talk', difficulty: 3 },
      { id: 'wrk_3_11', leftLabel: 'Formal DM', rightLabel: 'DM With Very Obvious Intentions', difficulty: 3 },
      { id: 'wrk_3_12', leftLabel: 'Teams Message', rightLabel: 'Personal WhatsApp', difficulty: 3 },
      { id: 'wrk_3_13', leftLabel: 'Work WhatsApp', rightLabel: 'Midnight WhatsApp', difficulty: 3 },
      { id: 'wrk_3_14', leftLabel: 'Goodnight', rightLabel: 'Wish You Were Here', difficulty: 3 },
      { id: 'wrk_3_15', leftLabel: 'Good Morning', rightLabel: 'Couldn’t Stop Thinking About You', difficulty: 3 },
      { id: 'wrk_3_16', leftLabel: 'Double Text', rightLabel: 'Triple Text', difficulty: 3 },
      { id: 'wrk_3_17', leftLabel: 'Story Like', rightLabel: 'Flirty Story Reply', difficulty: 3 },
      { id: 'wrk_3_18', leftLabel: 'Instagram Follow', rightLabel: 'Story Reply Every Day', difficulty: 3 },
      { id: 'wrk_3_19', leftLabel: 'Chai Break', rightLabel: 'Secret Chai Date', difficulty: 3 },
      { id: 'wrk_3_20', leftLabel: 'Coffee Break', rightLabel: 'Coffee With Chemistry', difficulty: 3 },
      { id: 'wrk_3_21', leftLabel: 'Lunch Together', rightLabel: 'Choosing the Seat Beside Them', difficulty: 3 },
      { id: 'wrk_3_22', leftLabel: 'Team Lunch', rightLabel: 'Ignoring Everyone Else', difficulty: 3 },
      { id: 'wrk_3_23', leftLabel: 'Office Party', rightLabel: 'After-Party Chemistry', difficulty: 3 },
      { id: 'wrk_3_24', leftLabel: 'Team Event', rightLabel: 'Unexpected Flirting', difficulty: 3 },
      { id: 'wrk_3_25', leftLabel: 'Business Trip', rightLabel: 'Business Trip With Tension', difficulty: 3 },
      { id: 'wrk_3_26', leftLabel: 'Work Trip', rightLabel: 'Accidental Date', difficulty: 3 },
      { id: 'wrk_3_27', leftLabel: 'Cab Ride', rightLabel: 'Cab Ride Nobody Wants to End', difficulty: 3 },
      { id: 'wrk_3_28', leftLabel: 'Lift Ride', rightLabel: 'Awkwardly Romantic Lift Ride', difficulty: 3 },
      { id: 'wrk_3_29', leftLabel: 'Meeting Room', rightLabel: 'Meeting Room With Tension', difficulty: 3 },
      { id: 'wrk_3_30', leftLabel: 'Calendar Invite', rightLabel: 'Why Is This Meeting Private?', difficulty: 3 },
      { id: 'wrk_3_31', leftLabel: 'One-on-One', rightLabel: 'One-on-One That Feels Like a Date', difficulty: 3 },
      { id: 'wrk_3_32', leftLabel: 'Office Corridor', rightLabel: 'Dangerous Eye Contact', difficulty: 3 },
      { id: 'wrk_3_33', leftLabel: 'Pantry', rightLabel: 'Gossip Headquarters', difficulty: 3 },
      { id: 'wrk_3_34', leftLabel: 'Cafeteria', rightLabel: 'Secret Meeting Spot', difficulty: 3 },
      { id: 'wrk_3_35', leftLabel: 'Parking Lot', rightLabel: 'Private Conversation', difficulty: 3 },
      { id: 'wrk_3_36', leftLabel: 'Late Office', rightLabel: 'Empty Office Chemistry', difficulty: 3 },
      { id: 'wrk_3_37', leftLabel: 'Working Late', rightLabel: 'Suddenly Not Complaining', difficulty: 3 },
      { id: 'wrk_3_38', leftLabel: 'Goodbye', rightLabel: 'Don’t Go Yet', difficulty: 3 },
      { id: 'wrk_3_39', leftLabel: 'Goodbye Hug', rightLabel: 'Hug Neither Wants to End', difficulty: 3 },
      { id: 'wrk_3_40', leftLabel: 'Cheek Kiss', rightLabel: 'Almost Kiss', difficulty: 3 },
      { id: 'wrk_3_41', leftLabel: 'Almost Kiss', rightLabel: 'Kiss That Changes Everything', difficulty: 3 },
      { id: 'wrk_3_42', leftLabel: 'Sweet Kiss', rightLabel: 'Passionate Kiss', difficulty: 3 },
      { id: 'wrk_3_43', leftLabel: 'Quick Kiss', rightLabel: 'Long Kiss', difficulty: 3 },
      { id: 'wrk_3_44', leftLabel: 'Cute', rightLabel: 'Distractingly Hot', difficulty: 3 },
      { id: 'wrk_3_45', leftLabel: 'Attractive', rightLabel: 'Irresistible', difficulty: 3 },
      { id: 'wrk_3_46', leftLabel: 'Friendly', rightLabel: 'Very Flirty', difficulty: 3 },
      { id: 'wrk_3_47', leftLabel: 'Flirting', rightLabel: 'Shameless Flirting', difficulty: 3 },
      { id: 'wrk_3_48', leftLabel: 'Small Crush', rightLabel: 'Major Distraction', difficulty: 3 },
      { id: 'wrk_3_49', leftLabel: 'Office Bestie', rightLabel: 'Office Crush', difficulty: 3 },
      { id: 'wrk_3_50', leftLabel: 'Office Crush', rightLabel: 'Secret Date', difficulty: 3 },
      { id: 'wrk_3_51', leftLabel: 'Secret Date', rightLabel: 'Actual Relationship', difficulty: 3 },
      { id: 'wrk_3_52', leftLabel: 'Office Romance', rightLabel: 'Office Scandal', difficulty: 3 },
      { id: 'wrk_3_53', leftLabel: 'Office Gossip', rightLabel: 'HR Conversation', difficulty: 3 },
      { id: 'wrk_3_54', leftLabel: 'Rumour', rightLabel: 'Everyone Knows', difficulty: 3 },
      { id: 'wrk_3_55', leftLabel: 'Private Chat', rightLabel: 'Leaked Screenshot', difficulty: 3 },
      { id: 'wrk_3_56', leftLabel: 'One Person Knows', rightLabel: 'Entire Floor Knows', difficulty: 3 },
      { id: 'wrk_3_57', leftLabel: 'Manager Favourite', rightLabel: 'Manager’s Obvious Favourite', difficulty: 3 },
      { id: 'wrk_3_58', leftLabel: 'Boss Compliment', rightLabel: 'Suspicious Boss Compliment', difficulty: 3 },
      { id: 'wrk_3_59', leftLabel: 'Manager Feedback', rightLabel: 'Too Personal Feedback', difficulty: 3 },
      { id: 'wrk_3_60', leftLabel: 'Performance Review', rightLabel: 'Salary Negotiation', difficulty: 3 },
      { id: 'wrk_3_61', leftLabel: 'Appraisal', rightLabel: 'Appraisal Anxiety', difficulty: 3 },
      { id: 'wrk_3_62', leftLabel: 'Promotion', rightLabel: 'Promotion Politics', difficulty: 3 },
      { id: 'wrk_3_63', leftLabel: 'Increment', rightLabel: 'Increment Drama', difficulty: 3 },
      { id: 'wrk_3_64', leftLabel: 'Bonus', rightLabel: 'Bonus Jealousy', difficulty: 3 },
      { id: 'wrk_3_65', leftLabel: 'Favourite Employee', rightLabel: 'Clearly Favoured Employee', difficulty: 3 },
      { id: 'wrk_3_66', leftLabel: 'Hard Worker', rightLabel: 'Office Martyr', difficulty: 3 },
      { id: 'wrk_3_67', leftLabel: 'Smart Worker', rightLabel: 'Workplace Survivor', difficulty: 3 },
      { id: 'wrk_3_68', leftLabel: 'Leaving at 6', rightLabel: 'Waiting for Boss', difficulty: 3 },
      { id: 'wrk_3_69', leftLabel: '5 PM', rightLabel: '11 PM', difficulty: 3 },
      { id: 'wrk_3_70', leftLabel: 'Friday Evening', rightLabel: 'Saturday Morning', difficulty: 3 },
      { id: 'wrk_3_71', leftLabel: 'Weekend', rightLabel: 'Weekend Work Call', difficulty: 3 },
      { id: 'wrk_3_72', leftLabel: 'Holiday', rightLabel: 'Holiday Work Message', difficulty: 3 },
      { id: 'wrk_3_73', leftLabel: 'WFH', rightLabel: 'WFH But Looking Good for One Person', difficulty: 3 },
      { id: 'wrk_3_74', leftLabel: 'Camera Off', rightLabel: 'Definitely Distracted', difficulty: 3 },
      { id: 'wrk_3_75', leftLabel: 'Mute', rightLabel: 'Saying Something Dangerous', difficulty: 3 },
      { id: 'wrk_3_76', leftLabel: 'Screen Share', rightLabel: 'Wrong Personal Chat', difficulty: 3 },
      { id: 'wrk_3_77', leftLabel: 'Reply All', rightLabel: 'Career Disaster', difficulty: 3 },
      { id: 'wrk_3_78', leftLabel: 'CC Manager', rightLabel: 'Political Move', difficulty: 3 },
      { id: 'wrk_3_79', leftLabel: 'BCC', rightLabel: 'Secret Office Politics', difficulty: 3 },
      { id: 'wrk_3_80', leftLabel: 'Per My Last Email', rightLabel: 'Office Passive Aggression', difficulty: 3 },
      { id: 'wrk_3_81', leftLabel: 'Gentle Reminder', rightLabel: 'Very Aggressive Reminder', difficulty: 3 },
      { id: 'wrk_3_82', leftLabel: 'Sure', rightLabel: 'Sure... 👀', difficulty: 3 },
      { id: 'wrk_3_83', leftLabel: 'Okay', rightLabel: 'Okay ❤️', difficulty: 3 },
      { id: 'wrk_3_84', leftLabel: 'Noted', rightLabel: 'Noted 👍', difficulty: 3 },
      { id: 'wrk_3_85', leftLabel: 'Professional Reply', rightLabel: 'Flirty Reply', difficulty: 3 },
      { id: 'wrk_3_86', leftLabel: 'Formal Goodbye', rightLabel: 'Personal Goodbye', difficulty: 3 },
      { id: 'wrk_3_87', leftLabel: 'Goodnight', rightLabel: 'Don’t Want to Say Goodnight', difficulty: 3 },
      { id: 'wrk_3_88', leftLabel: 'Casual Call', rightLabel: 'Call Until 2 AM', difficulty: 3 },
      { id: 'wrk_3_89', leftLabel: 'Coffee', rightLabel: 'Coffee Date', difficulty: 3 },
      { id: 'wrk_3_90', leftLabel: 'Lunch', rightLabel: 'Lunch Date', difficulty: 3 },
      { id: 'wrk_3_91', leftLabel: 'Meeting', rightLabel: 'Excuse to See Them', difficulty: 3 },
      { id: 'wrk_3_92', leftLabel: 'Work Friend', rightLabel: 'Potential Partner', difficulty: 3 },
      { id: 'wrk_3_93', leftLabel: 'Office Crush', rightLabel: 'Office Romance', difficulty: 3 },
      { id: 'wrk_3_94', leftLabel: 'Office Romance', rightLabel: 'Situationship', difficulty: 3 },
      { id: 'wrk_3_95', leftLabel: 'Situationship', rightLabel: 'Office Scandal', difficulty: 3 },
      { id: 'wrk_3_96', leftLabel: 'Safe Flirting', rightLabel: 'HR-Level Flirting', difficulty: 3 },
      { id: 'wrk_3_97', leftLabel: 'Romantic Chemistry', rightLabel: 'Sexual Tension', difficulty: 3 },
      { id: 'wrk_3_98', leftLabel: 'Flirty Vibes', rightLabel: 'Very Steamy Vibes', difficulty: 3 },
      { id: 'wrk_3_99', leftLabel: 'Office Chemistry', rightLabel: 'Can’t Pretend It’s Friendly', difficulty: 3 },
      { id: 'wrk_3_100', leftLabel: 'Normal Workday', rightLabel: 'Workday Full of Drama', difficulty: 3 }
    ],

    4: [
      { id: 'wrk_4_1', leftLabel: 'Office Crush', rightLabel: 'Office Problem', difficulty: 4 },
      { id: 'wrk_4_2', leftLabel: 'Secret Crush', rightLabel: 'Crush Everyone Has Noticed', difficulty: 4 },
      { id: 'wrk_4_3', leftLabel: 'Friendly Hug', rightLabel: 'Definitely Not a Friendly Hug', difficulty: 4 },
      { id: 'wrk_4_4', leftLabel: 'Quick Hug', rightLabel: 'Hug That Changes the Mood', difficulty: 4 },
      { id: 'wrk_4_5', leftLabel: 'Friendly Touch', rightLabel: 'Touch With Obvious Intentions', difficulty: 4 },
      { id: 'wrk_4_6', leftLabel: 'Eye Contact', rightLabel: 'Eye Contact That Feels Dangerous', difficulty: 4 },
      { id: 'wrk_4_7', leftLabel: 'Flirty Smile', rightLabel: 'Smile With Intentions', difficulty: 4 },
      { id: 'wrk_4_8', leftLabel: 'Compliment', rightLabel: 'Compliment That Makes You Blush', difficulty: 4 },
      { id: 'wrk_4_9', leftLabel: 'You Look Good', rightLabel: 'You Know Exactly What You’re Doing', difficulty: 4 },
      { id: 'wrk_4_10', leftLabel: 'Work Question', rightLabel: 'Obvious Excuse to See Them', difficulty: 4 },
      { id: 'wrk_4_11', leftLabel: 'Formal DM', rightLabel: 'Very Personal DM', difficulty: 4 },
      { id: 'wrk_4_12', leftLabel: 'Teams', rightLabel: 'WhatsApp', difficulty: 4 },
      { id: 'wrk_4_13', leftLabel: 'Work WhatsApp', rightLabel: 'Midnight WhatsApp', difficulty: 4 },
      { id: 'wrk_4_14', leftLabel: 'Goodnight', rightLabel: 'Wish You Were Here', difficulty: 4 },
      { id: 'wrk_4_15', leftLabel: 'Good Morning', rightLabel: 'Couldn’t Stop Thinking About You', difficulty: 4 },
      { id: 'wrk_4_16', leftLabel: 'Double Text', rightLabel: 'Shameless Triple Text', difficulty: 4 },
      { id: 'wrk_4_17', leftLabel: 'Story Like', rightLabel: 'Every Story Gets a Reply', difficulty: 4 },
      { id: 'wrk_4_18', leftLabel: 'Instagram Follow', rightLabel: 'Instagram Investigation', difficulty: 4 },
      { id: 'wrk_4_19', leftLabel: 'Chai Break', rightLabel: 'Secret Chai Date', difficulty: 4 },
      { id: 'wrk_4_20', leftLabel: 'Coffee', rightLabel: 'Definitely a Date', difficulty: 4 },
      { id: 'wrk_4_21', leftLabel: 'Lunch', rightLabel: 'Date Disguised as Lunch', difficulty: 4 },
      { id: 'wrk_4_22', leftLabel: 'Team Lunch', rightLabel: 'Ignoring Everyone Else', difficulty: 4 },
      { id: 'wrk_4_23', leftLabel: 'Office Party', rightLabel: 'After-Party', difficulty: 4 },
      { id: 'wrk_4_24', leftLabel: 'After-Party', rightLabel: 'Things Nobody Discusses Monday', difficulty: 4 },
      { id: 'wrk_4_25', leftLabel: 'Team Building', rightLabel: 'Unexpected Chemistry', difficulty: 4 },
      { id: 'wrk_4_26', leftLabel: 'Business Trip', rightLabel: 'Suspiciously Fun Business Trip', difficulty: 4 },
      { id: 'wrk_4_27', leftLabel: 'Work Trip', rightLabel: 'Accidental Date', difficulty: 4 },
      { id: 'wrk_4_28', leftLabel: 'Cab Ride', rightLabel: 'Cab Ride With Serious Tension', difficulty: 4 },
      { id: 'wrk_4_29', leftLabel: 'Lift Ride', rightLabel: 'Too Much Eye Contact', difficulty: 4 },
      { id: 'wrk_4_30', leftLabel: 'Meeting Room', rightLabel: 'Meeting Room With Suspicious Chemistry', difficulty: 4 },
      { id: 'wrk_4_31', leftLabel: 'Calendar Invite', rightLabel: 'Why Is It Just Us?', difficulty: 4 },
      { id: 'wrk_4_32', leftLabel: 'One-on-One', rightLabel: 'One-on-One That Feels Like a Date', difficulty: 4 },
      { id: 'wrk_4_33', leftLabel: 'Office Corridor', rightLabel: 'Dangerous Eye Contact', difficulty: 4 },
      { id: 'wrk_4_34', leftLabel: 'Pantry', rightLabel: 'Gossip Headquarters', difficulty: 4 },
      { id: 'wrk_4_35', leftLabel: 'Cafeteria', rightLabel: 'Secret Meeting Spot', difficulty: 4 },
      { id: 'wrk_4_36', leftLabel: 'Parking Lot', rightLabel: 'Private Conversation', difficulty: 4 },
      { id: 'wrk_4_37', leftLabel: 'Late Office', rightLabel: 'Empty Office', difficulty: 4 },
      { id: 'wrk_4_38', leftLabel: 'Empty Office', rightLabel: 'Very Interesting Chemistry', difficulty: 4 },
      { id: 'wrk_4_39', leftLabel: 'Working Late', rightLabel: 'Suddenly Enjoying Overtime', difficulty: 4 },
      { id: 'wrk_4_40', leftLabel: 'Goodbye', rightLabel: 'Stay a Little Longer', difficulty: 4 },
      { id: 'wrk_4_41', leftLabel: 'Goodbye Hug', rightLabel: 'Hug That Lasts Way Too Long', difficulty: 4 },
      { id: 'wrk_4_42', leftLabel: 'Cheek Kiss', rightLabel: 'Almost Kiss', difficulty: 4 },
      { id: 'wrk_4_43', leftLabel: 'Almost Kiss', rightLabel: 'Kiss That Changes Everything', difficulty: 4 },
      { id: 'wrk_4_44', leftLabel: 'Sweet Kiss', rightLabel: 'Passionate Kiss', difficulty: 4 },
      { id: 'wrk_4_45', leftLabel: 'Quick Kiss', rightLabel: 'Long Kiss', difficulty: 4 },
      { id: 'wrk_4_46', leftLabel: 'Romantic Kiss', rightLabel: 'Intense Kiss', difficulty: 4 },
      { id: 'wrk_4_47', leftLabel: 'Cute', rightLabel: 'Dangerously Attractive', difficulty: 4 },
      { id: 'wrk_4_48', leftLabel: 'Attractive', rightLabel: 'Distractingly Sexy', difficulty: 4 },
      { id: 'wrk_4_49', leftLabel: 'Friendly', rightLabel: 'Clearly Into Each Other', difficulty: 4 },
      { id: 'wrk_4_50', leftLabel: 'Flirty', rightLabel: 'Unfairly Flirty', difficulty: 4 },
      { id: 'wrk_4_51', leftLabel: 'Small Crush', rightLabel: 'Can’t Stop Thinking About Them', difficulty: 4 },
      { id: 'wrk_4_52', leftLabel: 'Office Bestie', rightLabel: 'Office Crush', difficulty: 4 },
      { id: 'wrk_4_53', leftLabel: 'Office Crush', rightLabel: 'Secret Date', difficulty: 4 },
      { id: 'wrk_4_54', leftLabel: 'Secret Date', rightLabel: 'Actual Relationship', difficulty: 4 },
      { id: 'wrk_4_55', leftLabel: 'Office Romance', rightLabel: 'Office Scandal', difficulty: 4 },
      { id: 'wrk_4_56', leftLabel: 'Office Gossip', rightLabel: 'HR Risk', difficulty: 4 },
      { id: 'wrk_4_57', leftLabel: 'Rumour', rightLabel: 'Whole Floor Knows', difficulty: 4 },
      { id: 'wrk_4_58', leftLabel: 'Private Chat', rightLabel: 'Screenshotted in Group', difficulty: 4 },
      { id: 'wrk_4_59', leftLabel: 'One Person Knows', rightLabel: 'Whole Team Knows', difficulty: 4 },
      { id: 'wrk_4_60', leftLabel: 'Manager Favourite', rightLabel: 'Suspicious Favourite', difficulty: 4 },
      { id: 'wrk_4_61', leftLabel: 'Boss Compliment', rightLabel: 'Too Personal Compliment', difficulty: 4 },
      { id: 'wrk_4_62', leftLabel: 'Manager Feedback', rightLabel: 'Personal Conversation', difficulty: 4 },
      { id: 'wrk_4_63', leftLabel: 'Performance Review', rightLabel: 'Salary Negotiation', difficulty: 4 },
      { id: 'wrk_4_64', leftLabel: 'Appraisal', rightLabel: 'Appraisal Drama', difficulty: 4 },
      { id: 'wrk_4_65', leftLabel: 'Promotion', rightLabel: 'Promotion Politics', difficulty: 4 },
      { id: 'wrk_4_66', leftLabel: 'Increment', rightLabel: 'Increment Jealousy', difficulty: 4 },
      { id: 'wrk_4_67', leftLabel: 'Bonus', rightLabel: 'Bonus Everyone Compares', difficulty: 4 },
      { id: 'wrk_4_68', leftLabel: 'Favourite Employee', rightLabel: 'Obvious Favouritism', difficulty: 4 },
      { id: 'wrk_4_69', leftLabel: 'Hard Worker', rightLabel: 'Office Martyr', difficulty: 4 },
      { id: 'wrk_4_70', leftLabel: 'Smart Worker', rightLabel: 'Corporate Survivor', difficulty: 4 },
      { id: 'wrk_4_71', leftLabel: 'Leaving at 6', rightLabel: 'Waiting for Boss', difficulty: 4 },
      { id: 'wrk_4_72', leftLabel: '5 PM', rightLabel: 'Midnight', difficulty: 4 },
      { id: 'wrk_4_73', leftLabel: 'Friday Evening', rightLabel: 'Monday Morning Regret', difficulty: 4 },
      { id: 'wrk_4_74', leftLabel: 'Weekend', rightLabel: 'Weekend Work Emergency', difficulty: 4 },
      { id: 'wrk_4_75', leftLabel: 'Holiday', rightLabel: 'Holiday Work Call', difficulty: 4 },
      { id: 'wrk_4_76', leftLabel: 'WFH', rightLabel: 'WFH But Dressing Up for Someone', difficulty: 4 },
      { id: 'wrk_4_77', leftLabel: 'Camera Off', rightLabel: 'Definitely Distracted', difficulty: 4 },
      { id: 'wrk_4_78', leftLabel: 'Mute', rightLabel: 'Saying Something Risky', difficulty: 4 },
      { id: 'wrk_4_79', leftLabel: 'Screen Share', rightLabel: 'Wrong WhatsApp Chat', difficulty: 4 },
      { id: 'wrk_4_80', leftLabel: 'Reply All', rightLabel: 'Career Risk', difficulty: 4 },
      { id: 'wrk_4_81', leftLabel: 'CC Manager', rightLabel: 'Corporate Warning Shot', difficulty: 4 },
      { id: 'wrk_4_82', leftLabel: 'BCC', rightLabel: 'Secret Office Politics', difficulty: 4 },
      { id: 'wrk_4_83', leftLabel: 'Per My Last Email', rightLabel: 'I Am Done With You', difficulty: 4 },
      { id: 'wrk_4_84', leftLabel: 'Gentle Reminder', rightLabel: 'Absolutely Not Gentle', difficulty: 4 },
      { id: 'wrk_4_85', leftLabel: 'Sure', rightLabel: 'Sure... 👀', difficulty: 4 },
      { id: 'wrk_4_86', leftLabel: 'Okay', rightLabel: 'Okay ❤️', difficulty: 4 },
      { id: 'wrk_4_87', leftLabel: 'Noted', rightLabel: 'Noted 👍', difficulty: 4 },
      { id: 'wrk_4_88', leftLabel: 'Professional Reply', rightLabel: 'Flirty Reply', difficulty: 4 },
      { id: 'wrk_4_89', leftLabel: 'Formal Goodbye', rightLabel: 'Personal Goodbye', difficulty: 4 },
      { id: 'wrk_4_90', leftLabel: 'Goodnight', rightLabel: 'Don’t Want to Say Goodnight', difficulty: 4 },
      { id: 'wrk_4_91', leftLabel: 'Call', rightLabel: 'Call Until Morning', difficulty: 4 },
      { id: 'wrk_4_92', leftLabel: 'Coffee', rightLabel: 'Secret Date', difficulty: 4 },
      { id: 'wrk_4_93', leftLabel: 'Lunch', rightLabel: 'Definitely a Date', difficulty: 4 },
      { id: 'wrk_4_94', leftLabel: 'Meeting', rightLabel: 'Excuse to Be Alone', difficulty: 4 },
      { id: 'wrk_4_95', leftLabel: 'Work Friend', rightLabel: 'Potential Relationship', difficulty: 4 },
      { id: 'wrk_4_96', leftLabel: 'Office Crush', rightLabel: 'Office Romance', difficulty: 4 },
      { id: 'wrk_4_97', leftLabel: 'Office Romance', rightLabel: 'Situationship', difficulty: 4 },
      { id: 'wrk_4_98', leftLabel: 'Situationship', rightLabel: 'Office Scandal', difficulty: 4 },
      { id: 'wrk_4_99', leftLabel: 'Romantic Chemistry', rightLabel: 'Sexual Tension', difficulty: 4 },
      { id: 'wrk_4_100', leftLabel: 'Sexual Tension', rightLabel: 'Career-Risk Spicy', difficulty: 4 }
    ],

    5: [
      { id: 'wrk_5_1', leftLabel: 'Office Crush', rightLabel: 'Career-Risk Crush', difficulty: 5 },
      { id: 'wrk_5_2', leftLabel: 'Secret Crush', rightLabel: 'Everyone Knows', difficulty: 5 },
      { id: 'wrk_5_3', leftLabel: 'Friendly Hug', rightLabel: 'Definitely Not Professional', difficulty: 5 },
      { id: 'wrk_5_4', leftLabel: 'Quick Hug', rightLabel: 'Hug You Never Want to End', difficulty: 5 },
      { id: 'wrk_5_5', leftLabel: 'Friendly Touch', rightLabel: 'Touch With Obvious Intentions', difficulty: 5 },
      { id: 'wrk_5_6', leftLabel: 'Eye Contact', rightLabel: 'Eye Contact You Can’t Maintain', difficulty: 5 },
      { id: 'wrk_5_7', leftLabel: 'Flirty Smile', rightLabel: 'Smile That Completely Distracts You', difficulty: 5 },
      { id: 'wrk_5_8', leftLabel: 'Compliment', rightLabel: 'Compliment That Changes the Mood', difficulty: 5 },
      { id: 'wrk_5_9', leftLabel: 'You Look Good', rightLabel: 'You Are Making This Difficult', difficulty: 5 },
      { id: 'wrk_5_10', leftLabel: 'Work Question', rightLabel: 'Obvious Excuse to Talk', difficulty: 5 },
      { id: 'wrk_5_11', leftLabel: 'Formal DM', rightLabel: 'DM With Dangerous Intentions', difficulty: 5 },
      { id: 'wrk_5_12', leftLabel: 'Teams', rightLabel: 'Personal WhatsApp', difficulty: 5 },
      { id: 'wrk_5_13', leftLabel: 'Work WhatsApp', rightLabel: 'Midnight Personal WhatsApp', difficulty: 5 },
      { id: 'wrk_5_14', leftLabel: 'Goodnight', rightLabel: 'Wish You Were Here', difficulty: 5 },
      { id: 'wrk_5_15', leftLabel: 'Good Morning', rightLabel: 'Couldn’t Stop Thinking About You', difficulty: 5 },
      { id: 'wrk_5_16', leftLabel: 'Double Text', rightLabel: 'Shameless Triple Text', difficulty: 5 },
      { id: 'wrk_5_17', leftLabel: 'Story Like', rightLabel: 'Story Reply With Intentions', difficulty: 5 },
      { id: 'wrk_5_18', leftLabel: 'Instagram Follow', rightLabel: 'Instagram Investigation', difficulty: 5 },
      { id: 'wrk_5_19', leftLabel: 'Chai Break', rightLabel: 'Secret Chai Date', difficulty: 5 },
      { id: 'wrk_5_20', leftLabel: 'Coffee', rightLabel: 'Coffee That Turns Into Midnight', difficulty: 5 },
      { id: 'wrk_5_21', leftLabel: 'Lunch', rightLabel: 'Date Disguised as Lunch', difficulty: 5 },
      { id: 'wrk_5_22', leftLabel: 'Team Lunch', rightLabel: 'Only Watching One Person', difficulty: 5 },
      { id: 'wrk_5_23', leftLabel: 'Office Party', rightLabel: 'After-Party Chemistry', difficulty: 5 },
      { id: 'wrk_5_24', leftLabel: 'After-Party', rightLabel: 'Things You Don’t Mention Monday', difficulty: 5 },
      { id: 'wrk_5_25', leftLabel: 'Team Building', rightLabel: 'Unexpected Attraction', difficulty: 5 },
      { id: 'wrk_5_26', leftLabel: 'Business Trip', rightLabel: 'Business Trip With Chemistry', difficulty: 5 },
      { id: 'wrk_5_27', leftLabel: 'Work Trip', rightLabel: 'Accidental Date', difficulty: 5 },
      { id: 'wrk_5_28', leftLabel: 'Cab Ride', rightLabel: 'Cab Ride Nobody Wants to End', difficulty: 5 },
      { id: 'wrk_5_29', leftLabel: 'Lift Ride', rightLabel: 'Way Too Much Eye Contact', difficulty: 5 },
      { id: 'wrk_5_30', leftLabel: 'Meeting Room', rightLabel: 'Meeting Room With Serious Tension', difficulty: 5 },
      { id: 'wrk_5_31', leftLabel: 'Calendar Invite', rightLabel: 'Why Is It Just Us?', difficulty: 5 },
      { id: 'wrk_5_32', leftLabel: 'One-on-One', rightLabel: 'One-on-One That Feels Like a Date', difficulty: 5 },
      { id: 'wrk_5_33', leftLabel: 'Office Corridor', rightLabel: 'Dangerous Eye Contact', difficulty: 5 },
      { id: 'wrk_5_34', leftLabel: 'Pantry', rightLabel: 'Secret Dating Spot', difficulty: 5 },
      { id: 'wrk_5_35', leftLabel: 'Cafeteria', rightLabel: 'Office Dating Zone', difficulty: 5 },
      { id: 'wrk_5_36', leftLabel: 'Parking Lot', rightLabel: 'Private Conversation', difficulty: 5 },
      { id: 'wrk_5_37', leftLabel: 'Late Office', rightLabel: 'Empty Office', difficulty: 5 },
      { id: 'wrk_5_38', leftLabel: 'Empty Office', rightLabel: 'Chemistry Nobody Can Ignore', difficulty: 5 },
      { id: 'wrk_5_39', leftLabel: 'Working Late', rightLabel: 'Suddenly Enjoying Overtime', difficulty: 5 },
      { id: 'wrk_5_40', leftLabel: 'Goodbye', rightLabel: 'Please Don’t Leave Yet', difficulty: 5 },
      { id: 'wrk_5_41', leftLabel: 'Goodbye Hug', rightLabel: 'Hug That Changes Everything', difficulty: 5 },
      { id: 'wrk_5_42', leftLabel: 'Cheek Kiss', rightLabel: 'Almost Kiss', difficulty: 5 },
      { id: 'wrk_5_43', leftLabel: 'Almost Kiss', rightLabel: 'Kiss That Changes the Relationship', difficulty: 5 },
      { id: 'wrk_5_44', leftLabel: 'Sweet Kiss', rightLabel: 'Passionate Kiss', difficulty: 5 },
      { id: 'wrk_5_45', leftLabel: 'Quick Kiss', rightLabel: 'Long Kiss', difficulty: 5 },
      { id: 'wrk_5_46', leftLabel: 'Romantic Kiss', rightLabel: 'Kiss You Keep Thinking About', difficulty: 5 },
      { id: 'wrk_5_47', leftLabel: 'Cute', rightLabel: 'Dangerously Attractive', difficulty: 5 },
      { id: 'wrk_5_48', leftLabel: 'Attractive', rightLabel: 'Distractingly Sexy', difficulty: 5 },
      { id: 'wrk_5_49', leftLabel: 'Friendly', rightLabel: 'Clearly Into Each Other', difficulty: 5 },
      { id: 'wrk_5_50', leftLabel: 'Flirty', rightLabel: 'Absolutely Shameless', difficulty: 5 },
      { id: 'wrk_5_51', leftLabel: 'Small Crush', rightLabel: 'Can’t Stop Thinking About Them', difficulty: 5 },
      { id: 'wrk_5_52', leftLabel: 'Office Bestie', rightLabel: 'Office Crush', difficulty: 5 },
      { id: 'wrk_5_53', leftLabel: 'Office Crush', rightLabel: 'Secret Date', difficulty: 5 },
      { id: 'wrk_5_54', leftLabel: 'Secret Date', rightLabel: 'Actual Relationship', difficulty: 5 },
      { id: 'wrk_5_55', leftLabel: 'Office Romance', rightLabel: 'Office Scandal', difficulty: 5 },
      { id: 'wrk_5_56', leftLabel: 'Office Gossip', rightLabel: 'HR Investigation', difficulty: 5 },
      { id: 'wrk_5_57', leftLabel: 'Rumour', rightLabel: 'Whole Company Knows', difficulty: 5 },
      { id: 'wrk_5_58', leftLabel: 'Private Chat', rightLabel: 'Screenshotted Everywhere', difficulty: 5 },
      { id: 'wrk_5_59', leftLabel: 'One Person Knows', rightLabel: 'Entire Floor Knows', difficulty: 5 },
      { id: 'wrk_5_60', leftLabel: 'Manager Favourite', rightLabel: 'Suspiciously Favoured', difficulty: 5 },
      { id: 'wrk_5_61', leftLabel: 'Boss Compliment', rightLabel: 'Too Personal for Work', difficulty: 5 },
      { id: 'wrk_5_62', leftLabel: 'Manager Feedback', rightLabel: 'Conversation That Feels Personal', difficulty: 5 },
      { id: 'wrk_5_63', leftLabel: 'Performance Review', rightLabel: 'Salary Negotiation', difficulty: 5 },
      { id: 'wrk_5_64', leftLabel: 'Appraisal', rightLabel: 'Appraisal Breakdown', difficulty: 5 },
      { id: 'wrk_5_65', leftLabel: 'Promotion', rightLabel: 'Promotion Politics', difficulty: 5 },
      { id: 'wrk_5_66', leftLabel: 'Increment', rightLabel: 'Increment Everyone Compares', difficulty: 5 },
      { id: 'wrk_5_67', leftLabel: 'Bonus', rightLabel: 'Bonus That Starts Fights', difficulty: 5 },
      { id: 'wrk_5_68', leftLabel: 'Favourite Employee', rightLabel: 'Obvious Favouritism', difficulty: 5 },
      { id: 'wrk_5_69', leftLabel: 'Hard Worker', rightLabel: 'Office Martyr', difficulty: 5 },
      { id: 'wrk_5_70', leftLabel: 'Smart Worker', rightLabel: 'Corporate Survivor', difficulty: 5 },
      { id: 'wrk_5_71', leftLabel: 'Leaving at 6', rightLabel: 'Waiting for Boss', difficulty: 5 },
      { id: 'wrk_5_72', leftLabel: '5 PM', rightLabel: '2 AM', difficulty: 5 },
      { id: 'wrk_5_73', leftLabel: 'Friday Evening', rightLabel: 'Monday Morning Regret', difficulty: 5 },
      { id: 'wrk_5_74', leftLabel: 'Weekend', rightLabel: 'Weekend Work Emergency', difficulty: 5 },
      { id: 'wrk_5_75', leftLabel: 'Holiday', rightLabel: 'Holiday Work Call', difficulty: 5 },
      { id: 'wrk_5_76', leftLabel: 'WFH', rightLabel: 'WFH But Looking Good for One Person', difficulty: 5 },
      { id: 'wrk_5_77', leftLabel: 'Camera Off', rightLabel: 'Definitely Doing Something Else', difficulty: 5 },
      { id: 'wrk_5_78', leftLabel: 'Mute', rightLabel: 'Saying Something Career-Limiting', difficulty: 5 },
      { id: 'wrk_5_79', leftLabel: 'Screen Share', rightLabel: 'Wrong Personal Chat', difficulty: 5 },
      { id: 'wrk_5_80', leftLabel: 'Reply All', rightLabel: 'Career Disaster', difficulty: 5 },
      { id: 'wrk_5_81', leftLabel: 'CC Manager', rightLabel: 'Corporate Warning Shot', difficulty: 5 },
      { id: 'wrk_5_82', leftLabel: 'BCC', rightLabel: 'Secret Political Move', difficulty: 5 },
      { id: 'wrk_5_83', leftLabel: 'Per My Last Email', rightLabel: 'I Am Done With You', difficulty: 5 },
      { id: 'wrk_5_84', leftLabel: 'Gentle Reminder', rightLabel: 'Absolutely Not Gentle', difficulty: 5 },
      { id: 'wrk_5_85', leftLabel: 'Sure', rightLabel: 'Sure... 👀', difficulty: 5 },
      { id: 'wrk_5_86', leftLabel: 'Okay', rightLabel: 'Okay ❤️', difficulty: 5 },
      { id: 'wrk_5_87', leftLabel: 'Noted', rightLabel: 'Noted 👍', difficulty: 5 },
      { id: 'wrk_5_88', leftLabel: 'Professional Reply', rightLabel: 'Flirty Reply', difficulty: 5 },
      { id: 'wrk_5_89', leftLabel: 'Formal Goodbye', rightLabel: 'Personal Goodbye', difficulty: 5 },
      { id: 'wrk_5_90', leftLabel: 'Goodnight', rightLabel: 'Don’t Want to Say Goodnight', difficulty: 5 },
      { id: 'wrk_5_91', leftLabel: 'Call', rightLabel: 'Call Until Morning', difficulty: 5 },
      { id: 'wrk_5_92', leftLabel: 'Coffee', rightLabel: 'Secret Date', difficulty: 5 },
      { id: 'wrk_5_93', leftLabel: 'Lunch', rightLabel: 'Definitely a Date', difficulty: 5 },
      { id: 'wrk_5_94', leftLabel: 'Meeting', rightLabel: 'Excuse to Be Alone', difficulty: 5 },
      { id: 'wrk_5_95', leftLabel: 'Work Friend', rightLabel: 'Potential Partner', difficulty: 5 },
      { id: 'wrk_5_96', leftLabel: 'Office Crush', rightLabel: 'Office Romance', difficulty: 5 },
      { id: 'wrk_5_97', leftLabel: 'Office Romance', rightLabel: 'Situationship', difficulty: 5 },
      { id: 'wrk_5_98', leftLabel: 'Situationship', rightLabel: 'Office Scandal', difficulty: 5 },
      { id: 'wrk_5_99', leftLabel: 'Romantic Chemistry', rightLabel: 'Sexual Tension', difficulty: 5 },
      { id: 'wrk_5_100', leftLabel: 'Professional', rightLabel: 'Story You’ll Never Tell HR', difficulty: 5 }
    ]
  }
};
